/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 가입 화면이 알아야 하는 규칙
         * @description 비밀번호 규칙과, 가입할 때 받아야 하는 동의의 종류와 지금 판을 돌려준다.
         *     가입 화면은 이 값을 코드에 박아 두지 않고 여기서 받아서 보여주고, 받은 `consents`를 가입 요청에 그대로 실어 보낸다.
         */
        get: operations["getAuthRequirements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입
         * @description 계정을 만들고 바로 로그인된 상태로 만든다. 응답에 세션 쿠키가 실린다.
         *     요청에 세션 쿠키가 딸려 왔으면 그 세션은 끊긴다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일과 비밀번호를 확인하고 새 세션을 연다. 응답에 세션 쿠키가 실린다.
         *     요청에 세션 쿠키가 딸려 왔으면 그 세션은 끊기고 새 토큰으로 바뀐다.
         *     실패의 까닭(없는 이메일, 틀린 비밀번호)은 구분해서 알려주지 않는다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 지금 세션을 끊고 쿠키를 지운다. 몇 번을 불러도 결과가 같다. 세션이 없거나 이미 끝났어도 204다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로그인한 사용자와 설정
         * @description 앱을 열 때 로그인 상태인지 알아보는 데에도 쓴다. 401이면 로그인 화면으로 보낸다.
         *     세션이 끝났으면 401과 함께 쿠키를 지우는 `Set-Cookie`가 실린다.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 한 달의 일기 목록, 또는 검색
         * @description `month`와 `q` 가운데 하나만 준다. 둘 다 주거나 둘 다 주지 않으면 `400 validation_failed`다.
         *
         *     - `month`를 주면 그 달의 일기를 날짜순으로 돌려준다. 일기가 없는 날은 목록에 없다.
         *     - `q`를 주면 본인의 모든 일기에서 그 글자가 들어 있는 것을 최근 날짜부터 돌려준다.
         *       영문은 대소문자를 가리지 않는다. 앞뒤 공백은 떼고 찾는다. 공백만 있는 검색어는 `422 validation_failed`(`fields: [q]`)다.
         *       아직 확인하지 않은 초안도 찾는다.
         *
         *     목록의 `first_line`은 지금 화면에 보일 글의 첫 줄이다. 상태가 `draft`면 초안의, `confirmed`면 확인한 글의 첫 줄이다.
         */
        get: operations["listDiaries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diaries/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 기록 날짜. `YYYY-MM-DD` 꼴이다 */
                date: components["parameters"]["RecordDate"];
            };
            cookie?: never;
        };
        /**
         * 하루의 일기
         * @description 그날의 일기를 돌려준다. 상태가 `draft`면 `text`는 대화에서 만든 초안이고, `confirmed`면 사용자가 확인한 글이다.
         *     확인한 뒤에 그날 다시 대화하면 새 대화의 내용을 이어 붙인 초안이 생기고 상태가 `draft`로 돌아간다. 사용자가 다시 확인한다.
         *
         *     그날의 일기가 없으면 `404 not_found`다. 대화가 막 끝나 초안을 만드는 중일 때도, 초안을 자동으로 만들지 않은 날도 그렇다.
         */
        get: operations["getDiary"];
        /**
         * 일기를 고치고 확인한다
         * @description 보낸 글이 그날의 일기가 되고 상태가 `confirmed`가 된다. 초안을 고치지 않고 그대로 확인할 때도 그 글을 그대로 보낸다.
         *     바뀌는 것은 일기 글뿐이다. 대화에서 나온 마음 신호는 바뀌지 않는다.
         *
         *     그날의 일기가 아직 없어도 대화한 날이면 새로 만든다. 초안을 자동으로 만들지 않은 날에도 사용자는 일기를 직접 쓸 수 있다.
         *     대화하지 않은 날이면 `404 not_found`다.
         *
         *     글의 앞뒤 공백은 떼고 저장한다. 공백만 있는 글은 `422 validation_failed`(`fields: [text]`)다.
         */
        put: operations["putDiary"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/days/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 기록 날짜. `YYYY-MM-DD` 꼴이다 */
                date: components["parameters"]["RecordDate"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 하루를 지운다
         * @description 그날의 일기만이 아니라 그날의 대화, 발화, 마음 신호와 그 근거, 그날에서 나온 기억까지 함께 지운다.
         *     지운 것은 되돌릴 수 없다. 추세는 남은 기록으로 다시 계산된다.
         *     화면은 무엇이 함께 지워지는지 알리고 한 번 더 확인받은 뒤에 이 요청을 보낸다.
         *
         *     그날에 열려 있는 대화가 있으면 그 대화도 함께 지워진다.
         *     그날의 기록이 없으면 `404 not_found`다. 이미 지운 날을 다시 지우려 해도 그렇다.
         */
        delete: operations["deleteDay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 도움이 필요할 때 연락할 수 있는 곳
         * @description 언제든 열 수 있는 "도움이 필요할 때" 화면이 보여주는 목록이다. 로그인하지 않아도 열린다.
         *     급한 곳이 앞에 온다. 전화번호는 누르면 바로 걸리게 한다(`tel:`).
         *     대화 도중에 서버가 보내는 `resources` 메시지도 같은 모양이다.
         */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date-time
         * @description UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
         * @example 2026-09-20T12:00:00.000Z
         */
        Timestamp: string;
        /**
         * @description 동의의 종류.
         *     `terms` 이용약관, `privacy` 개인정보 처리방침, `sensitive_data` 마음에 관한 기록의 처리,
         *     `overseas_transfer` 대화 내용이 외부 AI 서비스로 전송되어 해외에서 처리되는 것.
         * @enum {string}
         */
        ConsentKind: "terms" | "privacy" | "sensitive_data" | "overseas_transfer";
        ConsentGrant: {
            kind: components["schemas"]["ConsentKind"];
            /**
             * @description 사용자가 보고 동의한 문서의 판
             * @example 2026-09-20
             */
            version: string;
        };
        PasswordRequirements: {
            /**
             * @description 최소 길이. 글자 수로 센다
             * @example 10
             */
            min_length: number;
            /**
             * @description 최대 길이. UTF-8 바이트로 센다(한글 한 글자는 3바이트)
             * @example 128
             */
            max_bytes: number;
        };
        AuthRequirements: {
            password: components["schemas"]["PasswordRequirements"];
            /** @description 가입에 필요한 동의와 그 지금 판. 모두 필수다 */
            consents: components["schemas"]["ConsentGrant"][];
            /**
             * @description 부를 이름의 최대 글자 수
             * @example 40
             */
            display_name_max_length: number;
        };
        SignupRequest: {
            email: string;
            password: string;
            /** @description 부를 이름. 비워 둘 수 있다. 앞뒤 공백을 떼고 40자까지 받는다 */
            display_name?: string;
            /**
             * @description IANA 시간대 이름(예: `Asia/Seoul`). 브라우저의 `Intl.DateTimeFormat().resolvedOptions().timeZone` 값을 보낸다.
             *     하루의 경계와 알림 시각이 이 값으로 계산된다. 보내지 않으면 `Asia/Seoul`이다.
             */
            timezone?: string;
            /** @description `GET /api/v1/auth/requirements`가 준 동의 목록 가운데 사용자가 동의한 것 */
            consents: components["schemas"]["ConsentGrant"][];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @description 부를 이름. 정하지 않았으면 null이다 */
            display_name: string | null;
            /**
             * @description IANA 시간대 이름
             * @example Asia/Seoul
             */
            timezone: string;
            /** @description 둘러보기용으로 만들어진 계정인지 */
            is_demo: boolean;
            created_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description 대화를 시작할 때의 기본 방식
         * @enum {string}
         */
        ConversationMode: "voice" | "chat";
        SettingsSummary: {
            reminder_enabled: boolean;
            /**
             * @description 알림 시각. 사용자 시간대의 벽시계 시각이고 `HH:MM` 꼴이다
             * @example 20:00
             */
            reminder_time: string;
            default_mode: components["schemas"]["ConversationMode"];
            /** @description 끄면 대화와 일기만 남기고 마음 신호를 뽑지 않는다 */
            analysis_enabled: boolean;
            memory_enabled: boolean;
            mood_pick_enabled: boolean;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
        };
        /**
         * Format: date
         * @description 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
         *     서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
         * @example 2026-09-20
         */
        RecordDate: string;
        /**
         * @description `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
         * @enum {string}
         */
        DiaryStatus: "draft" | "confirmed";
        DiarySummary: {
            date: components["schemas"]["RecordDate"];
            status: components["schemas"]["DiaryStatus"];
            /** @description 지금 화면에 보일 글의 첫 줄. 길면 잘라서 준다. 빈 초안이면 빈 문자열이다 */
            first_line: string;
            /** @description 검색어가 나온 자리의 앞뒤 글. 검색 결과에만 있다 */
            snippet?: string;
        };
        DiaryList: {
            items: components["schemas"]["DiarySummary"][];
        };
        Diary: {
            date: components["schemas"]["RecordDate"];
            status: components["schemas"]["DiaryStatus"];
            /**
             * @description 상태가 `draft`면 초안, `confirmed`면 확인한 글이다.
             *     초안을 만들지 못한 날에는 빈 초안이 온다. 사용자가 직접 써서 확인하면 된다.
             */
            text: string;
            /** @description 마지막으로 확인한 시각. 한 번도 확인하지 않았으면 null이다 */
            confirmed_at: components["schemas"]["Timestamp"] | null;
            updated_at: components["schemas"]["Timestamp"];
        };
        DiaryUpdate: {
            /** @description 일기 글 전체 */
            text: string;
        };
        Resource: {
            /**
             * @description 자원을 가리키는 고정된 이름. 화면이 아이콘을 고르거나 목록을 견줄 때 쓴다
             * @example suicide_prevention_109
             */
            id: string;
            /** @example 자살예방상담전화 */
            name: string;
            /**
             * @description 전화번호. 화면에 그대로 보여주고, 걸 때는 숫자만 남겨 `tel:`에 넣는다
             * @example 109
             */
            phone: string;
            /**
             * @description 언제, 어떤 도움을 받을 수 있는지에 대한 한두 문장
             * @example 24시간, 지금 바로 이야기를 들어줄 사람과 연결돼요.
             */
            description: string;
        };
        ResourceList: {
            /** @description 급한 곳이 앞에 온다 */
            items: components["schemas"]["Resource"][];
        };
        /** @description 클라이언트가 대화 채널로 보내는 메시지. `type`으로 가린다 */
        WsClientMessage: components["schemas"]["WsStart"] | components["schemas"]["WsUserText"] | components["schemas"]["WsEnd"];
        /** @description 서버가 대화 채널로 보내는 메시지. `type`으로 가린다 */
        WsServerMessage: components["schemas"]["WsReady"] | components["schemas"]["WsThinking"] | components["schemas"]["WsAIText"] | components["schemas"]["WsResources"] | components["schemas"]["WsEnded"] | components["schemas"]["WsDiaryReady"] | components["schemas"]["WsError"];
        /**
         * @description 대화를 시작한다. 연결마다 한 번 보낸다. 열린 대화가 있으면 새로 만들지 않고 그 대화를 이어간다.
         *     기록 날짜가 지나도록 열려 있던 대화는 서버가 먼저 끝내고 새 대화를 연다.
         */
        WsStart: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "start";
            /** @description 대화 방식. 지금은 `chat`만 받는다. 다른 값에는 `error`(`unsupported_mode`)가 온다 */
            mode: components["schemas"]["ConversationMode"];
        };
        /** @description 사용자가 쓴 글 하나 */
        WsUserText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "user_text";
            /**
             * Format: uuid
             * @description 클라이언트가 글마다 새로 만드는 식별자(`crypto.randomUUID()`).
             *     `thinking`을 받지 못해 다시 보낼 때는 같은 값을 쓴다. 같은 값의 글은 한 번만 저장된다.
             */
            client_message_id: string;
            /** @description 앞뒤 공백을 뗀 글. 공백만 있는 글은 보내지 않는다 */
            text: string;
        };
        /** @description 끝내기 버튼을 눌렀다. 서버는 `ended`로 답한다 */
        WsEnd: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "end";
        };
        /**
         * @description 누가 한 말인지
         * @enum {string}
         */
        WsSpeaker: "user" | "ai";
        /**
         * @description 말을 만든 쪽. `user` 사용자, `model` 대화 AI, `fixed` 미리 써 둔 문구,
         *     `template` 사용자의 표현을 넣어 만든 고정 문형.
         * @enum {string}
         */
        WsOrigin: "user" | "model" | "fixed" | "template";
        /** @description 지난 발화 하나. 이어가는 대화의 `ready`에 담겨 온다 */
        WsUtterance: {
            /** @description 대화 안에서의 순번. 0부터 하나씩 는다. 화면은 이 순서대로 보여준다 */
            seq: number;
            speaker: components["schemas"]["WsSpeaker"];
            origin: components["schemas"]["WsOrigin"];
            text: string;
            /**
             * Format: uuid
             * @description 사용자의 글이면 보낼 때 붙인 식별자다. 아직 답을 받지 못한 글과 견주는 데 쓴다. AI의 말이면 null이다
             */
            client_message_id: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        /** @description `start`의 답. 이 메시지를 받은 뒤에 글을 보낼 수 있다 */
        WsReady: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ready";
            /** Format: uuid */
            conversation_id: string;
            record_date: components["schemas"]["RecordDate"];
            /** @description 열려 있던 대화를 이어가는 것이면 참이다. 거짓이면 새 대화이고 곧이어 첫 안부가 `ai_text`로 온다 */
            resumed: boolean;
            /** @description 이어가는 대화의 지난 발화. 순번대로다. 새 대화면 비어 있다 */
            utterances: components["schemas"]["WsUtterance"][];
            /** @description 이 대화에서 도움 자원을 화면에 고정해 두었는지. 참이면 곧이어 `resources`가 온다 */
            resources_pinned: boolean;
        };
        /**
         * @description 글을 받아 저장했고 답을 준비하고 있다. 받았다는 확인이기도 하다.
         *     이 메시지가 오지 않으면 같은 `client_message_id`로 다시 보낸다.
         */
        WsThinking: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "thinking";
            /**
             * Format: uuid
             * @description 어느 글에 대한 것인지
             */
            client_message_id: string;
            /** @description 그 글에 붙은 순번 */
            seq: number;
        };
        /** @description AI의 말 하나. 한 번에 통째로 온다 */
        WsAIText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ai_text";
            seq: number;
            text: string;
            /** @description `model`, `fixed`, `template` 가운데 하나다 */
            origin: components["schemas"]["WsOrigin"];
        };
        /** @description 화면에 고정해 둘 도움 자원. 받은 뒤로는 대화가 끝날 때까지 고정해 둔다 */
        WsResources: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resources";
            /** @description 급한 곳이 앞에 온다 */
            items: components["schemas"]["Resource"][];
        };
        /**
         * @description `user` 끝내기 버튼을 눌렀다. `idle` 한동안 말이 없어 서버가 닫았다.
         * @enum {string}
         */
        WsEndReason: "user" | "idle";
        /** @description 대화가 끝났다. 이 연결로는 더 보낼 수 없다. 다시 이야기하려면 새로 연결해 `start`를 보낸다 */
        WsEnded: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ended";
            reason: components["schemas"]["WsEndReason"];
            record_date: components["schemas"]["RecordDate"];
            /**
             * @description 일기 초안을 만들고 있으면 참이다. 준비되면 `diary_ready`가 온다.
             *     거짓이면 초안은 만들어지지 않는다. 사용자가 한 말이 없었거나, 초안을 자동으로 만들지 않는 대화였다.
             */
            diary_expected: boolean;
        };
        /** @description 일기 초안이 준비됐다. `GET /api/v1/diaries/{date}`로 읽는다 */
        WsDiaryReady: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "diary_ready";
            record_date: components["schemas"]["RecordDate"];
        };
        /**
         * @description `invalid_message` JSON이 아니거나, 모르는 `type`이거나, 모양이 틀렸다.
         *     `message_too_large` 메시지가 너무 크다.
         *     `rate_limited` 너무 자주 보냈다. 잠시 뒤에 같은 `client_message_id`로 다시 보낸다.
         *     `not_started` `start`보다 먼저 다른 메시지를 보냈다.
         *     `already_started` `start`를 두 번 보냈다.
         *     `unsupported_mode` 지금은 받지 않는 대화 방식이다.
         *     `conversation_ended` 이미 끝난 대화다. 새로 연결해 `start`를 보낸다.
         *     `internal_error` 서버 쪽 문제다. 글은 저장되지 않았을 수 있다. 같은 `client_message_id`로 다시 보내도 된다.
         * @enum {string}
         */
        WsErrorCode: "invalid_message" | "message_too_large" | "rate_limited" | "not_started" | "already_started" | "unsupported_mode" | "conversation_ended" | "internal_error";
        /** @description 요청을 처리하지 못했다. 사용자가 쓴 글은 담지 않는다 */
        WsError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            code: components["schemas"]["WsErrorCode"];
            /**
             * Format: uuid
             * @description 어느 글을 처리하다 난 오류인지. 글과 상관없는 오류에는 없다
             */
            client_message_id?: string;
        };
        Me: {
            user: components["schemas"]["User"];
            settings: components["schemas"]["SettingsSummary"];
        };
        /**
         * @description 오류의 종류. 값은 바뀌지 않는다. 화면은 이 값으로 안내 문구를 고른다
         * @enum {string}
         */
        ProblemCode: "validation_failed" | "invalid_credentials" | "unauthenticated" | "cross_origin_rejected" | "forbidden" | "not_found" | "method_not_allowed" | "email_taken" | "payload_too_large" | "unsupported_media_type" | "weak_password" | "consent_required" | "rate_limited" | "internal_error" | "service_unavailable";
        /**
         * @description 비밀번호를 받지 않는 이유.
         *     `too_short` 너무 짧다, `too_long` 너무 길다, `too_common` 누구나 먼저 넣어 보는 흔한 비밀번호다,
         *     `matches_email` 이메일 주소나 그 앞부분과 같다, `invalid_encoding` 글자로 읽을 수 없는 바이트가 있다.
         * @enum {string}
         */
        PasswordReason: "too_short" | "too_long" | "too_common" | "matches_email" | "invalid_encoding";
        /**
         * @description 받을 수 없는 값이 든 요청 필드의 이름. 쿼리 매개변수일 때는 그 이름이다
         * @enum {string}
         */
        ProblemField: "email" | "display_name" | "timezone" | "text" | "q";
        /** @description `consent_required`일 때만 있다 */
        ConsentProblem: {
            /** @description 필요한데 오지 않은 동의 */
            missing: components["schemas"]["ConsentKind"][];
            /** @description 왔지만 지금 판이 아닌 동의. 가입 규칙을 다시 받아 새 문서를 보여줘야 한다 */
            outdated: components["schemas"]["ConsentKind"][];
        };
        /** @description RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것 */
        Problem: {
            /**
             * @description 오류 종류를 가리키는 URI 참조. `/problems/{code}` 꼴이다
             * @example /problems/weak_password
             */
            type: string;
            /**
             * @description 개발자가 읽는 짧은 영어 문구. 사용자에게 보여주지 않는다
             * @example Password does not meet the policy
             */
            title: string;
            /**
             * @description HTTP 상태 코드와 같은 값
             * @example 422
             */
            status: number;
            code: components["schemas"]["ProblemCode"];
            /** @description 이 요청의 ID. 응답의 `X-Request-Id` 헤더와 같다. 문의할 때 알려주면 서버 로그에서 찾을 수 있다 */
            request_id: string;
            /** @description `weak_password`일 때만 있다 */
            reasons?: components["schemas"]["PasswordReason"][];
            consents?: components["schemas"]["ConsentProblem"];
            /** @description 422 `validation_failed`일 때만 있다 */
            fields?: components["schemas"]["ProblemField"][];
        };
    };
    responses: {
        /** @description 그 밖의 오류. 본문의 `code`로 구분한다 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 요청이 이 명세와 맞지 않는다 (`validation_failed`) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 로그인하지 않았거나 세션이 끝났다 (`unauthenticated`) */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 다른 출처의 페이지가 보낸 요청이다 (`cross_origin_rejected`) */
        CrossOriginRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 그 날짜에 찾는 기록이 없다 (`not_found`) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 값의 꼴은 맞지만 받을 수 없는 값이다 (`validation_failed`). `fields`에 어느 필드인지 담긴다 */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 너무 자주 시도했다 (`rate_limited`) */
        RateLimited: {
            headers: {
                /** @description 다시 시도하기까지 기다릴 초 */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description 기록 날짜. `YYYY-MM-DD` 꼴이다 */
        RecordDate: components["schemas"]["RecordDate"];
    };
    requestBodies: never;
    headers: {
        /**
         * @description 세션 쿠키. `HttpOnly; SameSite=Lax; Path=/`이고, 운영에서는 `Secure`가 더 붙는다.
         *     `Max-Age`는 세션의 전체 수명이다.
         */
        SessionCookie: string;
        /** @description 세션 쿠키를 지운다(`Max-Age=0`). */
        ClearedSessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthRequirements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 가입 규칙 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRequirements"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 가입했고 로그인됐다 */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["CrossOriginRejected"];
            /** @description 이미 가입된 이메일이다 (`email_taken`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description 받을 수 없는 값이다.
             *     `weak_password`(`reasons`), `consent_required`(`consents`), `validation_failed`(`fields`) 가운데 하나다.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인됐다 */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 이메일이나 비밀번호가 틀렸다 (`invalid_credentials`) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            403: components["responses"]["CrossOriginRejected"];
            429: components["responses"]["RateLimited"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃됐다. 쿠키를 지우는 `Set-Cookie`가 실린다 */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["ClearedSessionCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CrossOriginRejected"];
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그인한 사용자 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            default: components["responses"]["Problem"];
        };
    };
    listDiaries: {
        parameters: {
            query?: {
                /**
                 * @description 보고 싶은 달. `YYYY-MM` 꼴이다
                 * @example 2026-09
                 */
                month?: string;
                /** @description 검색어 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 일기 목록. 맞는 것이 없으면 빈 목록이다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiaryList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["Unprocessable"];
            default: components["responses"]["Problem"];
        };
    };
    getDiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 기록 날짜. `YYYY-MM-DD` 꼴이다 */
                date: components["parameters"]["RecordDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 그날의 일기 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    putDiary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 기록 날짜. `YYYY-MM-DD` 꼴이다 */
                date: components["parameters"]["RecordDate"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiaryUpdate"];
            };
        };
        responses: {
            /** @description 확인한 일기 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CrossOriginRejected"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
            default: components["responses"]["Problem"];
        };
    };
    deleteDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 기록 날짜. `YYYY-MM-DD` 꼴이다 */
                date: components["parameters"]["RecordDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 지웠다 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CrossOriginRejected"];
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 도움 자원 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceList"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
