// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const grantConsent = `-- name: GrantConsent :one
INSERT INTO consents (id, user_id, kind, version, granted_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, kind, version) WHERE withdrawn_at IS NULL DO UPDATE
SET version = EXCLUDED.version
RETURNING id, user_id, kind, version, granted_at, withdrawn_at
`

type GrantConsentParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Kind    string
	Version string
	Now     time.Time
}

// 동의 이력은 쌓기만 한다. 철회했던 동의에 다시 동의하면 앞선 행을 되살리지 않고 새 행을 더한다.
// 그래야 언제 동의했고 언제 철회했는지가 그대로 남는다.
// 같은 판에 유효한 동의가 이미 있으면 그 행을 그대로 돌려준다. 처음 동의한 시각이 바뀌지 않고 행도 늘지 않아,
// 같은 요청이 되풀이되어도 결과가 같다.
// DO NOTHING은 이미 있는 행을 돌려주지 않는다. 값을 바꾸지 않는 갱신을 걸어 두어야 어느 경우에도 행이 나온다.
func (q *Queries) GrantConsent(ctx context.Context, arg GrantConsentParams) (Consent, error) {
	row := q.db.QueryRow(ctx, grantConsent,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Version,
		arg.Now,
	)
	var i Consent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Version,
		&i.GrantedAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const listActiveConsents = `-- name: ListActiveConsents :many
SELECT id, user_id, kind, version, granted_at, withdrawn_at FROM consents
WHERE user_id = $1
  AND withdrawn_at IS NULL
ORDER BY kind, version
`

func (q *Queries) ListActiveConsents(ctx context.Context, userID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.Query(ctx, listActiveConsents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Consent{}
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Version,
			&i.GrantedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentHistory = `-- name: ListConsentHistory :many
SELECT id, user_id, kind, version, granted_at, withdrawn_at FROM consents
WHERE user_id = $1
ORDER BY granted_at, id
`

// 철회한 것까지 모두, 동의한 순서대로 돌려준다.
func (q *Queries) ListConsentHistory(ctx context.Context, userID uuid.UUID) ([]Consent, error) {
	rows, err := q.db.Query(ctx, listConsentHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Consent{}
	for rows.Next() {
		var i Consent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Version,
			&i.GrantedAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawConsent = `-- name: WithdrawConsent :execrows
UPDATE consents
SET withdrawn_at = $1::timestamptz
WHERE user_id = $2
  AND kind = $3
  AND withdrawn_at IS NULL
`

type WithdrawConsentParams struct {
	Now    time.Time
	UserID uuid.UUID
	Kind   string
}

// 판을 가리지 않고 그 종류의 유효한 동의를 모두 철회한다. 이미 철회한 행의 철회 시각은 건드리지 않는다.
func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, withdrawConsent, arg.Now, arg.UserID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
