// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceConversationCheckState = `-- name: AdvanceConversationCheckState :one
UPDATE conversations
SET check_state = $1::text
WHERE id = $2
  AND user_id = $3
  AND status = 'active'
  AND array_position(ARRAY['none', 'reflected', 'asked'], check_state)
      <= array_position(ARRAY['none', 'reflected', 'asked'], $1::text)
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type AdvanceConversationCheckStateParams struct {
	CheckState string
	ID         uuid.UUID
	UserID     uuid.UUID
}

// 확인 상태는 앞으로만 간다(none, reflected, asked 순). 같은 값을 다시 적는 것은 받아 준다.
// 뒤로 돌리려는 요청과 끝난 대화에 대한 요청은 찾지 못함이 된다. 직접 묻기는 한 대화에서 한 번뿐이어야 하므로,
// 같은 대화를 두 연결이 함께 다루더라도 "직접 물었다"가 "되물었다"로 덮이지 않게 한다.
// 'asked'로 옮기는 일은 ClaimDirectAsk만 한다. 여기서는 그 자리를 넘겨받지 않는다.
func (q *Queries) AdvanceConversationCheckState(ctx context.Context, arg AdvanceConversationCheckStateParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, advanceConversationCheckState, arg.CheckState, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const advanceConversationCrisisStage = `-- name: AdvanceConversationCrisisStage :one
UPDATE conversations
SET crisis_spoken_stage = $1
WHERE id = $2
  AND user_id = $3
  AND status = 'active'
  AND crisis_spoken_stage <= $1
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type AdvanceConversationCrisisStageParams struct {
	CrisisSpokenStage int16
	ID                uuid.UUID
	UserID            uuid.UUID
}

// 위기 대응의 고정 문구가 실제로 나간 단계를 적는다. 뒤로 돌리지 않고, 같은 값을 다시 적는 것은 받아 준다.
// 말이 나간 트랜잭션 안에서만 부른다. 말이 나가기 전에 적으면, 판정만 남기고 끊긴 턴을 다시 보냈을 때
// 고정 문구를 이미 말한 것으로 보고 건너뛴다.
func (q *Queries) AdvanceConversationCrisisStage(ctx context.Context, arg AdvanceConversationCrisisStageParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, advanceConversationCrisisStage, arg.CrisisSpokenStage, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const claimConversationAnalysis = `-- name: ClaimConversationAnalysis :one
UPDATE conversations
SET analysis_status = 'running'
WHERE id = $1
  AND user_id = $2
  AND status <> 'active'
  AND analysis_status IN ('none', 'pending', 'failed')
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type ClaimConversationAnalysisParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 끝난 대화의 신호 추출을 작업자 하나가 맡는다. 맡은 쪽만 행을 돌려받는다.
//
// 열려 있는 대화는 맡지 않는다. 아직 이어질 말이 남았는데 뽑으면 일부만 본 결과가 하루의 판단으로 굳는다.
// 이미 끝난 분석(done)은 다시 맡지 않는다. 같은 대화의 신호 행은 유일 제약에 걸려 두 번 들어갈 수 없으므로,
// 다시 맡아도 하는 일은 실패하는 것뿐이다.
// 실패한 분석(failed)은 다시 맡는다. 모델의 실패는 대개 그 답 하나의 문제라 다시 해 볼 만하다.
func (q *Queries) ClaimConversationAnalysis(ctx context.Context, arg ClaimConversationAnalysisParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, claimConversationAnalysis, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const claimDirectAsk = `-- name: ClaimDirectAsk :one
UPDATE conversations
SET check_state = 'asked'
WHERE id = $1
  AND user_id = $2
  AND status = 'active'
  AND check_state = 'reflected'
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type ClaimDirectAskParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 직접 묻기의 자리를 한 번만 내준다. 되물은 뒤('reflected')에서만 '물었다'로 옮겨지고, 옮긴 쪽만 행을 돌려받는다.
//
// 단순히 앞으로만 가는 규칙으로는 모자란다. 두 연결이 같은 대화를 함께 다루면 둘 다 'reflected'를 읽고
// 둘 다 직접 묻기로 가서, 사람이 같은 질문을 연달아 두 번 받는다. 여기서 진 쪽은 코어의 규칙대로
// "이미 물었다"로 보고 대응 단계로 올라간다.
func (q *Queries) ClaimDirectAsk(ctx context.Context, arg ClaimDirectAskParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, claimDirectAsk, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, user_id, day_id, status, started_mode, started_at, created_at)
VALUES (
    $1,
    $2,
    $3,
    'active',
    $4,
    $5,
    $5
)
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type CreateConversationParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DayID       uuid.UUID
	StartedMode string
	Now         time.Time
}

// 열린 대화는 사용자마다 하나뿐이다. 이미 있으면 유일 제약(conversations_user_id_active_key)에 걸린다.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.DayID,
		arg.StartedMode,
		arg.Now,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const endConversation = `-- name: EndConversation :one
UPDATE conversations AS c
SET status            = 'ended',
    ended_at          = $1::timestamptz,
    end_reason        = $2::text,
    processing_status = $3
WHERE c.id = $4
  AND c.user_id = $5
  AND c.status = 'active'
  AND (
      $6::timestamptz IS NULL
      OR NOT EXISTS (
          SELECT 1 FROM utterances AS u
          WHERE u.conversation_id = c.id
            AND u.created_at > $6::timestamptz
      )
  )
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type EndConversationParams struct {
	Now              time.Time
	EndReason        string
	ProcessingStatus string
	ID               uuid.UUID
	UserID           uuid.UUID
	QuietSince       *time.Time
}

// 열려 있는 대화만 끝낸다. 끝내기 버튼과 무응답 타이머가 겹쳐도 한쪽만 행을 돌려받고, 다른 쪽은 찾지 못함이 된다.
// 일기 초안 작업은 행을 돌려받은 쪽만 같은 트랜잭션에서 등록한다. 그래야 작업이 두 번 등록되지 않는다.
//
// quiet_since를 주면 그 시각 뒤로 발화가 하나도 없을 때만 끝낸다. 연결이 끊긴 대화를 한참 뒤에 닫을 때 쓴다.
// 타이머는 연결이 끊긴 프로세스에 있는데, 사용자는 그 사이에 다른 프로세스로 다시 붙어 이야기를 이어갔을 수 있다.
func (q *Queries) EndConversation(ctx context.Context, arg EndConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, endConversation,
		arg.Now,
		arg.EndReason,
		arg.ProcessingStatus,
		arg.ID,
		arg.UserID,
		arg.QuietSince,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const getActiveConversation = `-- name: GetActiveConversation :one
SELECT c.id, c.user_id, c.day_id, c.status, c.started_mode, c.started_at, c.ended_at, c.end_reason, c.processing_status, c.created_at, c.check_state, c.crisis_spoken_stage, c.analysis_status, d.record_date
FROM conversations AS c
JOIN days AS d ON d.id = c.day_id
WHERE c.user_id = $1
  AND c.status = 'active'
`

type GetActiveConversationRow struct {
	Conversation Conversation
	RecordDate   pgtype.Date
}

// 기록 날짜를 함께 돌려준다. 새벽의 경계를 넘긴 채 열려 있는 대화는 이어가지 않고 먼저 끝내야 하는데,
// 그 판단은 대화가 매달린 하루의 기록 날짜와 지금의 기록 날짜를 견줘서 한다.
func (q *Queries) GetActiveConversation(ctx context.Context, userID uuid.UUID) (GetActiveConversationRow, error) {
	row := q.db.QueryRow(ctx, getActiveConversation, userID)
	var i GetActiveConversationRow
	err := row.Scan(
		&i.Conversation.ID,
		&i.Conversation.UserID,
		&i.Conversation.DayID,
		&i.Conversation.Status,
		&i.Conversation.StartedMode,
		&i.Conversation.StartedAt,
		&i.Conversation.EndedAt,
		&i.Conversation.EndReason,
		&i.Conversation.ProcessingStatus,
		&i.Conversation.CreatedAt,
		&i.Conversation.CheckState,
		&i.Conversation.CrisisSpokenStage,
		&i.Conversation.AnalysisStatus,
		&i.RecordDate,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT c.id, c.user_id, c.day_id, c.status, c.started_mode, c.started_at, c.ended_at, c.end_reason, c.processing_status, c.created_at, c.check_state, c.crisis_spoken_stage, c.analysis_status, d.record_date
FROM conversations AS c
JOIN days AS d ON d.id = c.day_id
WHERE c.id = $1
  AND c.user_id = $2
`

type GetConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetConversationRow struct {
	Conversation Conversation
	RecordDate   pgtype.Date
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i GetConversationRow
	err := row.Scan(
		&i.Conversation.ID,
		&i.Conversation.UserID,
		&i.Conversation.DayID,
		&i.Conversation.Status,
		&i.Conversation.StartedMode,
		&i.Conversation.StartedAt,
		&i.Conversation.EndedAt,
		&i.Conversation.EndReason,
		&i.Conversation.ProcessingStatus,
		&i.Conversation.CreatedAt,
		&i.Conversation.CheckState,
		&i.Conversation.CrisisSpokenStage,
		&i.Conversation.AnalysisStatus,
		&i.RecordDate,
	)
	return i, err
}

const hasAnalysedConversationOnDate = `-- name: HasAnalysedConversationOnDate :one
SELECT EXISTS (
    SELECT 1
    FROM conversations AS c
    JOIN days AS d ON d.id = c.day_id
    WHERE c.user_id = $1
      AND d.user_id = $1
      AND d.record_date = $2
      AND c.analysis_status = 'done'
)::boolean AS analysed
`

type HasAnalysedConversationOnDateParams struct {
	UserID     uuid.UUID
	RecordDate pgtype.Date
}

// 그날 신호 추출이 끝난 대화가 있는지다. 근거 화면이 "대화하지 않은 날"과 "아직 분석이 끝나지 않은 날"을 가리는 데 쓴다.
// 신호 행이 있는지로 물어도 같은 답이 나온다. 여덟 항목과 done은 한 트랜잭션에서 함께 적히기 때문이다.
func (q *Queries) HasAnalysedConversationOnDate(ctx context.Context, arg HasAnalysedConversationOnDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnalysedConversationOnDate, arg.UserID, arg.RecordDate)
	var analysed bool
	err := row.Scan(&analysed)
	return analysed, err
}

const listConversationsByDay = `-- name: ListConversationsByDay :many
SELECT c.id, c.user_id, c.day_id, c.status, c.started_mode, c.started_at, c.ended_at, c.end_reason, c.processing_status, c.created_at, c.check_state, c.crisis_spoken_stage, c.analysis_status,
       EXISTS (
           SELECT 1 FROM gate_events AS g
           WHERE g.conversation_id = c.id
             AND g.final_stage >= 2
       )::boolean AS crisis
FROM conversations AS c
WHERE c.day_id = $1
  AND c.user_id = $2
ORDER BY c.started_at, c.id
`

type ListConversationsByDayParams struct {
	DayID  uuid.UUID
	UserID uuid.UUID
}

type ListConversationsByDayRow struct {
	Conversation Conversation
	Crisis       bool
}

// 그날의 대화를 시작한 순서대로 돌려준다. crisis는 그 대화에 대응 단계 이상의 관문 기록이 있는지다.
// 그런 대화에서는 일기 초안을 자동으로 만들지 않고, 끝날 때까지 도움 자원을 화면에 고정해 둔다.
func (q *Queries) ListConversationsByDay(ctx context.Context, arg ListConversationsByDayParams) ([]ListConversationsByDayRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByDay, arg.DayID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsByDayRow{}
	for rows.Next() {
		var i ListConversationsByDayRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.UserID,
			&i.Conversation.DayID,
			&i.Conversation.Status,
			&i.Conversation.StartedMode,
			&i.Conversation.StartedAt,
			&i.Conversation.EndedAt,
			&i.Conversation.EndReason,
			&i.Conversation.ProcessingStatus,
			&i.Conversation.CreatedAt,
			&i.Conversation.CheckState,
			&i.Conversation.CrisisSpokenStage,
			&i.Conversation.AnalysisStatus,
			&i.Crisis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleActiveConversations = `-- name: ListStaleActiveConversations :many
SELECT c.id, c.user_id, c.day_id, c.started_at
FROM conversations AS c
WHERE c.status = 'active'
  AND c.started_at < $1
  AND NOT EXISTS (
      SELECT 1 FROM utterances AS u
      WHERE u.conversation_id = c.id
        AND u.created_at >= $1
  )
ORDER BY c.started_at, c.id
LIMIT $2
`

type ListStaleActiveConversationsParams struct {
	IdleBefore time.Time
	MaxRows    int32
}

type ListStaleActiveConversationsRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DayID     uuid.UUID
	StartedAt time.Time
}

// 시작한 지도, 마지막 발화가 있은 지도 idle_before보다 오래된 열린 대화다. 모든 사용자를 통틀어 찾는다.
// 끊긴 연결을 기다리는 타이머는 프로세스의 메모리에 있어서 프로세스가 다시 뜨면 사라진다.
// 주기 작업이 이 목록을 보고 EndConversation(quiet_since)으로 닫는다. 그 사이에 이어진 대화는 그 조건에서 걸러진다.
// 열린 대화만 담는 부분 인덱스(conversations_user_id_active_key)를 읽으므로 끝난 대화가 쌓여도 느려지지 않는다.
func (q *Queries) ListStaleActiveConversations(ctx context.Context, arg ListStaleActiveConversationsParams) ([]ListStaleActiveConversationsRow, error) {
	rows, err := q.db.Query(ctx, listStaleActiveConversations, arg.IdleBefore, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleActiveConversationsRow{}
	for rows.Next() {
		var i ListStaleActiveConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DayID,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConversationForAppend = `-- name: LockConversationForAppend :one
SELECT id, status FROM conversations
WHERE id = $1
  AND user_id = $2
FOR NO KEY UPDATE
`

type LockConversationForAppendParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type LockConversationForAppendRow struct {
	ID     uuid.UUID
	Status string
}

// 발화를 더하기 전에 대화를 잡아 둔다. 같은 대화에 발화를 더하는 트랜잭션들이 여기서 한 줄로 선다.
// 다음 순번은 이 잠금을 얻은 뒤의 새 문장에서 읽어야 한다. 한 문장 안에서 잠그고 읽으면,
// 기다리기 전에 뜬 스냅샷으로 읽기 때문에 앞선 트랜잭션이 방금 넣은 발화를 보지 못하고 같은 순번을 고른다.
// 키를 바꾸지 않는 잠금이라 이 대화에 관문 기록이나 신호가 매달리는 것은 막지 않는다.
func (q *Queries) LockConversationForAppend(ctx context.Context, arg LockConversationForAppendParams) (LockConversationForAppendRow, error) {
	row := q.db.QueryRow(ctx, lockConversationForAppend, arg.ID, arg.UserID)
	var i LockConversationForAppendRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const setConversationAnalysisStatus = `-- name: SetConversationAnalysisStatus :one
UPDATE conversations
SET analysis_status = $1
WHERE id = $2
  AND user_id = $3
  AND status <> 'active'
  AND (analysis_status <> 'done' OR $1::text = 'done')
RETURNING id, user_id, day_id, status, started_mode, started_at, ended_at, end_reason, processing_status, created_at, check_state, crisis_spoken_stage, analysis_status
`

type SetConversationAnalysisStatusParams struct {
	AnalysisStatus string
	ID             uuid.UUID
	UserID         uuid.UUID
}

// 신호 추출의 진행 상태를 적는다. 끝난 대화에만 적는다.
//
// 이미 done인 대화의 상태는 바꾸지 않는다. done은 여덟 항목의 신호 행과 같은 트랜잭션에서만 적히는 값이라
// (store.SaveConversationSignals), 뒤늦게 돌아온 작업자가 그 사실을 running이나 failed로 덮으면
// "분석이 끝난 대화"라는 표시와 실제로 들어 있는 행이 어긋난다.
// done을 다시 적는 것은 받아 준다. 같은 작업을 두 번 돌려도 결과가 같아야 한다.
func (q *Queries) SetConversationAnalysisStatus(ctx context.Context, arg SetConversationAnalysisStatusParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, setConversationAnalysisStatus, arg.AnalysisStatus, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.Status,
		&i.StartedMode,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.ProcessingStatus,
		&i.CreatedAt,
		&i.CheckState,
		&i.CrisisSpokenStage,
		&i.AnalysisStatus,
	)
	return i, err
}

const setConversationProcessingStatus = `-- name: SetConversationProcessingStatus :execrows
UPDATE conversations
SET processing_status = $1
WHERE id = $2
  AND user_id = $3
`

type SetConversationProcessingStatusParams struct {
	ProcessingStatus string
	ID               uuid.UUID
	UserID           uuid.UUID
}

// 대화가 끝난 뒤에 도는 작업이 제 진행 상태를 적는다.
func (q *Queries) SetConversationProcessingStatus(ctx context.Context, arg SetConversationProcessingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setConversationProcessingStatus, arg.ProcessingStatus, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
