// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: days.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDay = `-- name: DeleteDay :one
DELETE FROM days
WHERE id = $1
  AND user_id = $2
RETURNING id
`

type DeleteDayParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 그날의 대화, 발화, 위기 관문 기록, 일기, 신호, 그날에서 나온 기억, 기분 고르기가 외래 키를 따라 함께 지워진다.
// user_id를 함께 받는다. 남의 하루는 ID를 알아도 지울 수 없고, 그때는 없는 것과 똑같이 찾지 못함이 된다.
func (q *Queries) DeleteDay(ctx context.Context, arg DeleteDayParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDay, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDayByDate = `-- name: DeleteDayByDate :one
DELETE FROM days
WHERE user_id = $1
  AND record_date = $2
RETURNING id
`

type DeleteDayByDateParams struct {
	UserID     uuid.UUID
	RecordDate pgtype.Date
}

// DeleteDay와 같되 기록 날짜로 찾는다. 그날의 기록이 없으면 찾지 못함이 된다.
func (q *Queries) DeleteDayByDate(ctx context.Context, arg DeleteDayByDateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDayByDate, arg.UserID, arg.RecordDate)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDayByDate = `-- name: GetDayByDate :one
SELECT id, user_id, record_date, created_at FROM days
WHERE user_id = $1
  AND record_date = $2
`

type GetDayByDateParams struct {
	UserID     uuid.UUID
	RecordDate pgtype.Date
}

func (q *Queries) GetDayByDate(ctx context.Context, arg GetDayByDateParams) (Day, error) {
	row := q.db.QueryRow(ctx, getDayByDate, arg.UserID, arg.RecordDate)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordDate,
		&i.CreatedAt,
	)
	return i, err
}

const lockDay = `-- name: LockDay :one
SELECT id FROM days
WHERE id = $1
  AND user_id = $2
FOR NO KEY UPDATE
`

type LockDayParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 그날의 일기를 쓰는 동안 하루를 잡아 둔다. 같은 날의 초안 작업 둘이 겹치거나 초안 작업과 사용자의 저장이 겹쳐도 차례로 돈다.
// 하루를 지우는 요청과도 차례가 갈린다. 지워진 뒤라면 찾지 못함이 되고, 일기를 쓰던 쪽은 거기서 그만둔다.
// 키를 바꾸지 않는 잠금이라 그날에 새 대화가 매달리는 것은 막지 않는다.
func (q *Queries) LockDay(ctx context.Context, arg LockDayParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockDay, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertDay = `-- name: UpsertDay :one
INSERT INTO days (id, user_id, record_date, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, record_date) DO UPDATE
SET record_date = EXCLUDED.record_date
RETURNING id
`

type UpsertDayParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	RecordDate pgtype.Date
	Now        time.Time
}

// 그날의 첫 대화가 행을 만들고, 뒤의 대화는 같은 행을 받는다.
// DO NOTHING은 이미 있는 행을 돌려주지 않는다. 값을 바꾸지 않는 갱신을 걸어 두어야 어느 경우에도 id가 나오고,
// 두 요청이 동시에 들어와도 한 행으로 모인다.
func (q *Queries) UpsertDay(ctx context.Context, arg UpsertDayParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDay,
		arg.ID,
		arg.UserID,
		arg.RecordDate,
		arg.Now,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
