// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diaries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmDiary = `-- name: ConfirmDiary :one
UPDATE diaries
SET body_enc     = $1::bytea,
    draft_enc    = NULL,
    status       = 'confirmed',
    confirmed_at = $2::timestamptz,
    updated_at   = $2::timestamptz
WHERE id = $3
  AND user_id = $4
RETURNING id, day_id, user_id, status, draft_enc, body_enc, confirmed_at, created_at, updated_at
`

type ConfirmDiaryParams struct {
	BodyEnc []byte
	Now     time.Time
	ID      uuid.UUID
	UserID  uuid.UUID
}

// 글을 고치고 확인한다. 바뀌는 것은 일기 글뿐이고 신호는 그대로다.
// 확인한 글이 초안을 대신하므로 초안은 비운다. 쓰이지 않는 사용자의 글을 남겨 두지 않는다.
func (q *Queries) ConfirmDiary(ctx context.Context, arg ConfirmDiaryParams) (Diary, error) {
	row := q.db.QueryRow(ctx, confirmDiary,
		arg.BodyEnc,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.UserID,
		&i.Status,
		&i.DraftEnc,
		&i.BodyEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConfirmedDiary = `-- name: CreateConfirmedDiary :one
INSERT INTO diaries (id, day_id, user_id, status, body_enc, confirmed_at, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    'confirmed',
    $4::bytea,
    $5::timestamptz,
    $5::timestamptz,
    $5::timestamptz
)
RETURNING id, day_id, user_id, status, draft_enc, body_enc, confirmed_at, created_at, updated_at
`

type CreateConfirmedDiaryParams struct {
	ID      uuid.UUID
	DayID   uuid.UUID
	UserID  uuid.UUID
	BodyEnc []byte
	Now     time.Time
}

// 초안 없이 사용자가 직접 쓴 일기다. 초안을 자동으로 만들지 않은 날에도 일기는 쓸 수 있다.
func (q *Queries) CreateConfirmedDiary(ctx context.Context, arg CreateConfirmedDiaryParams) (Diary, error) {
	row := q.db.QueryRow(ctx, createConfirmedDiary,
		arg.ID,
		arg.DayID,
		arg.UserID,
		arg.BodyEnc,
		arg.Now,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.UserID,
		&i.Status,
		&i.DraftEnc,
		&i.BodyEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDiaryDraft = `-- name: CreateDiaryDraft :one
INSERT INTO diaries (id, day_id, user_id, status, draft_enc, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    'draft',
    $4::bytea,
    $5,
    $5
)
RETURNING id, day_id, user_id, status, draft_enc, body_enc, confirmed_at, created_at, updated_at
`

type CreateDiaryDraftParams struct {
	ID       uuid.UUID
	DayID    uuid.UUID
	UserID   uuid.UUID
	DraftEnc []byte
	Now      time.Time
}

// 그날의 첫 초안이다. 일기는 하루에 하나라서, 이미 있으면 유일 제약(diaries_day_id_key)에 걸린다.
// 직접 부르지 않고 store.SaveDiaryDraft를 쓴다. 암호문에 행 ID가 묶이므로 있는 행인지 새 행인지를 먼저 알아야 잠글 수 있다.
func (q *Queries) CreateDiaryDraft(ctx context.Context, arg CreateDiaryDraftParams) (Diary, error) {
	row := q.db.QueryRow(ctx, createDiaryDraft,
		arg.ID,
		arg.DayID,
		arg.UserID,
		arg.DraftEnc,
		arg.Now,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.UserID,
		&i.Status,
		&i.DraftEnc,
		&i.BodyEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiaryByDate = `-- name: GetDiaryByDate :one
SELECT dr.id, dr.day_id, dr.user_id, dr.status, dr.draft_enc, dr.body_enc, dr.confirmed_at, dr.created_at, dr.updated_at
FROM diaries AS dr
JOIN days AS d ON d.id = dr.day_id
WHERE d.user_id = $1
  AND d.record_date = $2
`

type GetDiaryByDateParams struct {
	UserID     uuid.UUID
	RecordDate pgtype.Date
}

func (q *Queries) GetDiaryByDate(ctx context.Context, arg GetDiaryByDateParams) (Diary, error) {
	row := q.db.QueryRow(ctx, getDiaryByDate, arg.UserID, arg.RecordDate)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.UserID,
		&i.Status,
		&i.DraftEnc,
		&i.BodyEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiaryByDayID = `-- name: GetDiaryByDayID :one
SELECT id, day_id, user_id, status, draft_enc, body_enc, confirmed_at, created_at, updated_at FROM diaries
WHERE day_id = $1
  AND user_id = $2
`

type GetDiaryByDayIDParams struct {
	DayID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDiaryByDayID(ctx context.Context, arg GetDiaryByDayIDParams) (Diary, error) {
	row := q.db.QueryRow(ctx, getDiaryByDayID, arg.DayID, arg.UserID)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.UserID,
		&i.Status,
		&i.DraftEnc,
		&i.BodyEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiariesByDateRange = `-- name: ListDiariesByDateRange :many
SELECT dr.id, dr.day_id, dr.user_id, dr.status, dr.draft_enc, dr.body_enc, dr.confirmed_at, dr.created_at, dr.updated_at, d.record_date
FROM diaries AS dr
JOIN days AS d ON d.id = dr.day_id
WHERE d.user_id = $1
  AND d.record_date >= $2
  AND d.record_date < $3
ORDER BY d.record_date
`

type ListDiariesByDateRangeParams struct {
	UserID   uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ListDiariesByDateRangeRow struct {
	Diary      Diary
	RecordDate pgtype.Date
}

// from_date부터 to_date 앞까지의 일기를 날짜순으로 돌려준다. 한 달을 볼 때는 그 달 1일과 다음 달 1일을 준다.
func (q *Queries) ListDiariesByDateRange(ctx context.Context, arg ListDiariesByDateRangeParams) ([]ListDiariesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listDiariesByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiariesByDateRangeRow{}
	for rows.Next() {
		var i ListDiariesByDateRangeRow
		if err := rows.Scan(
			&i.Diary.ID,
			&i.Diary.DayID,
			&i.Diary.UserID,
			&i.Diary.Status,
			&i.Diary.DraftEnc,
			&i.Diary.BodyEnc,
			&i.Diary.ConfirmedAt,
			&i.Diary.CreatedAt,
			&i.Diary.UpdatedAt,
			&i.RecordDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiariesByUser = `-- name: ListDiariesByUser :many
SELECT dr.id, dr.day_id, dr.user_id, dr.status, dr.draft_enc, dr.body_enc, dr.confirmed_at, dr.created_at, dr.updated_at, d.record_date
FROM diaries AS dr
JOIN days AS d ON d.id = dr.day_id
WHERE d.user_id = $1
ORDER BY d.record_date DESC
`

type ListDiariesByUserRow struct {
	Diary      Diary
	RecordDate pgtype.Date
}

// 그 사용자의 일기 전부를 최근 날짜부터 돌려준다. 일기 글은 암호문이라 DB에서 찾을 수 없다.
// 검색은 본인의 일기를 모두 읽어 풀어서 메모리에서 한다.
func (q *Queries) ListDiariesByUser(ctx context.Context, userID uuid.UUID) ([]ListDiariesByUserRow, error) {
	rows, err := q.db.Query(ctx, listDiariesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiariesByUserRow{}
	for rows.Next() {
		var i ListDiariesByUserRow
		if err := rows.Scan(
			&i.Diary.ID,
			&i.Diary.DayID,
			&i.Diary.UserID,
			&i.Diary.Status,
			&i.Diary.DraftEnc,
			&i.Diary.BodyEnc,
			&i.Diary.ConfirmedAt,
			&i.Diary.CreatedAt,
			&i.Diary.UpdatedAt,
			&i.RecordDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceDiaryDraft = `-- name: ReplaceDiaryDraft :one
UPDATE diaries
SET draft_enc  = $1::bytea,
    status     = 'draft',
    updated_at = $2
WHERE id = $3
  AND user_id = $4
RETURNING id, day_id, user_id, status, draft_enc, body_enc, confirmed_at, created_at, updated_at
`

type ReplaceDiaryDraftParams struct {
	DraftEnc []byte
	Now      time.Time
	ID       uuid.UUID
	UserID   uuid.UUID
}

// 그날 다시 대화해서 새 초안이 생겼다. 상태가 draft로 돌아가 사용자가 다시 확인한다.
// 사용자가 확인한 글(body_enc)과 확인한 시각은 건드리지 않는다.
func (q *Queries) ReplaceDiaryDraft(ctx context.Context, arg ReplaceDiaryDraftParams) (Diary, error) {
	row := q.db.QueryRow(ctx, replaceDiaryDraft,
		arg.DraftEnc,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.UserID,
		&i.Status,
		&i.DraftEnc,
		&i.BodyEnc,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
