// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Consent struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Kind        string
	Version     string
	GrantedAt   time.Time
	WithdrawnAt *time.Time
}

type Conversation struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	DayID             uuid.UUID
	Status            string
	StartedMode       string
	StartedAt         time.Time
	EndedAt           *time.Time
	EndReason         *string
	ProcessingStatus  string
	CreatedAt         time.Time
	CheckState        string
	CrisisSpokenStage int16
	AnalysisStatus    string
}

type Day struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	RecordDate pgtype.Date
	CreatedAt  time.Time
}

type Diary struct {
	ID          uuid.UUID
	DayID       uuid.UUID
	UserID      uuid.UUID
	Status      string
	DraftEnc    []byte
	BodyEnc     []byte
	ConfirmedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GateEvent struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ConversationID uuid.UUID
	UtteranceID    uuid.UUID
	RuleStage      *int16
	AIStage        *int16
	FinalStage     int16
	DetectedBy     string
	Adjustments    []string
	AIFailed       bool
	AILatencyMs    *int32
	EvidenceEnc    []byte
	CreatedAt      time.Time
}

type Memory struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	SourceDayID uuid.UUID
	Kind        string
	ContentEnc  []byte
	Sensitive   bool
	DueDate     pgtype.Date
	LastUsedAt  *time.Time
	CreatedAt   time.Time
}

type MoodPick struct {
	DayID     uuid.UUID
	UserID    uuid.UUID
	ValueEnc  []byte
	CreatedAt time.Time
}

type SelfCheck struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	RecordDate pgtype.Date
	ResultEnc  []byte
	CreatedAt  time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	UserAgent  *string
	IP         *netip.Addr
}

type Signal struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	DayID               uuid.UUID
	ConversationID      uuid.UUID
	Item                string
	Status              string
	Explicitness        string
	EvidenceEnc         []byte
	EvidenceUtteranceID *uuid.UUID
	CancelledAt         *time.Time
	ExtractorVersion    string
	CreatedAt           time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	PasswordHash    *string
	DisplayName     *string
	Timezone        string
	Role            string
	IsDemo          bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserIdentity struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Provider  string
	Subject   string
	Email     *string
	CreatedAt time.Time
}

type UserKey struct {
	UserID     uuid.UUID
	WrappedDEK []byte
	KEKVersion int16
	CreatedAt  time.Time
}

type UserSetting struct {
	UserID          uuid.UUID
	ReminderEnabled bool
	ReminderTime    pgtype.Time
	DefaultMode     string
	AnalysisEnabled bool
	MemoryEnabled   bool
	MoodPickEnabled bool
	UpdatedAt       time.Time
}

type Utterance struct {
	ID               uuid.UUID
	ConversationID   uuid.UUID
	UserID           uuid.UUID
	Seq              int32
	Speaker          string
	Modality         string
	Origin           string
	TextEnc          []byte
	STTMinConfidence *float32
	CreatedAt        time.Time
	ClientMessageID  *uuid.UUID
}
