// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token_hash, created_at, last_seen_at, expires_at, user_agent, ip)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, token_hash, created_at, last_seen_at, expires_at, user_agent, ip
`

type CreateSessionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	Now       time.Time
	ExpiresAt time.Time
	UserAgent *string
	IP        *netip.Addr
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Now,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IP,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.IP,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions WHERE token_hash = $1
`

// 로그아웃할 때와, 새로 로그인하면서 그 브라우저가 들고 있던 세션을 끊을 때 쓴다.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionWithUserByTokenHash = `-- name: GetSessionWithUserByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.created_at, s.last_seen_at, s.expires_at, s.user_agent, s.ip,
       u.email,
       u.email_verified_at,
       u.display_name,
       u.timezone,
       u.role,
       u.is_demo,
       (u.password_hash IS NOT NULL)::boolean AS has_password,
       u.created_at AS user_created_at
FROM sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > $2
`

type GetSessionWithUserByTokenHashParams struct {
	TokenHash []byte
	Now       time.Time
}

type GetSessionWithUserByTokenHashRow struct {
	Session         Session
	Email           string
	EmailVerifiedAt *time.Time
	DisplayName     *string
	Timezone        string
	Role            string
	IsDemo          bool
	HasPassword     bool
	UserCreatedAt   time.Time
}

// 만료된 세션은 없는 것으로 친다. 만료 확인을 부르는 쪽에 맡기면 한 곳만 빠뜨려도 끝난 세션으로 들어올 수 있다.
//
// 사용자는 행 전체가 아니라 필요한 컬럼만 읽는다. 이 쿼리는 로그인한 요청마다 돌기 때문에,
// 행을 통째로 읽으면 비밀번호 해시가 요청마다 DB에서 건너와 메모리에 올라온다. 쓰이지 않는 값이고,
// 누군가 이 결과를 로그에 찍거나 응답으로 내보내는 코드를 더하는 날 그대로 새어 나간다.
// 비밀번호가 있는 계정인지만 알면 되므로 그것만 참거짓으로 받는다. 해시가 필요한 곳은 로그인(GetUserByEmail)뿐이다.
func (q *Queries) GetSessionWithUserByTokenHash(ctx context.Context, arg GetSessionWithUserByTokenHashParams) (GetSessionWithUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUserByTokenHash, arg.TokenHash, arg.Now)
	var i GetSessionWithUserByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.ExpiresAt,
		&i.Session.UserAgent,
		&i.Session.IP,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.DisplayName,
		&i.Timezone,
		&i.Role,
		&i.IsDemo,
		&i.HasPassword,
		&i.UserCreatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen_at = GREATEST(last_seen_at, $1::timestamptz),
    expires_at   = GREATEST(expires_at, $2::timestamptz)
WHERE id = $3
  AND expires_at > $1::timestamptz
`

type TouchSessionParams struct {
	Now       time.Time
	ExpiresAt time.Time
	ID        uuid.UUID
}

// 쓰는 동안 만료를 뒤로 민다. 만료는 늘어나기만 하고, 이미 끝난 세션은 되살리지 않는다.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.Now, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
