// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (user_id, updated_at)
VALUES ($1, $2)
RETURNING user_id, reminder_enabled, reminder_time, default_mode, analysis_enabled, memory_enabled, mood_pick_enabled, updated_at
`

type CreateUserSettingsParams struct {
	UserID uuid.UUID
	Now    time.Time
}

// 값은 모두 테이블의 기본값으로 시작한다.
func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, createUserSettings, arg.UserID, arg.Now)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.ReminderEnabled,
		&i.ReminderTime,
		&i.DefaultMode,
		&i.AnalysisEnabled,
		&i.MemoryEnabled,
		&i.MoodPickEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, reminder_enabled, reminder_time, default_mode, analysis_enabled, memory_enabled, mood_pick_enabled, updated_at FROM user_settings WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.ReminderEnabled,
		&i.ReminderTime,
		&i.DefaultMode,
		&i.AnalysisEnabled,
		&i.MemoryEnabled,
		&i.MoodPickEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET reminder_enabled  = COALESCE($1, reminder_enabled),
    reminder_time     = COALESCE($2, reminder_time),
    default_mode      = COALESCE($3, default_mode),
    analysis_enabled  = COALESCE($4, analysis_enabled),
    memory_enabled    = COALESCE($5, memory_enabled),
    mood_pick_enabled = COALESCE($6, mood_pick_enabled),
    updated_at        = $7
WHERE user_id = $8
RETURNING user_id, reminder_enabled, reminder_time, default_mode, analysis_enabled, memory_enabled, mood_pick_enabled, updated_at
`

type UpdateUserSettingsParams struct {
	ReminderEnabled *bool
	ReminderTime    pgtype.Time
	DefaultMode     *string
	AnalysisEnabled *bool
	MemoryEnabled   *bool
	MoodPickEnabled *bool
	Now             time.Time
	UserID          uuid.UUID
}

// 넘기지 않은(NULL) 항목은 그대로 둔다. 설정 화면은 한 번에 하나씩 바꾼다.
func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.ReminderEnabled,
		arg.ReminderTime,
		arg.DefaultMode,
		arg.AnalysisEnabled,
		arg.MemoryEnabled,
		arg.MoodPickEnabled,
		arg.Now,
		arg.UserID,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.ReminderEnabled,
		&i.ReminderTime,
		&i.DefaultMode,
		&i.AnalysisEnabled,
		&i.MemoryEnabled,
		&i.MoodPickEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
