// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSignal = `-- name: CancelSignal :one
UPDATE signals AS s
SET cancelled_at = COALESCE(s.cancelled_at, $1::timestamptz)
WHERE s.id = $2
  AND s.user_id = $3
RETURNING (SELECT d.record_date FROM days AS d WHERE d.id = s.day_id) AS record_date
`

type CancelSignalParams struct {
	Now    time.Time
	ID     uuid.UUID
	UserID uuid.UUID
}

// 사용자가 "이건 아니에요"로 신호 하나를 취소한다. 행은 남고 계산에서만 빠진다.
// 이미 취소한 행을 다시 취소해도 처음 취소한 시각을 그대로 두고 성공한다. 같은 버튼을 두 번 눌러도 결과가 같다.
// 남의 행은 ID를 알아도 취소할 수 없고, 그때는 없는 것과 똑같이 찾지 못함이 된다.
// 그 행이 매달린 기록 날짜를 돌려준다. 취소하면 그날의 판단이 달라지므로 부르는 쪽이 그날을 다시 읽는다.
func (q *Queries) CancelSignal(ctx context.Context, arg CancelSignalParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, cancelSignal, arg.Now, arg.ID, arg.UserID)
	var record_date pgtype.Date
	err := row.Scan(&record_date)
	return record_date, err
}

const insertSignal = `-- name: InsertSignal :one
INSERT INTO signals (
    id, user_id, day_id, conversation_id, item, status, explicitness,
    evidence_enc, evidence_utterance_id, extractor_version, created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, user_id, day_id, conversation_id, item, status, explicitness, evidence_enc, evidence_utterance_id, cancelled_at, extractor_version, created_at
`

type InsertSignalParams struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	DayID               uuid.UUID
	ConversationID      uuid.UUID
	Item                string
	Status              string
	Explicitness        string
	EvidenceEnc         []byte
	EvidenceUtteranceID *uuid.UUID
	ExtractorVersion    string
	Now                 time.Time
}

// 신호 행 하나다. 직접 부르지 않고 store.SaveConversationSignals를 쓴다.
// 여덟 항목은 한 트랜잭션에서 함께 들어가야 한다. 낱개로 넣으면 일부 항목만 든 하루가 계산에 들어가서,
// 그날 관찰되지 않은 항목과 아직 뽑히지 않은 항목이 구별되지 않는다.
func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, insertSignal,
		arg.ID,
		arg.UserID,
		arg.DayID,
		arg.ConversationID,
		arg.Item,
		arg.Status,
		arg.Explicitness,
		arg.EvidenceEnc,
		arg.EvidenceUtteranceID,
		arg.ExtractorVersion,
		arg.Now,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DayID,
		&i.ConversationID,
		&i.Item,
		&i.Status,
		&i.Explicitness,
		&i.EvidenceEnc,
		&i.EvidenceUtteranceID,
		&i.CancelledAt,
		&i.ExtractorVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listSignalExtractors = `-- name: ListSignalExtractors :many
SELECT s.extractor_version,
       count(*)::bigint AS row_count,
       max(s.created_at)::timestamptz AS last_at
FROM signals AS s
WHERE s.user_id = $1
GROUP BY s.extractor_version
ORDER BY max(s.created_at) DESC, s.extractor_version
`

type ListSignalExtractorsRow struct {
	ExtractorVersion string
	RowCount         int64
	LastAt           time.Time
}

// 그 사용자의 신호 행이 어떤 추출기에서 나왔는지다. 내부 확인 화면이 읽는다.
//
// 이 값을 화면에 띄우는 까닭: 키 없이 띄운 서버는 낱말 표로 답하는 모델로도 여덟 항목의 행을 채운다.
// 저장된 판단만 보고는 실제 모델이 읽은 것과 구별할 수 없고, 화면에도 아무 표시가 없다.
// 행에 남은 이 표시가 둘을 가르는 유일한 자리다.
// 판단이 아니라 어디서 나왔는지를 세는 것이라 취소된 행도 함께 센다.
func (q *Queries) ListSignalExtractors(ctx context.Context, userID uuid.UUID) ([]ListSignalExtractorsRow, error) {
	rows, err := q.db.Query(ctx, listSignalExtractors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSignalExtractorsRow{}
	for rows.Next() {
		var i ListSignalExtractorsRow
		if err := rows.Scan(&i.ExtractorVersion, &i.RowCount, &i.LastAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalRowsByDateRange = `-- name: ListSignalRowsByDateRange :many
SELECT s.id,
       d.record_date,
       s.conversation_id,
       s.item,
       s.status,
       s.explicitness,
       s.evidence_enc,
       (s.cancelled_at IS NOT NULL)::boolean AS cancelled
FROM signals AS s
JOIN days AS d ON d.id = s.day_id
WHERE s.user_id = $1
  AND d.user_id = $1
  AND d.record_date >= $2
  AND d.record_date <= $3
ORDER BY d.record_date, s.conversation_id, s.item
`

type ListSignalRowsByDateRangeParams struct {
	UserID   uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ListSignalRowsByDateRangeRow struct {
	ID             uuid.UUID
	RecordDate     pgtype.Date
	ConversationID uuid.UUID
	Item           string
	Status         string
	Explicitness   string
	EvidenceEnc    []byte
	Cancelled      bool
}

// 기간 안(from_date와 to_date를 모두 포함)의 신호 판단이다. 추세 화면이 읽는다.
//
// 취소된 행도 돌려준다. 계산 코어가 취소된 행을 스스로 빼기 때문에, 화면에 보여줄 것과 계산에 넣을 것을
// 한 번 읽어 나눠 쓸 수 있다. 걸러서 돌려주면 취소한 판단을 취소된 것으로 보여줄 방법이 없어진다.
// 근거 글의 암호문도 함께 온다. 점만 그리는 추세 화면은 읽지 않고 두면 되고, 기간의 근거를 훑는 쪽은 여기서 읽는다.
// 근거가 어느 발화에서 왔는지까지 필요하면 ListSignalsByDate로 하루씩 읽는다.
func (q *Queries) ListSignalRowsByDateRange(ctx context.Context, arg ListSignalRowsByDateRangeParams) ([]ListSignalRowsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listSignalRowsByDateRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSignalRowsByDateRangeRow{}
	for rows.Next() {
		var i ListSignalRowsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordDate,
			&i.ConversationID,
			&i.Item,
			&i.Status,
			&i.Explicitness,
			&i.EvidenceEnc,
			&i.Cancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalRowsByUser = `-- name: ListSignalRowsByUser :many
SELECT d.record_date,
       s.conversation_id,
       s.item,
       s.status,
       s.explicitness,
       (s.cancelled_at IS NOT NULL)::boolean AS cancelled
FROM signals AS s
JOIN days AS d ON d.id = s.day_id
WHERE s.user_id = $1
ORDER BY d.record_date, s.conversation_id, s.item
`

type ListSignalRowsByUserRow struct {
	RecordDate     pgtype.Date
	ConversationID uuid.UUID
	Item           string
	Status         string
	Explicitness   string
	Cancelled      bool
}

// 그 사용자의 신호 판단 전부다. 글(근거)은 읽지 않고 계산에 쓰는 값만 읽는다.
// 대화 도중에 그 사람의 최근 상태를 읽을 때와, 첫 대화 날부터 다시 돌리는 계산(개입 단계)에 쓴다.
// 단계는 첫 대화 날부터 다시 돌려 구하므로 기간을 자르지 않는다.
// 신호 행은 대화 하나의 분석이 끝났을 때 여덟 항목이 한꺼번에 들어온다. 분석이 끝나지 않은 대화의 행은 여기에 없다.
func (q *Queries) ListSignalRowsByUser(ctx context.Context, userID uuid.UUID) ([]ListSignalRowsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSignalRowsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSignalRowsByUserRow{}
	for rows.Next() {
		var i ListSignalRowsByUserRow
		if err := rows.Scan(
			&i.RecordDate,
			&i.ConversationID,
			&i.Item,
			&i.Status,
			&i.Explicitness,
			&i.Cancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalsByDate = `-- name: ListSignalsByDate :many
SELECT s.id,
       s.conversation_id,
       s.item,
       s.status,
       s.explicitness,
       s.evidence_enc,
       (s.cancelled_at IS NOT NULL)::boolean AS cancelled,
       s.created_at,
       u.id AS utterance_id,
       u.seq AS utterance_seq,
       u.text_enc AS utterance_text_enc,
       u.created_at AS utterance_created_at
FROM signals AS s
JOIN days AS d ON d.id = s.day_id
LEFT JOIN utterances AS u ON u.id = s.evidence_utterance_id
WHERE s.user_id = $1
  AND d.user_id = $1
  AND d.record_date = $2
ORDER BY s.conversation_id, s.item
`

type ListSignalsByDateParams struct {
	UserID     uuid.UUID
	RecordDate pgtype.Date
}

type ListSignalsByDateRow struct {
	ID                 uuid.UUID
	ConversationID     uuid.UUID
	Item               string
	Status             string
	Explicitness       string
	EvidenceEnc        []byte
	Cancelled          bool
	CreatedAt          time.Time
	UtteranceID        *uuid.UUID
	UtteranceSeq       *int32
	UtteranceTextEnc   []byte
	UtteranceCreatedAt *time.Time
}

// 하루의 신호 판단 전부와, 근거가 된 발화다. 근거 화면이 읽는다.
// 하루에 대화를 여러 번 했으면 같은 항목의 행이 대화마다 하나씩 있다. 하루의 판단으로 합치는 일은 계산 쪽이 한다.
//
// 발화는 왼쪽 조인이다. 발화가 지워지면 가리키는 값만 비워지고(ON DELETE SET NULL) 신호 행은 남으므로,
// 근거 글은 있는데 어느 발화에서 왔는지는 모르는 행이 생길 수 있다.
func (q *Queries) ListSignalsByDate(ctx context.Context, arg ListSignalsByDateParams) ([]ListSignalsByDateRow, error) {
	rows, err := q.db.Query(ctx, listSignalsByDate, arg.UserID, arg.RecordDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSignalsByDateRow{}
	for rows.Next() {
		var i ListSignalsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Item,
			&i.Status,
			&i.Explicitness,
			&i.EvidenceEnc,
			&i.Cancelled,
			&i.CreatedAt,
			&i.UtteranceID,
			&i.UtteranceSeq,
			&i.UtteranceTextEnc,
			&i.UtteranceCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncancelSignal = `-- name: UncancelSignal :one
UPDATE signals AS s
SET cancelled_at = NULL
WHERE s.id = $1
  AND s.user_id = $2
RETURNING (SELECT d.record_date FROM days AS d WHERE d.id = s.day_id) AS record_date
`

type UncancelSignalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 취소를 되돌린다. 취소한 적이 없는 행에 불러도 성공한다.
func (q *Queries) UncancelSignal(ctx context.Context, arg UncancelSignalParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, uncancelSignal, arg.ID, arg.UserID)
	var record_date pgtype.Date
	err := row.Scan(&record_date)
	return record_date, err
}
