// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listSignalRowsByUser = `-- name: ListSignalRowsByUser :many
SELECT d.record_date,
       s.conversation_id,
       s.item,
       s.status,
       s.explicitness,
       (s.cancelled_at IS NOT NULL)::boolean AS cancelled
FROM signals AS s
JOIN days AS d ON d.id = s.day_id
WHERE s.user_id = $1
ORDER BY d.record_date, s.conversation_id, s.item
`

type ListSignalRowsByUserRow struct {
	RecordDate     pgtype.Date
	ConversationID uuid.UUID
	Item           string
	Status         string
	Explicitness   string
	Cancelled      bool
}

// 그 사용자의 신호 판단 전부다. 글(근거)은 읽지 않고 계산에 쓰는 값만 읽는다.
// 대화 도중에 그 사람의 최근 상태를 읽을 때 쓴다. 단계는 첫 대화 날부터 다시 돌려 구하므로 기간을 자르지 않는다.
// 신호 행은 대화 하나의 분석이 끝났을 때 여덟 항목이 한꺼번에 들어온다. 분석이 끝나지 않은 대화의 행은 여기에 없다.
func (q *Queries) ListSignalRowsByUser(ctx context.Context, userID uuid.UUID) ([]ListSignalRowsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSignalRowsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSignalRowsByUserRow{}
	for rows.Next() {
		var i ListSignalRowsByUserRow
		if err := rows.Scan(
			&i.RecordDate,
			&i.ConversationID,
			&i.Item,
			&i.Status,
			&i.Explicitness,
			&i.Cancelled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
