// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, display_name, timezone, is_demo, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $7
)
RETURNING id, email, email_verified_at, password_hash, display_name, timezone, role, is_demo, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash *string
	DisplayName  *string
	Timezone     string
	IsDemo       bool
	Now          time.Time
}

// role은 넣지 않는다. 가입으로는 일반 사용자만 만들어진다.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Timezone,
		arg.IsDemo,
		arg.Now,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.Role,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserKey = `-- name: CreateUserKey :exec
INSERT INTO user_keys (user_id, wrapped_dek, kek_version, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserKeyParams struct {
	UserID     uuid.UUID
	WrappedDEK []byte
	KEKVersion int16
	Now        time.Time
}

func (q *Queries) CreateUserKey(ctx context.Context, arg CreateUserKeyParams) error {
	_, err := q.db.Exec(ctx, createUserKey,
		arg.UserID,
		arg.WrappedDEK,
		arg.KEKVersion,
		arg.Now,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1
RETURNING id
`

// 외래 키의 ON DELETE CASCADE가 그 사용자의 모든 기록을 함께 지운다.
// 지운 행을 돌려받아, 없는 사용자를 지우려 한 경우를 찾지 못함 오류로 구분한다.
func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, password_hash, display_name, timezone, role, is_demo, created_at, updated_at FROM users WHERE email = $1
`

// email이 citext라 대소문자를 가리지 않고 찾는다.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.Role,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, password_hash, display_name, timezone, role, is_demo, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.Role,
		&i.IsDemo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserKey = `-- name: GetUserKey :one
SELECT user_id, wrapped_dek, kek_version, created_at FROM user_keys WHERE user_id = $1
`

func (q *Queries) GetUserKey(ctx context.Context, userID uuid.UUID) (UserKey, error) {
	row := q.db.QueryRow(ctx, getUserKey, userID)
	var i UserKey
	err := row.Scan(
		&i.UserID,
		&i.WrappedDEK,
		&i.KEKVersion,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :execrows
UPDATE users
SET password_hash = $1::text,
    updated_at    = $2
WHERE id = $3
  AND password_hash = $4::text
`

type UpdateUserPasswordHashParams struct {
	NewHash string
	Now     time.Time
	ID      uuid.UUID
	OldHash string
}

// 로그인에 성공한 김에, 옛 설정으로 만든 해시를 지금 설정으로 다시 만들어 바꿔 넣을 때 쓴다.
// 읽었던 해시가 그대로일 때만 바꾼다. 그 사이에 비밀번호가 바뀌었다면 새 비밀번호를 옛 비밀번호로 되돌리게 된다.
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPasswordHash,
		arg.NewHash,
		arg.Now,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
