// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: utterances.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendUtteranceUnderLock = `-- name: AppendUtteranceUnderLock :one
INSERT INTO utterances (
    id, conversation_id, user_id, seq, speaker, modality, origin, text_enc, stt_min_confidence, client_message_id, created_at
)
SELECT $1::uuid,
       $2::uuid,
       $3::uuid,
       COALESCE(MAX(u.seq) + 1, 0),
       $4::text,
       $5::text,
       $6::text,
       $7::bytea,
       $8::real,
       $9::uuid,
       $10::timestamptz
FROM utterances AS u
WHERE u.conversation_id = $2::uuid
RETURNING id, conversation_id, user_id, seq, speaker, modality, origin, text_enc, stt_min_confidence, created_at, client_message_id
`

type AppendUtteranceUnderLockParams struct {
	ID               uuid.UUID
	ConversationID   uuid.UUID
	UserID           uuid.UUID
	Speaker          string
	Modality         string
	Origin           string
	TextEnc          []byte
	STTMinConfidence *float32
	ClientMessageID  *uuid.UUID
	Now              time.Time
}

// 대화의 다음 순번으로 발화를 더한다. 직접 부르지 않고 store.AppendUtterance를 쓴다.
// 같은 트랜잭션에서 LockConversationForAppend를 먼저 불러야 순번이 겹치지 않는다.
// 잠금 없이 불러도 순번이 겹친 발화가 저장되지는 않는다. (conversation_id, seq)의 유일 제약에 걸려 한쪽이 실패한다.
func (q *Queries) AppendUtteranceUnderLock(ctx context.Context, arg AppendUtteranceUnderLockParams) (Utterance, error) {
	row := q.db.QueryRow(ctx, appendUtteranceUnderLock,
		arg.ID,
		arg.ConversationID,
		arg.UserID,
		arg.Speaker,
		arg.Modality,
		arg.Origin,
		arg.TextEnc,
		arg.STTMinConfidence,
		arg.ClientMessageID,
		arg.Now,
	)
	var i Utterance
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Seq,
		&i.Speaker,
		&i.Modality,
		&i.Origin,
		&i.TextEnc,
		&i.STTMinConfidence,
		&i.CreatedAt,
		&i.ClientMessageID,
	)
	return i, err
}

const getUtteranceByClientMessageID = `-- name: GetUtteranceByClientMessageID :one
SELECT id, conversation_id, user_id, seq, speaker, modality, origin, text_enc, stt_min_confidence, created_at, client_message_id FROM utterances
WHERE conversation_id = $1
  AND client_message_id = $2::uuid
`

type GetUtteranceByClientMessageIDParams struct {
	ConversationID  uuid.UUID
	ClientMessageID uuid.UUID
}

// 같은 글을 다시 보낸 것인지 알아본다.
func (q *Queries) GetUtteranceByClientMessageID(ctx context.Context, arg GetUtteranceByClientMessageIDParams) (Utterance, error) {
	row := q.db.QueryRow(ctx, getUtteranceByClientMessageID, arg.ConversationID, arg.ClientMessageID)
	var i Utterance
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Seq,
		&i.Speaker,
		&i.Modality,
		&i.Origin,
		&i.TextEnc,
		&i.STTMinConfidence,
		&i.CreatedAt,
		&i.ClientMessageID,
	)
	return i, err
}

const listLastUtterances = `-- name: ListLastUtterances :many
SELECT id, conversation_id, user_id, seq, speaker, modality, origin, text_enc, stt_min_confidence, created_at, client_message_id FROM utterances
WHERE conversation_id = $1
  AND user_id = $2
ORDER BY seq DESC
LIMIT $3
`

type ListLastUtterancesParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
	MaxRows        int32
}

// 가장 최근 발화부터 거꾸로 돌려준다. 위기 판별에 넘길 직전 몇 턴을 읽을 때 대화 전체를 읽지 않으려는 것이다.
func (q *Queries) ListLastUtterances(ctx context.Context, arg ListLastUtterancesParams) ([]Utterance, error) {
	rows, err := q.db.Query(ctx, listLastUtterances, arg.ConversationID, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Utterance{}
	for rows.Next() {
		var i Utterance
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Seq,
			&i.Speaker,
			&i.Modality,
			&i.Origin,
			&i.TextEnc,
			&i.STTMinConfidence,
			&i.CreatedAt,
			&i.ClientMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUtterancesByConversation = `-- name: ListUtterancesByConversation :many
SELECT id, conversation_id, user_id, seq, speaker, modality, origin, text_enc, stt_min_confidence, created_at, client_message_id FROM utterances
WHERE conversation_id = $1
  AND user_id = $2
ORDER BY seq
`

type ListUtterancesByConversationParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) ListUtterancesByConversation(ctx context.Context, arg ListUtterancesByConversationParams) ([]Utterance, error) {
	rows, err := q.db.Query(ctx, listUtterancesByConversation, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Utterance{}
	for rows.Next() {
		var i Utterance
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Seq,
			&i.Speaker,
			&i.Modality,
			&i.Origin,
			&i.TextEnc,
			&i.STTMinConfidence,
			&i.CreatedAt,
			&i.ClientMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUtterancesByDay = `-- name: ListUtterancesByDay :many
SELECT u.id, u.conversation_id, u.user_id, u.seq, u.speaker, u.modality, u.origin, u.text_enc, u.stt_min_confidence, u.created_at, u.client_message_id
FROM utterances AS u
JOIN conversations AS c ON c.id = u.conversation_id
WHERE c.day_id = $1
  AND c.user_id = $2
ORDER BY c.started_at, c.id, u.seq
`

type ListUtterancesByDayParams struct {
	DayID  uuid.UUID
	UserID uuid.UUID
}

// 그날의 모든 대화의 발화를 대화를 시작한 순서, 그 안에서는 순번대로 돌려준다. 일기 초안의 재료다.
func (q *Queries) ListUtterancesByDay(ctx context.Context, arg ListUtterancesByDayParams) ([]Utterance, error) {
	rows, err := q.db.Query(ctx, listUtterancesByDay, arg.DayID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Utterance{}
	for rows.Next() {
		var i Utterance
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Seq,
			&i.Speaker,
			&i.Modality,
			&i.Origin,
			&i.TextEnc,
			&i.STTMinConfidence,
			&i.CreatedAt,
			&i.ClientMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
