// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ConsentKind.
const (
	ConsentKindOverseasTransfer ConsentKind = "overseas_transfer"
	ConsentKindPrivacy          ConsentKind = "privacy"
	ConsentKindSensitiveData    ConsentKind = "sensitive_data"
	ConsentKindTerms            ConsentKind = "terms"
)

// Valid indicates whether the value is a known member of the ConsentKind enum.
func (e ConsentKind) Valid() bool {
	switch e {
	case ConsentKindOverseasTransfer:
		return true
	case ConsentKindPrivacy:
		return true
	case ConsentKindSensitiveData:
		return true
	case ConsentKindTerms:
		return true
	default:
		return false
	}
}

// Defines values for ConversationMode.
const (
	ConversationModeChat  ConversationMode = "chat"
	ConversationModeVoice ConversationMode = "voice"
)

// Valid indicates whether the value is a known member of the ConversationMode enum.
func (e ConversationMode) Valid() bool {
	switch e {
	case ConversationModeChat:
		return true
	case ConversationModeVoice:
		return true
	default:
		return false
	}
}

// Defines values for DiaryStatus.
const (
	DiaryStatusConfirmed DiaryStatus = "confirmed"
	DiaryStatusDraft     DiaryStatus = "draft"
)

// Valid indicates whether the value is a known member of the DiaryStatus enum.
func (e DiaryStatus) Valid() bool {
	switch e {
	case DiaryStatusConfirmed:
		return true
	case DiaryStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for PasswordReason.
const (
	PasswordReasonInvalidEncoding PasswordReason = "invalid_encoding"
	PasswordReasonMatchesEmail    PasswordReason = "matches_email"
	PasswordReasonTooCommon       PasswordReason = "too_common"
	PasswordReasonTooLong         PasswordReason = "too_long"
	PasswordReasonTooShort        PasswordReason = "too_short"
)

// Valid indicates whether the value is a known member of the PasswordReason enum.
func (e PasswordReason) Valid() bool {
	switch e {
	case PasswordReasonInvalidEncoding:
		return true
	case PasswordReasonMatchesEmail:
		return true
	case PasswordReasonTooCommon:
		return true
	case PasswordReasonTooLong:
		return true
	case PasswordReasonTooShort:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	ProblemCodeConsentRequired      ProblemCode = "consent_required"
	ProblemCodeCrossOriginRejected  ProblemCode = "cross_origin_rejected"
	ProblemCodeEmailTaken           ProblemCode = "email_taken"
	ProblemCodeForbidden            ProblemCode = "forbidden"
	ProblemCodeInternalError        ProblemCode = "internal_error"
	ProblemCodeInvalidCredentials   ProblemCode = "invalid_credentials"
	ProblemCodeMethodNotAllowed     ProblemCode = "method_not_allowed"
	ProblemCodeNotFound             ProblemCode = "not_found"
	ProblemCodePayloadTooLarge      ProblemCode = "payload_too_large"
	ProblemCodeRateLimited          ProblemCode = "rate_limited"
	ProblemCodeServiceUnavailable   ProblemCode = "service_unavailable"
	ProblemCodeUnauthenticated      ProblemCode = "unauthenticated"
	ProblemCodeUnsupportedMediaType ProblemCode = "unsupported_media_type"
	ProblemCodeValidationFailed     ProblemCode = "validation_failed"
	ProblemCodeWeakPassword         ProblemCode = "weak_password"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case ProblemCodeConsentRequired:
		return true
	case ProblemCodeCrossOriginRejected:
		return true
	case ProblemCodeEmailTaken:
		return true
	case ProblemCodeForbidden:
		return true
	case ProblemCodeInternalError:
		return true
	case ProblemCodeInvalidCredentials:
		return true
	case ProblemCodeMethodNotAllowed:
		return true
	case ProblemCodeNotFound:
		return true
	case ProblemCodePayloadTooLarge:
		return true
	case ProblemCodeRateLimited:
		return true
	case ProblemCodeServiceUnavailable:
		return true
	case ProblemCodeUnauthenticated:
		return true
	case ProblemCodeUnsupportedMediaType:
		return true
	case ProblemCodeValidationFailed:
		return true
	case ProblemCodeWeakPassword:
		return true
	default:
		return false
	}
}

// Defines values for ProblemField.
const (
	ProblemFieldDisplayName ProblemField = "display_name"
	ProblemFieldEmail       ProblemField = "email"
	ProblemFieldQ           ProblemField = "q"
	ProblemFieldText        ProblemField = "text"
	ProblemFieldTimezone    ProblemField = "timezone"
)

// Valid indicates whether the value is a known member of the ProblemField enum.
func (e ProblemField) Valid() bool {
	switch e {
	case ProblemFieldDisplayName:
		return true
	case ProblemFieldEmail:
		return true
	case ProblemFieldQ:
		return true
	case ProblemFieldText:
		return true
	case ProblemFieldTimezone:
		return true
	default:
		return false
	}
}

// Defines values for WsAITextType.
const (
	WsAITextTypeAiText WsAITextType = "ai_text"
)

// Valid indicates whether the value is a known member of the WsAITextType enum.
func (e WsAITextType) Valid() bool {
	switch e {
	case WsAITextTypeAiText:
		return true
	default:
		return false
	}
}

// Defines values for WsDiaryReadyType.
const (
	WsDiaryReadyTypeDiaryReady WsDiaryReadyType = "diary_ready"
)

// Valid indicates whether the value is a known member of the WsDiaryReadyType enum.
func (e WsDiaryReadyType) Valid() bool {
	switch e {
	case WsDiaryReadyTypeDiaryReady:
		return true
	default:
		return false
	}
}

// Defines values for WsEndType.
const (
	WsEndTypeEnd WsEndType = "end"
)

// Valid indicates whether the value is a known member of the WsEndType enum.
func (e WsEndType) Valid() bool {
	switch e {
	case WsEndTypeEnd:
		return true
	default:
		return false
	}
}

// Defines values for WsEndReason.
const (
	WsEndReasonIdle WsEndReason = "idle"
	WsEndReasonUser WsEndReason = "user"
)

// Valid indicates whether the value is a known member of the WsEndReason enum.
func (e WsEndReason) Valid() bool {
	switch e {
	case WsEndReasonIdle:
		return true
	case WsEndReasonUser:
		return true
	default:
		return false
	}
}

// Defines values for WsEndedType.
const (
	WsEndedTypeEnded WsEndedType = "ended"
)

// Valid indicates whether the value is a known member of the WsEndedType enum.
func (e WsEndedType) Valid() bool {
	switch e {
	case WsEndedTypeEnded:
		return true
	default:
		return false
	}
}

// Defines values for WsErrorType.
const (
	WsErrorTypeError WsErrorType = "error"
)

// Valid indicates whether the value is a known member of the WsErrorType enum.
func (e WsErrorType) Valid() bool {
	switch e {
	case WsErrorTypeError:
		return true
	default:
		return false
	}
}

// Defines values for WsErrorCode.
const (
	WsErrorCodeAlreadyStarted    WsErrorCode = "already_started"
	WsErrorCodeConversationEnded WsErrorCode = "conversation_ended"
	WsErrorCodeInternalError     WsErrorCode = "internal_error"
	WsErrorCodeInvalidMessage    WsErrorCode = "invalid_message"
	WsErrorCodeMessageTooLarge   WsErrorCode = "message_too_large"
	WsErrorCodeNotStarted        WsErrorCode = "not_started"
	WsErrorCodeRateLimited       WsErrorCode = "rate_limited"
	WsErrorCodeUnsupportedMode   WsErrorCode = "unsupported_mode"
)

// Valid indicates whether the value is a known member of the WsErrorCode enum.
func (e WsErrorCode) Valid() bool {
	switch e {
	case WsErrorCodeAlreadyStarted:
		return true
	case WsErrorCodeConversationEnded:
		return true
	case WsErrorCodeInternalError:
		return true
	case WsErrorCodeInvalidMessage:
		return true
	case WsErrorCodeMessageTooLarge:
		return true
	case WsErrorCodeNotStarted:
		return true
	case WsErrorCodeRateLimited:
		return true
	case WsErrorCodeUnsupportedMode:
		return true
	default:
		return false
	}
}

// Defines values for WsOrigin.
const (
	WsOriginFixed    WsOrigin = "fixed"
	WsOriginModel    WsOrigin = "model"
	WsOriginTemplate WsOrigin = "template"
	WsOriginUser     WsOrigin = "user"
)

// Valid indicates whether the value is a known member of the WsOrigin enum.
func (e WsOrigin) Valid() bool {
	switch e {
	case WsOriginFixed:
		return true
	case WsOriginModel:
		return true
	case WsOriginTemplate:
		return true
	case WsOriginUser:
		return true
	default:
		return false
	}
}

// Defines values for WsReadyType.
const (
	WsReadyTypeReady WsReadyType = "ready"
)

// Valid indicates whether the value is a known member of the WsReadyType enum.
func (e WsReadyType) Valid() bool {
	switch e {
	case WsReadyTypeReady:
		return true
	default:
		return false
	}
}

// Defines values for WsResourcesType.
const (
	WsResourcesTypeResources WsResourcesType = "resources"
)

// Valid indicates whether the value is a known member of the WsResourcesType enum.
func (e WsResourcesType) Valid() bool {
	switch e {
	case WsResourcesTypeResources:
		return true
	default:
		return false
	}
}

// Defines values for WsSpeaker.
const (
	WsSpeakerAi   WsSpeaker = "ai"
	WsSpeakerUser WsSpeaker = "user"
)

// Valid indicates whether the value is a known member of the WsSpeaker enum.
func (e WsSpeaker) Valid() bool {
	switch e {
	case WsSpeakerAi:
		return true
	case WsSpeakerUser:
		return true
	default:
		return false
	}
}

// Defines values for WsStartType.
const (
	WsStartTypeStart WsStartType = "start"
)

// Valid indicates whether the value is a known member of the WsStartType enum.
func (e WsStartType) Valid() bool {
	switch e {
	case WsStartTypeStart:
		return true
	default:
		return false
	}
}

// Defines values for WsThinkingType.
const (
	WsThinkingTypeThinking WsThinkingType = "thinking"
)

// Valid indicates whether the value is a known member of the WsThinkingType enum.
func (e WsThinkingType) Valid() bool {
	switch e {
	case WsThinkingTypeThinking:
		return true
	default:
		return false
	}
}

// Defines values for WsUserTextType.
const (
	WsUserTextTypeUserText WsUserTextType = "user_text"
)

// Valid indicates whether the value is a known member of the WsUserTextType enum.
func (e WsUserTextType) Valid() bool {
	switch e {
	case WsUserTextTypeUserText:
		return true
	default:
		return false
	}
}

// AuthRequirements defines model for AuthRequirements.
type AuthRequirements struct {
	// Consents 가입에 필요한 동의와 그 지금 판. 모두 필수다
	Consents []ConsentGrant `json:"consents"`

	// DisplayNameMaxLength 부를 이름의 최대 글자 수
	//
	// Example: 40
	DisplayNameMaxLength int                  `json:"display_name_max_length"`
	Password             PasswordRequirements `json:"password"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	User User `json:"user"`
}

// ConsentGrant defines model for ConsentGrant.
type ConsentGrant struct {
	// Kind 동의의 종류.
	// `terms` 이용약관, `privacy` 개인정보 처리방침, `sensitive_data` 마음에 관한 기록의 처리,
	// `overseas_transfer` 대화 내용이 외부 AI 서비스로 전송되어 해외에서 처리되는 것.
	Kind ConsentKind `json:"kind"`

	// Version 사용자가 보고 동의한 문서의 판
	//
	// Example: 2026-09-20
	Version string `json:"version"`
}

// ConsentKind 동의의 종류.
// `terms` 이용약관, `privacy` 개인정보 처리방침, `sensitive_data` 마음에 관한 기록의 처리,
// `overseas_transfer` 대화 내용이 외부 AI 서비스로 전송되어 해외에서 처리되는 것.
type ConsentKind string

// ConsentProblem `consent_required`일 때만 있다
type ConsentProblem struct {
	// Missing 필요한데 오지 않은 동의
	Missing []ConsentKind `json:"missing"`

	// Outdated 왔지만 지금 판이 아닌 동의. 가입 규칙을 다시 받아 새 문서를 보여줘야 한다
	Outdated []ConsentKind `json:"outdated"`
}

// ConversationMode 대화를 시작할 때의 기본 방식
type ConversationMode string

// Diary defines model for Diary.
type Diary struct {
	// ConfirmedAt 마지막으로 확인한 시각. 한 번도 확인하지 않았으면 null이다
	ConfirmedAt *Timestamp `json:"confirmed_at"`

	// Date 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	Date RecordDate `json:"date"`

	// Status `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
	Status DiaryStatus `json:"status"`

	// Text 상태가 `draft`면 초안, `confirmed`면 확인한 글이다.
	// 초안을 만들지 못한 날에는 빈 초안이 온다. 사용자가 직접 써서 확인하면 된다.
	Text string `json:"text"`

	// UpdatedAt UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
	//
	// Example: 2026-09-20T12:00:00.000Z
	UpdatedAt Timestamp `json:"updated_at"`
}

// DiaryList defines model for DiaryList.
type DiaryList struct {
	Items []DiarySummary `json:"items"`
}

// DiaryStatus `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
type DiaryStatus string

// DiarySummary defines model for DiarySummary.
type DiarySummary struct {
	// Date 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	Date RecordDate `json:"date"`

	// FirstLine 지금 화면에 보일 글의 첫 줄. 길면 잘라서 준다. 빈 초안이면 빈 문자열이다
	FirstLine string `json:"first_line"`

	// Snippet 검색어가 나온 자리의 앞뒤 글. 검색 결과에만 있다
	Snippet *string `json:"snippet,omitempty"`

	// Status `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
	Status DiaryStatus `json:"status"`
}

// DiaryUpdate defines model for DiaryUpdate.
type DiaryUpdate struct {
	// Text 일기 글 전체
	Text string `json:"text"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	Settings SettingsSummary `json:"settings"`
	User     User            `json:"user"`
}

// PasswordReason 비밀번호를 받지 않는 이유.
// `too_short` 너무 짧다, `too_long` 너무 길다, `too_common` 누구나 먼저 넣어 보는 흔한 비밀번호다,
// `matches_email` 이메일 주소나 그 앞부분과 같다, `invalid_encoding` 글자로 읽을 수 없는 바이트가 있다.
type PasswordReason string

// PasswordRequirements defines model for PasswordRequirements.
type PasswordRequirements struct {
	// MaxBytes 최대 길이. UTF-8 바이트로 센다(한글 한 글자는 3바이트)
	//
	// Example: 128
	MaxBytes int `json:"max_bytes"`

	// MinLength 최소 길이. 글자 수로 센다
	//
	// Example: 10
	MinLength int `json:"min_length"`
}

// Problem RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type Problem struct {
	// Code 오류의 종류. 값은 바뀌지 않는다. 화면은 이 값으로 안내 문구를 고른다
	Code ProblemCode `json:"code"`

	// Consents `consent_required`일 때만 있다
	Consents *ConsentProblem `json:"consents,omitempty"`

	// Fields 422 `validation_failed`일 때만 있다
	Fields *[]ProblemField `json:"fields,omitempty"`

	// Reasons `weak_password`일 때만 있다
	Reasons *[]PasswordReason `json:"reasons,omitempty"`

	// RequestID 이 요청의 ID. 응답의 `X-Request-Id` 헤더와 같다. 문의할 때 알려주면 서버 로그에서 찾을 수 있다
	RequestID string `json:"request_id"`

	// Status HTTP 상태 코드와 같은 값
	//
	// Example: 422
	Status int `json:"status"`

	// Title 개발자가 읽는 짧은 영어 문구. 사용자에게 보여주지 않는다
	//
	// Example: Password does not meet the policy
	Title string `json:"title"`

	// Type 오류 종류를 가리키는 URI 참조. `/problems/{code}` 꼴이다
	//
	// Example: /problems/weak_password
	Type string `json:"type"`
}

// ProblemCode 오류의 종류. 값은 바뀌지 않는다. 화면은 이 값으로 안내 문구를 고른다
type ProblemCode string

// ProblemField 받을 수 없는 값이 든 요청 필드의 이름. 쿼리 매개변수일 때는 그 이름이다
type ProblemField string

// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
//
// Example: 2026-09-20
type RecordDate = openapi_types.Date

// Resource defines model for Resource.
type Resource struct {
	// Description 언제, 어떤 도움을 받을 수 있는지에 대한 한두 문장
	//
	// Example: 24시간, 지금 바로 이야기를 들어줄 사람과 연결돼요.
	Description string `json:"description"`

	// ID 자원을 가리키는 고정된 이름. 화면이 아이콘을 고르거나 목록을 견줄 때 쓴다
	//
	// Example: suicide_prevention_109
	ID string `json:"id"`

	// Name Example: 자살예방상담전화
	Name string `json:"name"`

	// Phone 전화번호. 화면에 그대로 보여주고, 걸 때는 숫자만 남겨 `tel:`에 넣는다
	//
	// Example: 109
	Phone string `json:"phone"`
}

// ResourceList defines model for ResourceList.
type ResourceList struct {
	// Items 급한 곳이 앞에 온다
	Items []Resource `json:"items"`
}

// SettingsSummary defines model for SettingsSummary.
type SettingsSummary struct {
	// AnalysisEnabled 끄면 대화와 일기만 남기고 마음 신호를 뽑지 않는다
	AnalysisEnabled bool `json:"analysis_enabled"`

	// DefaultMode 대화를 시작할 때의 기본 방식
	DefaultMode     ConversationMode `json:"default_mode"`
	MemoryEnabled   bool             `json:"memory_enabled"`
	MoodPickEnabled bool             `json:"mood_pick_enabled"`
	ReminderEnabled bool             `json:"reminder_enabled"`

	// ReminderTime 알림 시각. 사용자 시간대의 벽시계 시각이고 `HH:MM` 꼴이다
	//
	// Example: 20:00
	ReminderTime string `json:"reminder_time"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Consents `GET /api/v1/auth/requirements`가 준 동의 목록 가운데 사용자가 동의한 것
	Consents []ConsentGrant `json:"consents"`

	// DisplayName 부를 이름. 비워 둘 수 있다. 앞뒤 공백을 떼고 40자까지 받는다
	DisplayName *string `json:"display_name,omitempty"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`

	// Timezone IANA 시간대 이름(예: `Asia/Seoul`). 브라우저의 `Intl.DateTimeFormat().resolvedOptions().timeZone` 값을 보낸다.
	// 하루의 경계와 알림 시각이 이 값으로 계산된다. 보내지 않으면 `Asia/Seoul`이다.
	Timezone *string `json:"timezone,omitempty"`
}

// Timestamp UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
//
// Example: 2026-09-20T12:00:00.000Z
type Timestamp = UTCTime

// User defines model for User.
type User struct {
	// CreatedAt UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
	//
	// Example: 2026-09-20T12:00:00.000Z
	CreatedAt Timestamp `json:"created_at"`

	// DisplayName 부를 이름. 정하지 않았으면 null이다
	DisplayName *string            `json:"display_name"`
	Email       string             `json:"email"`
	ID          openapi_types.UUID `json:"id"`

	// IsDemo 둘러보기용으로 만들어진 계정인지
	IsDemo bool `json:"is_demo"`

	// Timezone IANA 시간대 이름
	//
	// Example: Asia/Seoul
	Timezone string `json:"timezone"`
}

// WsAIText AI의 말 하나. 한 번에 통째로 온다
type WsAIText struct {
	// Origin `model`, `fixed`, `template` 가운데 하나다
	Origin WsOrigin     `json:"origin"`
	Seq    int          `json:"seq"`
	Text   string       `json:"text"`
	Type   WsAITextType `json:"type"`
}

// WsAITextType defines model for WsAIText.Type.
type WsAITextType string

// WsClientMessage 클라이언트가 대화 채널로 보내는 메시지. `type`으로 가린다
type WsClientMessage struct {
	union json.RawMessage
}

// WsDiaryReady 일기 초안이 준비됐다. `GET /api/v1/diaries/{date}`로 읽는다
type WsDiaryReady struct {
	// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	RecordDate RecordDate       `json:"record_date"`
	Type       WsDiaryReadyType `json:"type"`
}

// WsDiaryReadyType defines model for WsDiaryReady.Type.
type WsDiaryReadyType string

// WsEnd 끝내기 버튼을 눌렀다. 서버는 `ended`로 답한다
type WsEnd struct {
	Type WsEndType `json:"type"`
}

// WsEndType defines model for WsEnd.Type.
type WsEndType string

// WsEndReason `user` 끝내기 버튼을 눌렀다. `idle` 한동안 말이 없어 서버가 닫았다.
type WsEndReason string

// WsEnded 대화가 끝났다. 이 연결로는 더 보낼 수 없다. 다시 이야기하려면 새로 연결해 `start`를 보낸다
type WsEnded struct {
	// DiaryExpected 일기 초안을 만들고 있으면 참이다. 준비되면 `diary_ready`가 온다.
	// 거짓이면 초안은 만들어지지 않는다. 사용자가 한 말이 없었거나, 초안을 자동으로 만들지 않는 대화였다.
	DiaryExpected bool `json:"diary_expected"`

	// Reason `user` 끝내기 버튼을 눌렀다. `idle` 한동안 말이 없어 서버가 닫았다.
	Reason WsEndReason `json:"reason"`

	// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	RecordDate RecordDate  `json:"record_date"`
	Type       WsEndedType `json:"type"`
}

// WsEndedType defines model for WsEnded.Type.
type WsEndedType string

// WsError 요청을 처리하지 못했다. 사용자가 쓴 글은 담지 않는다
type WsError struct {
	// ClientMessageID 어느 글을 처리하다 난 오류인지. 글과 상관없는 오류에는 없다
	ClientMessageID *openapi_types.UUID `json:"client_message_id,omitempty"`

	// Code `invalid_message` JSON이 아니거나, 모르는 `type`이거나, 모양이 틀렸다.
	// `message_too_large` 메시지가 너무 크다.
	// `rate_limited` 너무 자주 보냈다. 잠시 뒤에 같은 `client_message_id`로 다시 보낸다.
	// `not_started` `start`보다 먼저 다른 메시지를 보냈다.
	// `already_started` `start`를 두 번 보냈다.
	// `unsupported_mode` 지금은 받지 않는 대화 방식이다.
	// `conversation_ended` 이미 끝난 대화다. 새로 연결해 `start`를 보낸다.
	// `internal_error` 서버 쪽 문제다. 글은 저장되지 않았을 수 있다. 같은 `client_message_id`로 다시 보내도 된다.
	Code WsErrorCode `json:"code"`
	Type WsErrorType `json:"type"`
}

// WsErrorType defines model for WsError.Type.
type WsErrorType string

// WsErrorCode `invalid_message` JSON이 아니거나, 모르는 `type`이거나, 모양이 틀렸다.
// `message_too_large` 메시지가 너무 크다.
// `rate_limited` 너무 자주 보냈다. 잠시 뒤에 같은 `client_message_id`로 다시 보낸다.
// `not_started` `start`보다 먼저 다른 메시지를 보냈다.
// `already_started` `start`를 두 번 보냈다.
// `unsupported_mode` 지금은 받지 않는 대화 방식이다.
// `conversation_ended` 이미 끝난 대화다. 새로 연결해 `start`를 보낸다.
// `internal_error` 서버 쪽 문제다. 글은 저장되지 않았을 수 있다. 같은 `client_message_id`로 다시 보내도 된다.
type WsErrorCode string

// WsOrigin 말을 만든 쪽. `user` 사용자, `model` 대화 AI, `fixed` 미리 써 둔 문구,
// `template` 사용자의 표현을 넣어 만든 고정 문형.
type WsOrigin string

// WsReady `start`의 답. 이 메시지를 받은 뒤에 글을 보낼 수 있다
type WsReady struct {
	ConversationID openapi_types.UUID `json:"conversation_id"`

	// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	RecordDate RecordDate `json:"record_date"`

	// ResourcesPinned 이 대화에서 도움 자원을 화면에 고정해 두었는지. 참이면 곧이어 `resources`가 온다
	ResourcesPinned bool `json:"resources_pinned"`

	// Resumed 열려 있던 대화를 이어가는 것이면 참이다. 거짓이면 새 대화이고 곧이어 첫 안부가 `ai_text`로 온다
	Resumed bool        `json:"resumed"`
	Type    WsReadyType `json:"type"`

	// Utterances 이어가는 대화의 지난 발화. 순번대로다. 새 대화면 비어 있다
	Utterances []WsUtterance `json:"utterances"`
}

// WsReadyType defines model for WsReady.Type.
type WsReadyType string

// WsResources 화면에 고정해 둘 도움 자원. 받은 뒤로는 대화가 끝날 때까지 고정해 둔다
type WsResources struct {
	// Items 급한 곳이 앞에 온다
	Items []Resource      `json:"items"`
	Type  WsResourcesType `json:"type"`
}

// WsResourcesType defines model for WsResources.Type.
type WsResourcesType string

// WsServerMessage 서버가 대화 채널로 보내는 메시지. `type`으로 가린다
type WsServerMessage struct {
	union json.RawMessage
}

// WsSpeaker 누가 한 말인지
type WsSpeaker string

// WsStart 대화를 시작한다. 연결마다 한 번 보낸다. 열린 대화가 있으면 새로 만들지 않고 그 대화를 이어간다.
// 기록 날짜가 지나도록 열려 있던 대화는 서버가 먼저 끝내고 새 대화를 연다.
type WsStart struct {
	// Mode 대화 방식. 지금은 `chat`만 받는다. 다른 값에는 `error`(`unsupported_mode`)가 온다
	Mode ConversationMode `json:"mode"`
	Type WsStartType      `json:"type"`
}

// WsStartType defines model for WsStart.Type.
type WsStartType string

// WsThinking 글을 받아 저장했고 답을 준비하고 있다. 받았다는 확인이기도 하다.
// 이 메시지가 오지 않으면 같은 `client_message_id`로 다시 보낸다.
type WsThinking struct {
	// ClientMessageID 어느 글에 대한 것인지
	ClientMessageID openapi_types.UUID `json:"client_message_id"`

	// Seq 그 글에 붙은 순번
	Seq  int            `json:"seq"`
	Type WsThinkingType `json:"type"`
}

// WsThinkingType defines model for WsThinking.Type.
type WsThinkingType string

// WsUserText 사용자가 쓴 글 하나
type WsUserText struct {
	// ClientMessageID 클라이언트가 글마다 새로 만드는 식별자(`crypto.randomUUID()`).
	// `thinking`을 받지 못해 다시 보낼 때는 같은 값을 쓴다. 같은 값의 글은 한 번만 저장된다.
	ClientMessageID openapi_types.UUID `json:"client_message_id"`

	// Text 앞뒤 공백을 뗀 글. 공백만 있는 글은 보내지 않는다
	Text string         `json:"text"`
	Type WsUserTextType `json:"type"`
}

// WsUserTextType defines model for WsUserText.Type.
type WsUserTextType string

// WsUtterance 지난 발화 하나. 이어가는 대화의 `ready`에 담겨 온다
type WsUtterance struct {
	// ClientMessageID 사용자의 글이면 보낼 때 붙인 식별자다. 아직 답을 받지 못한 글과 견주는 데 쓴다. AI의 말이면 null이다
	ClientMessageID *openapi_types.UUID `json:"client_message_id"`

	// CreatedAt UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
	//
	// Example: 2026-09-20T12:00:00.000Z
	CreatedAt Timestamp `json:"created_at"`

	// Origin 말을 만든 쪽. `user` 사용자, `model` 대화 AI, `fixed` 미리 써 둔 문구,
	// `template` 사용자의 표현을 넣어 만든 고정 문형.
	Origin WsOrigin `json:"origin"`

	// Seq 대화 안에서의 순번. 0부터 하나씩 는다. 화면은 이 순서대로 보여준다
	Seq int `json:"seq"`

	// Speaker 누가 한 말인지
	Speaker WsSpeaker `json:"speaker"`
	Text    string    `json:"text"`
}

// BadRequest RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type BadRequest = Problem

// CrossOriginRejected RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type CrossOriginRejected = Problem

// NotFound RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type NotFound = Problem

// RateLimited RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type RateLimited = Problem

// Unauthenticated RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type Unauthenticated = Problem

// Unprocessable RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type Unprocessable = Problem

// ListDiariesParams defines parameters for ListDiaries.
type ListDiariesParams struct {
	// Month 보고 싶은 달. `YYYY-MM` 꼴이다
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// Q 검색어
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// PutDiaryJSONRequestBody defines body for PutDiary for application/json ContentType.
type PutDiaryJSONRequestBody = DiaryUpdate

// AsWsStart returns the union data inside the WsClientMessage as a WsStart
func (t WsClientMessage) AsWsStart() (WsStart, error) {
	var body WsStart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsStart overwrites any union data inside the WsClientMessage as the provided WsStart
func (t *WsClientMessage) FromWsStart(v WsStart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"start"}`))
	t.union = b
	return err
}

// MergeWsStart performs a merge with any union data inside the WsClientMessage, using the provided WsStart
func (t *WsClientMessage) MergeWsStart(v WsStart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"start"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsUserText returns the union data inside the WsClientMessage as a WsUserText
func (t WsClientMessage) AsWsUserText() (WsUserText, error) {
	var body WsUserText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsUserText overwrites any union data inside the WsClientMessage as the provided WsUserText
func (t *WsClientMessage) FromWsUserText(v WsUserText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"user_text"}`))
	t.union = b
	return err
}

// MergeWsUserText performs a merge with any union data inside the WsClientMessage, using the provided WsUserText
func (t *WsClientMessage) MergeWsUserText(v WsUserText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"user_text"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsEnd returns the union data inside the WsClientMessage as a WsEnd
func (t WsClientMessage) AsWsEnd() (WsEnd, error) {
	var body WsEnd
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsEnd overwrites any union data inside the WsClientMessage as the provided WsEnd
func (t *WsClientMessage) FromWsEnd(v WsEnd) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"end"}`))
	t.union = b
	return err
}

// MergeWsEnd performs a merge with any union data inside the WsClientMessage, using the provided WsEnd
func (t *WsClientMessage) MergeWsEnd(v WsEnd) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"end"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WsClientMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t WsClientMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "end":
		return t.AsWsEnd()
	case "start":
		return t.AsWsStart()
	case "user_text":
		return t.AsWsUserText()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t WsClientMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WsClientMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsWsReady returns the union data inside the WsServerMessage as a WsReady
func (t WsServerMessage) AsWsReady() (WsReady, error) {
	var body WsReady
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsReady overwrites any union data inside the WsServerMessage as the provided WsReady
func (t *WsServerMessage) FromWsReady(v WsReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ready"}`))
	t.union = b
	return err
}

// MergeWsReady performs a merge with any union data inside the WsServerMessage, using the provided WsReady
func (t *WsServerMessage) MergeWsReady(v WsReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ready"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsThinking returns the union data inside the WsServerMessage as a WsThinking
func (t WsServerMessage) AsWsThinking() (WsThinking, error) {
	var body WsThinking
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsThinking overwrites any union data inside the WsServerMessage as the provided WsThinking
func (t *WsServerMessage) FromWsThinking(v WsThinking) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"thinking"}`))
	t.union = b
	return err
}

// MergeWsThinking performs a merge with any union data inside the WsServerMessage, using the provided WsThinking
func (t *WsServerMessage) MergeWsThinking(v WsThinking) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"thinking"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsAIText returns the union data inside the WsServerMessage as a WsAIText
func (t WsServerMessage) AsWsAIText() (WsAIText, error) {
	var body WsAIText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsAIText overwrites any union data inside the WsServerMessage as the provided WsAIText
func (t *WsServerMessage) FromWsAIText(v WsAIText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ai_text"}`))
	t.union = b
	return err
}

// MergeWsAIText performs a merge with any union data inside the WsServerMessage, using the provided WsAIText
func (t *WsServerMessage) MergeWsAIText(v WsAIText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ai_text"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsResources returns the union data inside the WsServerMessage as a WsResources
func (t WsServerMessage) AsWsResources() (WsResources, error) {
	var body WsResources
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsResources overwrites any union data inside the WsServerMessage as the provided WsResources
func (t *WsServerMessage) FromWsResources(v WsResources) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"resources"}`))
	t.union = b
	return err
}

// MergeWsResources performs a merge with any union data inside the WsServerMessage, using the provided WsResources
func (t *WsServerMessage) MergeWsResources(v WsResources) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"resources"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsEnded returns the union data inside the WsServerMessage as a WsEnded
func (t WsServerMessage) AsWsEnded() (WsEnded, error) {
	var body WsEnded
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsEnded overwrites any union data inside the WsServerMessage as the provided WsEnded
func (t *WsServerMessage) FromWsEnded(v WsEnded) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ended"}`))
	t.union = b
	return err
}

// MergeWsEnded performs a merge with any union data inside the WsServerMessage, using the provided WsEnded
func (t *WsServerMessage) MergeWsEnded(v WsEnded) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ended"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsDiaryReady returns the union data inside the WsServerMessage as a WsDiaryReady
func (t WsServerMessage) AsWsDiaryReady() (WsDiaryReady, error) {
	var body WsDiaryReady
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsDiaryReady overwrites any union data inside the WsServerMessage as the provided WsDiaryReady
func (t *WsServerMessage) FromWsDiaryReady(v WsDiaryReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"diary_ready"}`))
	t.union = b
	return err
}

// MergeWsDiaryReady performs a merge with any union data inside the WsServerMessage, using the provided WsDiaryReady
func (t *WsServerMessage) MergeWsDiaryReady(v WsDiaryReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"diary_ready"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsError returns the union data inside the WsServerMessage as a WsError
func (t WsServerMessage) AsWsError() (WsError, error) {
	var body WsError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsError overwrites any union data inside the WsServerMessage as the provided WsError
func (t *WsServerMessage) FromWsError(v WsError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"error"}`))
	t.union = b
	return err
}

// MergeWsError performs a merge with any union data inside the WsServerMessage, using the provided WsError
func (t *WsServerMessage) MergeWsError(v WsError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"error"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WsServerMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t WsServerMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai_text":
		return t.AsWsAIText()
	case "diary_ready":
		return t.AsWsDiaryReady()
	case "ended":
		return t.AsWsEnded()
	case "error":
		return t.AsWsError()
	case "ready":
		return t.AsWsReady()
	case "resources":
		return t.AsWsResources()
	case "thinking":
		return t.AsWsThinking()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t WsServerMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WsServerMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 로그인
	// (POST /api/v1/auth/login)
	Login(ctx *echo.Context) error
	// Logout 로그아웃
	// (POST /api/v1/auth/logout)
	Logout(ctx *echo.Context) error
	// GetAuthRequirements 가입 화면이 알아야 하는 규칙
	// (GET /api/v1/auth/requirements)
	GetAuthRequirements(ctx *echo.Context) error
	// Signup 가입
	// (POST /api/v1/auth/signup)
	Signup(ctx *echo.Context) error
	// DeleteDay 하루를 지운다
	// (DELETE /api/v1/days/{date})
	DeleteDay(ctx *echo.Context, date RecordDate) error
	// ListDiaries 한 달의 일기 목록, 또는 검색
	// (GET /api/v1/diaries)
	ListDiaries(ctx *echo.Context, params ListDiariesParams) error
	// GetDiary 하루의 일기
	// (GET /api/v1/diaries/{date})
	GetDiary(ctx *echo.Context, date RecordDate) error
	// PutDiary 일기를 고치고 확인한다
	// (PUT /api/v1/diaries/{date})
	PutDiary(ctx *echo.Context, date RecordDate) error
	// GetMe 로그인한 사용자와 설정
	// (GET /api/v1/me)
	GetMe(ctx *echo.Context) error
	// ListResources 도움이 필요할 때 연락할 수 있는 곳
	// (GET /api/v1/resources)
	ListResources(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetAuthRequirements converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthRequirements(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthRequirements(ctx)
	return err
}

// Signup converts echo context to params.
func (w *ServerInterfaceWrapper) Signup(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Signup(ctx)
	return err
}

// DeleteDay converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDay(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "date" -------------
	var date RecordDate

	err = runtime.BindStyledParameterWithOptions("simple", "date", ctx.Param("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDay(ctx, date)
	return err
}

// ListDiaries converts echo context to params.
func (w *ServerInterfaceWrapper) ListDiaries(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDiariesParams
	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", ctx.QueryParams(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDiaries(ctx, params)
	return err
}

// GetDiary converts echo context to params.
func (w *ServerInterfaceWrapper) GetDiary(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "date" -------------
	var date RecordDate

	err = runtime.BindStyledParameterWithOptions("simple", "date", ctx.Param("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDiary(ctx, date)
	return err
}

// PutDiary converts echo context to params.
func (w *ServerInterfaceWrapper) PutDiary(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "date" -------------
	var date RecordDate

	err = runtime.BindStyledParameterWithOptions("simple", "date", ctx.Param("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutDiary(ctx, date)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// ListResources converts echo context to params.
func (w *ServerInterfaceWrapper) ListResources(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListResources(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/v1/auth/requirements", wrapper.GetAuthRequirements, options.OperationMiddlewares["getAuthRequirements"]...)
	router.POST(options.BaseURL+"/api/v1/auth/signup", wrapper.Signup, options.OperationMiddlewares["signup"]...)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.GET(options.BaseURL+"/api/v1/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)
	router.GET(options.BaseURL+"/api/v1/diaries", wrapper.ListDiaries, options.OperationMiddlewares["listDiaries"]...)
	router.GET(options.BaseURL+"/api/v1/diaries/:date", wrapper.GetDiary, options.OperationMiddlewares["getDiary"]...)
	router.PUT(options.BaseURL+"/api/v1/diaries/:date", wrapper.PutDiary, options.OperationMiddlewares["putDiary"]...)
	router.DELETE(options.BaseURL+"/api/v1/days/:date", wrapper.DeleteDay, options.OperationMiddlewares["deleteDay"]...)
	router.GET(options.BaseURL+"/api/v1/resources", wrapper.ListResources, options.OperationMiddlewares["listResources"]...)

}

type BadRequestApplicationProblemPlusJSONResponse Problem

type CrossOriginRejectedApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ProblemApplicationProblemPlusJSONResponse Problem

type RateLimitedResponseHeaders struct {
	RetryAfter int
}
type RateLimitedApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers RateLimitedResponseHeaders
}

type UnauthenticatedApplicationProblemPlusJSONResponse Problem

type UnprocessableApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    AuthResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse Problem

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response Login403ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	RateLimitedApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogindefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response LogindefaultApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type Logout403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response Logout403ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response LogoutdefaultApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthRequirementsRequestObject struct {
}

type GetAuthRequirementsResponseObject interface {
	VisitGetAuthRequirementsResponse(w http.ResponseWriter) error
}

type GetAuthRequirements200JSONResponse AuthRequirements

func (response GetAuthRequirements200JSONResponse) VisitGetAuthRequirementsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthRequirementsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAuthRequirementsdefaultApplicationProblemPlusJSONResponse) VisitGetAuthRequirementsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup201ResponseHeaders struct {
	SetCookie string
}

type Signup201JSONResponse struct {
	Body    AuthResponse
	Headers Signup201ResponseHeaders
}

func (response Signup201JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Signup400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response Signup400ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Signup403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response Signup403ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Signup409ApplicationProblemPlusJSONResponse Problem

func (response Signup409ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Signup422ApplicationProblemPlusJSONResponse Problem

func (response Signup422ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Signup429ApplicationProblemPlusJSONResponse struct {
	RateLimitedApplicationProblemPlusJSONResponse
}

func (response Signup429ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type SignupdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SignupdefaultApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDayRequestObject struct {
	Date RecordDate `json:"date"`
}

type DeleteDayResponseObject interface {
	VisitDeleteDayResponse(w http.ResponseWriter) error
}

type DeleteDay204Response struct {
}

func (response DeleteDay204Response) VisitDeleteDayResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDay400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DeleteDay400ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDay401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response DeleteDay401ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDay403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response DeleteDay403ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDay404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteDay404ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDaydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteDaydefaultApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiariesRequestObject struct {
	Params ListDiariesParams
}

type ListDiariesResponseObject interface {
	VisitListDiariesResponse(w http.ResponseWriter) error
}

type ListDiaries200JSONResponse DiaryList

func (response ListDiaries200JSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiaries400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListDiaries400ApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiaries401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response ListDiaries401ApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiaries422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response ListDiaries422ApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiariesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListDiariesdefaultApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiaryRequestObject struct {
	Date RecordDate `json:"date"`
}

type GetDiaryResponseObject interface {
	VisitGetDiaryResponse(w http.ResponseWriter) error
}

type GetDiary200JSONResponse Diary

func (response GetDiary200JSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiary400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetDiary400ApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiary401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetDiary401ApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiary404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDiary404ApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiarydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetDiarydefaultApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiaryRequestObject struct {
	Date RecordDate `json:"date"`
	Body *PutDiaryJSONRequestBody
}

type PutDiaryResponseObject interface {
	VisitPutDiaryResponse(w http.ResponseWriter) error
}

type PutDiary200JSONResponse Diary

func (response PutDiary200JSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PutDiary400ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response PutDiary401ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response PutDiary403ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PutDiary404ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response PutDiary422ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiarydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PutDiarydefaultApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMedefaultApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListResourcesRequestObject struct {
}

type ListResourcesResponseObject interface {
	VisitListResourcesResponse(w http.ResponseWriter) error
}

type ListResources200JSONResponse ResourceList

func (response ListResources200JSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListResourcesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListResourcesdefaultApplicationProblemPlusJSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login 로그인
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout 로그아웃
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetAuthRequirements 가입 화면이 알아야 하는 규칙
	// (GET /api/v1/auth/requirements)
	GetAuthRequirements(ctx context.Context, request GetAuthRequirementsRequestObject) (GetAuthRequirementsResponseObject, error)
	// Signup 가입
	// (POST /api/v1/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)
	// DeleteDay 하루를 지운다
	// (DELETE /api/v1/days/{date})
	DeleteDay(ctx context.Context, request DeleteDayRequestObject) (DeleteDayResponseObject, error)
	// ListDiaries 한 달의 일기 목록, 또는 검색
	// (GET /api/v1/diaries)
	ListDiaries(ctx context.Context, request ListDiariesRequestObject) (ListDiariesResponseObject, error)
	// GetDiary 하루의 일기
	// (GET /api/v1/diaries/{date})
	GetDiary(ctx context.Context, request GetDiaryRequestObject) (GetDiaryResponseObject, error)
	// PutDiary 일기를 고치고 확인한다
	// (PUT /api/v1/diaries/{date})
	PutDiary(ctx context.Context, request PutDiaryRequestObject) (PutDiaryResponseObject, error)
	// GetMe 로그인한 사용자와 설정
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListResources 도움이 필요할 때 연락할 수 있는 곳
	// (GET /api/v1/resources)
	ListResources(ctx context.Context, request ListResourcesRequestObject) (ListResourcesResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuthRequirements operation middleware
func (sh *strictHandler) GetAuthRequirements(ctx *echo.Context) error {
	var request GetAuthRequirementsRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthRequirements(ctx.Request().Context(), request.(GetAuthRequirementsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthRequirements")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAuthRequirementsResponseObject); ok {
		return validResponse.VisitGetAuthRequirementsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Signup operation middleware
func (sh *strictHandler) Signup(ctx *echo.Context) error {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx.Request().Context(), request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		return validResponse.VisitSignupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteDay operation middleware
func (sh *strictHandler) DeleteDay(ctx *echo.Context, date RecordDate) error {
	var request DeleteDayRequestObject

	request.Date = date

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDay(ctx.Request().Context(), request.(DeleteDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDay")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteDayResponseObject); ok {
		return validResponse.VisitDeleteDayResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListDiaries operation middleware
func (sh *strictHandler) ListDiaries(ctx *echo.Context, params ListDiariesParams) error {
	var request ListDiariesRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListDiaries(ctx.Request().Context(), request.(ListDiariesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDiaries")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListDiariesResponseObject); ok {
		return validResponse.VisitListDiariesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDiary operation middleware
func (sh *strictHandler) GetDiary(ctx *echo.Context, date RecordDate) error {
	var request GetDiaryRequestObject

	request.Date = date

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDiary(ctx.Request().Context(), request.(GetDiaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDiary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDiaryResponseObject); ok {
		return validResponse.VisitGetDiaryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutDiary operation middleware
func (sh *strictHandler) PutDiary(ctx *echo.Context, date RecordDate) error {
	var request PutDiaryRequestObject

	request.Date = date

	var body PutDiaryJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutDiary(ctx.Request().Context(), request.(PutDiaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDiary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutDiaryResponseObject); ok {
		return validResponse.VisitPutDiaryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListResources operation middleware
func (sh *strictHandler) ListResources(ctx *echo.Context) error {
	var request ListResourcesRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListResources(ctx.Request().Context(), request.(ListResourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListResources")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListResourcesResponseObject); ok {
		return validResponse.VisitListResourcesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zH1tdxNHuuBfqaO5H+xZWcjGmR18z3zgkswNO8kkh5czm4tZdcdqsG6kliK1GbzB5wjTw2iQWORgYREk",
	"X2UR2DCeM4rdgNiYmf+yH1Wl/3BPPfXS1a1qSyYJcz8kB9vdXU899by/1VexpXyukLct2ynFFr6KLVtm",
	"2irCP89kLbNopc9bpVImb5/J57/IWPT3aau0VMwUnEzeji3EiNsnf2gi8vfOcL2LnxwislMm33i42p0y",
	"Pjavz5y+av0qaUwnYvFY0fpyJVO00rEFp7hixWOlpWUrZ9JPOqsFK7YQKznFjH01trYWjx1n1QQyPnSc",
	"wid2dvWf0XkzZ53PONavPjKv/zP61HSWf3XCIG1vcNCJI/KNR5o3yVaduC18ZxMZ562llaJlDHplhO9u",
	"IvzyIb6ziavdxKItoDfog2w90m4i0nHJvodIpYmf/4G0PfbwsXa3Fo8VzKKZsxyO6XPWUr6Yft90NDsd",
	"9Hv42zbC6x2y00og47PPPvts5uOPZ95/30CDQ49BEIvHMvThguksx+Ix28zRBdP0g0cB9k9F60psIfaz",
	"Ez4NnGB/LZ1QYAKIi1apkLdLFgD8L2b6nPXlilVy6E9LeduxbPinWShkM0smhf1EoZj/PGvl/tu/l+hG",
	"vppw3U/ZW2zR0KF/s0n2/0LaHqL/UfS7ffKwjPDONtkpI9K4ww4PTRnXzGwmDWCkrpiZrJU2pmNr8diZ",
	"Yr5U+qSYuZqxz1n/bi05FCvvbgO42sVP+oi8bJF9IKbh/2mStkd2ykCABx5e7yO5S7aTJQpyKg8wp4oc",
	"aLab3+adX+dX7He6hcGrPqdFslVHpPc3yh2MRuFgtm4zsO28k7pCgWOgii++a0h7D4Bnm138pJlA+KCP",
	"9/r0N8ZSPm0Z+NsWGrzYwy/dYaNF2WgtHjtnOtZHmVzmXZOGW8F7HiLbdfL4EJFqC99zhw8qDJlF07FS",
	"WQaUMR2Lq1L6nOUUV2dOX3Gs4qjwwNUuqbbE5xrNQb83eF2jzEKPrNrFTz1EvMqRQiKXsTO5lVxsYTYu",
	"JFnGdqyrVpHuYy0eu2ibK86yZTsUOe8Ya9+2Bq/6pN0fNppcBJBGc/BdD683pcz2EL7Zxut7DJcrQWgZ",
	"eV60C8X8klUqmZ9nrXdKpL2vKTmCIBeCDO/UEO49Im2XahlgKcpj9EkvUrolkHElY2XTJQP48oGH79TR",
	"sOHi+y3S7lPc4Ko36IOyoGBw2Cjop1ec5XPs+HPCDCgU8wWr6GSYuF+igp//JQx/mWz/gS45bLjkm81h",
	"o4XwvYek3aSCmbIgFW79ChrW6gmEn+/iDfZopcnVlmPlSuMQeIat/69F03bocXEyNItFc5X+nM6UCllz",
	"NUX1XipnXk9lLfuqs6zhh5dlMFHaHn7qgmR40cI1yg1lsl2n6I7FY9Z1M1egZDCfHKV4qrpLpd/ni+mx",
	"p86fC6CWaVLBapf8j8V9JEfv57KEJ/85VQQUHHZ6TDePntxKiYmFowC9WAJWDgIGL+rWC5wFZY90OkOx",
	"a2Y/VVa+YmZLVjwEzBcZOz3hUf+GProWj12ziqUM47WQLbC+R755RrbrXHMODjqc8IAE9/rEbYGGrdXV",
	"I43NJed+MZM8NTOXjMVjOfP6R5xSTs7FqaQTP/qyTrFJVfzAXnz4jsDUb/iuQ5TImISS4P/9A1VOi7bh",
	"WMVcyaDUSbfWeDPwynFkFIqZa+bSqoEGPWDlTgMfeIjsN/HTPdx7Rl7vxpFRsuxSxslcs1Jp0zENhHcq",
	"pF2jfDnwyhQjQkU3+ZvxRdvIU+gts5RyiqZdumIVDYRr5eHDTYTXAQSq0B/28csyOn0WUZP5tUvudKnW",
	"pFbw7W9xvUkeeGjY8MjDPrOqBWD1Jgit/VvMOLZsqkEuxWCLMUoYsKlYPBaEPBaPjUClIFcchkSuYlcE",
	"8WtwdkqJQzNI+xDhRo1KV7JdYdInSJ+5TKlEPz/yMSnb8N0eNSaEqqEiG87xmIJMUHdYjuVXnLRQoSFy",
	"f7jJNYMvT+F4Gi6u1jgUCcTEMRq8apHXD6kC4QYAVScNF5FbFc4aVAriA49s7ZFukzQOETeAfox9hDhF",
	"YFXZXgS30IMHrfZxPq3xhBhtgvyutsj2xrDRoQcK+rPfwwfU3HtGqm2F3K7lM0vUBVpaNh0tGb2fMYur",
	"WoV3JVPMWemUyYRcNvvJldjCpaOxciGTs0qOmSvE1i6PWCo7FTjAP5HWIWWg4cMGmC1gnA16NxMI5NZ+",
	"Bd9z5R8Vm4a+9sxD9ko2K10++gMzWKjNRvUg9yAn9evisZJjOitjjxuwdJ49So/buu5oSPTWzeGtFhXH",
	"RrpoXnEMCi/xKqRRiVN7m2MUfu3vnmpe4USzh4Fsd2r4PrAZfv49IGa9Q7bqVKTg1xUkHvQQae7Sd1FA",
	"HZCdm6SzgcjdXSqQJDLpwrjekg77CDGsFIA8+ZlPeNIhauc+N8crx1U8SFCBlXS8APj+KMO86yBlSvac",
	"iE/Zwa3kcpTKxzEq+2IkPOclqYQkLTttrjq4FoAD7PgHRdVz8IwaLtm5qaN0OE+FXoLv8RfAMwqqFgBD",
	"RXU0wwuMjGD3+Ax0JVMsOalsxtYFqbiofriJn3lUF1OJ2z5kNE8V8Z8R6boJNOj3gVe2m7h9CDq0WwYs",
	"BGgdyPc1E+DbdbLlh35GNlmyM4WCpeHRwX6Z3PoTeeCB1bTeJM1d6nLip3sAUGMbf92l4CUQexIN9nuD",
	"g0PKeqraHF3w+GJkDN8oeI2kyIsFcV7HMEIjhFf7cNDv0a3zAF/QOpxNJpPJ4xmIsI4O9I/yEH2S0bNj",
	"wG7lzEwWLBXVcB0HWNBlCexqbv54m2IAKB/UbfBjjR9SshwnY18dSyLn+XOKzPphLkzcX1oHq++kmSWd",
	"m4Ffu7hXxvuVYbMPNlPvkR9qBEu91QHTPZ9PlZbzRSoHeSRnZwdXu3EEf8rm7avyL5Td5V+W8rlc3jYQ",
	"rriDF3t4vYnw7iHplBF2H1PbGh94dKVhm7nWKjjVLjXic6aztGyVUnA04DzgZ5tUypDHh+R2jX4R3PDG",
	"NnV+X7qDg0M06D1kEGRsCCWkLHspn85QGJknDCZ++00oBIF7m6TtDe/0QYBvj4pgiQUqI/i2+T/ZPoGr",
	"FHghbh0EQSu1tb70CJFRT/nzVcfSKCnp5/dJ20ugixd+PfNLfz+wXfcQV7tTw0aLCgFhmmyDzXFSPjmt",
	"OpOzc7/UBQhyGTsyAEFetMjtmoTDjzv4IARW0EQgRsxruVpcwYCW2KOcpXO/PoNOzb/33/1YqQiVbtV5",
	"qJQ8LCOjyKRWKpM2gBnuAlEO9m+NuFJL3IKfICx2hj66Fg8EmSbwPWRQjeoKK5vWHPr83BzSxMp0juBE",
	"1hRf8td0OZ37VgQhojORfm+ZX6SE0PwBAASllRYEcUI6HefJ5EITnX0/gUh7A1dfQDz8f85wlTRzNm2g",
	"4VYX392EEB6IigRicXPuciHSqOFOlzwGn4S6k/su4rFYHgXo/U0KjwmshiCgH1648Cli7gQibzbx/RaH",
	"hDrcg97XgRjd3JyOB52Mk9Ul03ot3GsJE7T9BoT4zg79LmneBHm71x+82FMcCrJVH+zXhLP8+DCQaQqE",
	"lsTpoHTeKiE776CcZTnIWbZQIZ/NQLRjBAfsFyNHxZiQhYYoqw16Zfx0b7jepRBfPHcWkV6ffNtLIEPE",
	"pEsnvqJMtxbMCvrQ+c8FiDE21o6hfxUIVQw04PAAwR0hcs5oHXq2SyUGxoLcZSqYcbkWwHRCmNH0qNoe",
	"PMk8adKo4HVxcICrgw5+0uf7F4GAsBRQNM9S0UpbtpMxs3RfofwA3akuA0dN1Hzx80w6bVGtJtNdVAhb",
	"znI+naK/MrPZ/O/hYVB3Kcf8Ah4vmKvZvJlOgZI0i1ctWLi0Uijki9QvzFnpjJniqA+fVziyRU9BSRDB",
	"zhyraJvZlFUs5pkNVLyWWbJSK7Z5zcywoIFWz6oSbtQYikhKIHD1QLLIlEOTB9kTiPz9ED/dQ3inS7nv",
	"oEwqTSEA6ReobcLD8V7wzISFoEbDgRJz1v/O25bvXH+p3csxkuq4uoc7T/iP3DvF1QpuH8YVQUD3VG0N",
	"ei6ulYHwblXw/hs0T6qQC2VEC8Zao4kf7/KYBghH+GanMWx4IByl9FTzOglEHr0mje9ATENMSMhSFs4Y",
	"HLhkvee7yrJQITq+fSVfzJmOXwmgwVEpv1Jc0hjsAXyNMO6DPum04pBmetBF+J5LHpUhbqNQyHYF39kk",
	"O2XATQ2C0MNGC2/UmQf7JAj2PENtXMQ3KTbBCPVIg7pmYG/c75IHHum69FDwdo2asmSrN9jv4XuH5JvN",
	"hG6LWk24XSeP6hTSgFwdHHRIp4HrLUm7QuZAoJXC8qYJb1EJ4/E0I37+DCLrLhrs71HgQEHeHxHApZXM",
	"UiZtpQpF6xoVL3k7NZs8pQOZlW98pbxLAV73SLOCe8/IrZu46pGOO3y4qXu7sJzXBiPgBeY6JJSYxOBV",
	"n9OzVHFQKjP4ri94lFT+TA3hnRrC67uD/V1kOFZ2ARKN2H2s0YTafYWjTWlRqCJADoZMddpEkOuY0FiY",
	"1/8EVurBATvHbUiQQtxwUrtLssnbh9DCju0I9KZtZldLmVLKsql41onfmy7EgFic7SHVg8AZ/Fz6PciB",
	"QeIHkWpHeKxvNsImCwfu83w+a5lgRqatK+ZK1knlJjDbRwL11OWxcvniqgr66Bq5fD6dKmSWvjj6saKV",
	"y9hpqzjhU1QbaIi9UcNPD2VoXcpwX4BTaY7339CfD1whb1mc0vjww4WPP46yo+aSC8kkqHCHKtnYQux/",
	"TV1Kzl6+lJw5dfnG3KXkzMnL0wuXkjPvsV/901hOGNlxeHuh84mP0srICejQrSXLzFV7pfB20ajoqgDj",
	"Xz+4gE6YhcyJa7MnqDl1oqg47lBtR7oid8YFKOSuvvEgwxbI7cqkLvMz36pgIGdeP8vem/3F0eUDY2oG",
	"Egi/dsmjGsIbTcW7ScjY6cEL3PsOVOEDKkfRfJLug9Xc4N4jyYNKGO6XSY0Uf/ehPsWyGsHB2dO/Pe3z",
	"DsfFFGlWFpBxupQxT5y38itZYzqBcL+G24fkmx7pAI8ZZ20nm6BW2IVMzvo1GCRT04miVcpnr1npT2CF",
	"0tR0gi7+b3nbMphF5PJyOGbiMIsKMn37b6ghRKWfyuOiKNB3C5i5xPM97GOeSDKwXJoKuVrIqaDtF/PH",
	"jogqgQwdw/mZoxEkX7xwRkosDHYJ8SqIuH0eoheVW9JKiRJQwgK8MDu3kKTiKpFMJv8tbA/OcNkS3F88",
	"dn3man6G//LihTMUYCiR4mHYkAwoWsdPmR2T48BwPlYq9Ch+ijAQJWpWVjJprR1ZSqWtXF4D7UYT/8ce",
	"PvAG/R4VW4z8eAbzgUd2XKDFToPVYWn17zE5L3DePhVPZnONd6vEVuPq8eqI+Xel02cvaPMpp8+CZN+p",
	"gzO03pTpbSgVu/2C7LCgqzDDglTFfO3JE++/4zW9mry7QVVm1ogj40rmupWm/3CsXCFrOiBphMphUPIS",
	"0JL1ZaDwUVsGJvJIkREd4caamVQoF3R0pIWuLl1bjgk98s9kM5btfGyVSuZVDekMb3pUFLc98qDPg/a8",
	"vId852K3zm1+vA4ZBvxskzqyO+UEMuhahpCjVBL12CmlM/T7uYxtOvki0zCFAq+Ysex09PF8AIGRkmMW",
	"neiHzsOfWcKHoSzyUSqMgPDWJOms/pYVvQOe1uKxvG1NRDls1bX4uOeUJcc9Sne7dhmOCPKU5ywzvRqZ",
	"c1SKGbpl/NrF9TpLgatGVDpjFjNW6cRXVHKvGTw/I62JIPsUIfKROn4yO0y6dNXVVBHAn5R81cX1ZPsB",
	"q4c70tIMez5tvE7lK8L77vDOIZgHlRrusDQ5i7FAP4dlp600oAdXX8iaplAGOLRLSrmT7S5yP1HpQ4PS",
	"soHGwG9k0lnLgOjIvYekUaFykxfTkwcivg7sW/0zL5AIpN14opN+RRsJAxC1HiWIA/iyqJBOILYyRFW+",
	"hSYZaIyhcuJQhv7ApOK15SJCQ0VopwsJgVsVIFD4yLDhIQM43+BFZ8yqGzkWRmzW9YJsyziSXUSREFSW",
	"bFe4UUB6fRlN49wEdT+GQsrM/2jyAN3gux7Zuc/rK8THy6r+LocC0cF6FKrW/OPaqrCoUFyBk1pv9x4G",
	"7QI/h8zd+WY5XJcU8HYFeY0VPH5q6EeTAsBTx+B/ACC4fjx8uhGcBOHq0ZPnSSuXF5dyaxA//57XAYVK",
	"i+57rMQGat7DwY+Q/QoqNJVjOlSfNmO19PBFBQJc7SK83kIiidEH1TnolyEqeevmwCvzIDl/gpWvMe5R",
	"bfEog3OSFCpHmUihjpwc4HPSk4MFjzgYfRJH1hBwHBrof5z/5LeyNlXyA36+i5+ApcHNi7an/Ik82KCv",
	"DKtl3OE+nyEORSZJDN9IAZnFyimGN/f4C4E2GRTsqKFy5xYnlu0O1MR+3YX4J0srGiOUwLUIq59VfFFo",
	"bQKBRlcRou0AWjNE7Qbr85LQCsF3i5dMGGYWJNHoZ+iDG3VqKAdfCCSH8mnL4HFyli17NCJPeCmsdGuN",
	"JSVql2JaEpyJv/aZ7G/xFxmGJhHg9KvBRJMhUsHk+RsI8neY882ZkXTKZPsJrquuXCBHnDjGYXj4nhuo",
	"5hQ0HyJHCI2F6Gg0YaYcaSweC51OODfHYnCjCB1NvOmV8SfSuwmXCNelWutQHCYQtx+keIsj7s+IYz59",
	"Vno2CP+1j5/uIXJ3F+GNTZ4QjUNfgXB4Asms4UZr2HRhSV5rxFZmAQb6/rDZ0FoaAAMU6V2HbYsFIjYc",
	"Yf9yogJHsfqCGR5Bluk9AvrmjMoEsGqJ6Mv4AyczoXf/1sqyyFMDpVQhY9tWRNlFsDYW0mXIT0IpyRhA",
	"PeU4vFEnWzyDlhBmzTMPDQ52wKPzkCGXVgyaCPOhtJLTgrbl4U4X8Hi3iZT6eliBen6sh0NYR75xFbSa",
	"blXEDlkE3QcSalwbFfwSJLbBfWEj4PtrwiEhPRblgcRjK45jFU17SVvzpe5CwNekghPEXa81fLiZQKTS",
	"wvsVlgITwk+gAipuXdjHsep0fle6KOAamzKSyjdItGH7SZxhYMsa8tPrb5HA0mBJT3zNIJUmFF4UXkHQ",
	"d4C6oECEkn1Ia3X9IzJ1OqoSSJnUQopO7/2udN4qXrOKkcEYxYn76WIwItQUSZY8XBcPePaRTyvBizj3",
	"Ao5yPVidCzPhjzRXmZdw1MpiUf+IjnhUPBKPOcsZ+wvARdTTF8QTPzxwxGAcHw1Slhz3KD+e8Q/6m54o",
	"GmWlJ3hOOe0JPgrnyINc5wuW+YW2/bziBnxkHv8OWRNmJsJuYKG5Y4aKRprEuFRnEY0d6KjnsWjFlkVU",
	"FT7tKVJNiSkwazjguYOWe9XX6EyXhxXUCiPWlFTG6018z6W/1ipeGDMipQT3JFjk6KCjqqUnUPYiLd9Q",
	"ETT30iaLnI8m8y/rMcodioTidxhLy6Zj8G51ERzhrs+g9zV3eA3mGkyNujDTitmiEc8sWjypaM5FO6+S",
	"ATUKR1YtNVzunwwfVKCOovoCnBMIIg0bTR5mYnukzzfpTu9s8oYkavj0e9C7JwJ0AXOWbbUbTEAe2/X8",
	"geELvxALbDrOjWNtY54OGZ2uIb75ErbBDKlYfFzeJHTMUmZPHKYY2TMDUX/4Mmx/PDGiCyjxJNHbHIIm",
	"FTPol7k0UuULmFak2sYHLtmuTxlLxdWCk08UTTudz128ePb9qWljGhpOONoMQcCiV9ILEI5fZymrp4Gs",
	"73uqvy2mUDA/XTSi7tSky+672WOpJaK/aqQ8YqvMG83gV6IWHobJsNCdmrHXlU3MjW/JGqU2P7f0Q8gt",
	"srdLNfx17YC+4yHzohFeisFC1cBfVW+wvxuVK51EBKheP2+4feYpBMJYuO8THi9pgRZNLglVGmuJOOdg",
	"f4+XsULdDqcqmfzlCwUy9WECGpu5f8sSAz+HPFnmOELOCWu9UWHeO3iQIOkSKIlfloeuSB6TzWdIX6tO",
	"Ki2q2ANVltDhOVZYlnzLakwWkz8YnZgOUTfLMovvS3T5Dcsasj+yGgAQuLRSzDir5ylYou/vyDFucn4P",
	"60qD4QWiKcVDpLrnz14TE+Z4igoKxssI93rDe3uIuF0osHAR3uyx4v/Eov3hhQufnqfu6k5NcbLYs1Ns",
	"FNy0PwuOfVS4nUYq9WG+5Myw0XDKWDgxam2JbUkOW7NNK5NN8f36gtEsZH5jrbLRPxn7iq5+ZB2agpXi",
	"7/s9Cs+5D85fQKc/PctMjue7EJrbf8Pdb4Nnhg0Is283wVUWLXmL9s9+hqiCf9petNUZSX67Dui1kdF9",
	"gHCGYvZLupKYrWeI7uQ73eHNPfz0jeicCzQKQvGwWgUGK0EGR+i7Ro2KFjdo24j9l9Hwdmd4swefZJXv",
	"1NJ6vBvKwnHVxWep8cjayzJ+4uG/AqMZVyxnadlQx0Pce0i2N/BOTXSOwB4BvmqXOdgCecFJbbwOv7nL",
	"N7Jos+4kFqTcHPytDwQEf5v69JPzF+Lo04v0f6cvnPkwjt7/4KMPLnwwzTStCjWVkgqm/NFvorQ8jEY2",
	"7SNkTYBIEm+SB54/ziOxaB9r5FwZGfPJk0g/cg4CEd/1qMzjPhXlNYrGald0qq4fytMri0Qxx6jg7q09",
	"Ud6ldkEwpleIlctO1svKKvvo+3zijGwu8L8STtLyBhVeeeVR7hlWy+DjqU20lKm4GT6fnEWaniBDBDW/",
	"6+OnTCCxcqx7ruiOW7T5HCyquOeTp5DS7UMdJDh53ugiN8SzLyP7Ym4F1dnVLjAB2yEfCUAatcFBB4h9",
	"Q8ZmFRDEnAvWPiHRCU0NckAHm86D7/biiMGjTiSBwT2kUyG9XaA53vsLlQliBsdGnYoi8k2P9aYxmmZy",
	"m6e57zGgqd3wDO83/NmA3DPikowFt4KEIQCRzc+wSxfhO0/Jy035i7LocD5wxTeggsKdMubnTqHgzDz8",
	"97pEFO+Plo4bIrfaVEI8E0QGikVuUUwtC26TwnNPEDBz6qEBqK5KYEj8Ltqim4+/WRZfNKJGyxlToiN3",
	"WgTcfYuCjy5kqThwSyMb4MBRyDhZy2CyZ7Lmx/C4jiM7IBOa7XFxEjBdZVVvvcnwpjPwAXE3ROvnDUR3",
	"im4g3Poe3Vi0b8zMzMj/6HPzySS6oevwRTfQ5LNC/cQ0612LCzkxvEWJIc6btRHxKoODwzgavN4lOy5k",
	"uacRh2OWwqGTHRQShelBqCviB6JjMuctxvaR52+Ydw4npBVwgYXDIw0pyo47GJF/7yT9nl7+068ee36p",
	"+lnZLxkAEDT+gwqfbjVsdNT+Qo41/0Pz9EP+bFGKXi7oQZ4oRQUTDSpNILy+KyyEb9tUpMvv3aI2KW5u",
	"AN97fj2ZAOU9CsporyeFCYIjABDgJZiff7ZJLbD76qdO0U+pOoOTjaIeWkE6ku/OAmpH+kkBxXzaqRes",
	"lBAvvsdIR9d0Gnw7IKZAPPnVHf735uYiefEthlweY5xlYP1goz3dRojb+Gg0KptCkiABPncpb/M1YbYH",
	"q7rTrTQyXw7dGJmBCW+/7pBva4LzRoe3VeS8I2gaUPcrZgTq9wtEEyx5uYGix8gmkKGMipUt/tR29Cp4",
	"pza8eSiHwvbkMu8xERuu87ihrfQQrwBJalqO4T0ZPhaVVJ1AVWGwOCc0v1YswrQrtEos2qIBRKrVixfO",
	"iE6uqF4IpbkLVO3JkydPxbVNFzyZOS3NWDWuT02Zw0G/RxWL0qLChUxZXZ+v2Ax+AMxnEE28UEb9GxUW",
	"EY3JSlOMMBYn71Guyxqf/Tdolv8FiNbPQ3RcuqayGTGijWuoCl0DaFiElxXIFeUV3f0s7Nm363lmFPD/",
	"6qTaWrS5c8wNEOq8nzGXlq2ZM3nbKeazC8jOz5ScvJjzLp155Q0+W1PdMOO4HlTtNmpMFqoeoprGRVO/",
	"sz4/n1/6wnKmF20fj9SHD/STI/mc8EGh3VZJoKgu/u9LJ67NnlBLA/xGJcWsoV5HwXSWQXiw47upCFbq",
	"ElKUbu1RUmWVNGyG5002FF8Bwc9YsM48VpgHRqeIOiV41InFJjf4geiaDWTIhdvrRqhlwYirCS/N04Gc",
	"uiGQP4N+/nMW3Pj5zxcAxcp4kNFg0YjLzVKBwpUZcbFFcIJUH0tyQxEGlcgQsi9SlDf3hJMoDVBwLMM2",
	"WvwIY0rwwJZHtkQScoxjzmr4JLAbTQSRlpY7MtKHz38Ch0DIQJa2oxpZwQbzdLvD2i5MqeRbbI4OZhGW",
	"ghuIDIl5d1qXAcnveSzzuhdqzVN7H3JsULs8AeQHX+QcSfZZShmSgClxDP9wl8J0p4+Gmy7uVMi2K6K1",
	"W3Uw4dGg1yb7nt8AFCq9CI1g6clonOoysOFYj8K7pOAwl5TCIgETENAjv7nH1YdSBPK6gu+5XCbje64y",
	"bAthV5CcTKuOVsnGQ2bBdKDenapo3Hs2fPAE3UB0p0c4WCGmRv//9tdC8d8QNaH09cice2ROPTp3jiZY",
	"WWZxwKLQpeom+IjF/IcjezPYd/g79PXwJ2+IRI2PEFnPKDSESKrEg1oyrkv94DYTKIFU0QRAyHQgNbff",
	"Jqs9ySKieg/d8FM8k2FIFCpSG3mSerNJvsqLmG8gTRfLJO+rHSHgbx3RjTURPNI0HtOuwCzYYbvOcxhU",
	"Bnf+KLhzNiHrruF4tKXXassT20Gg5QkkbKiQ8Rg1mdqkJAgdWCvhVyAyb0UlVuEwQdSnS+0LgIW/GS5X",
	"ZJWrkxa3JhbtuYQgb0UIyCK6MG447TfAn1CYRAQpoY6DtGsizPp0j2UvePop0EAk0RSqgUcI8bDXER2u",
	"CUS+7VHrli+83sSVTkQEjGJLye57at2ItDiOWTqC8PM/AmyigBrK58fm+08mFANNORKJA0/KcjkE54i6",
	"UD3rc1NcGU8DRFdxqYr1Q9ks/D7Yr/m5jfkEOolfuuSvXbUFq3UYzHIFCFxWfu19z6bcvOrj7Sb0EoS/",
	"wAXMFI8KLCDo0psOn/97CY0KKTP1Es20mj7FBP9tItgqFWKRo7vgePIAt77nN14xQTBJJxw7RuZ2j209",
	"9XvbRBMqFznSqpP1a3cG+4cUrPDSvDMqnNV71RdDh9pi7BNpv+H5Jdilf8TaUIEC0C8SKkAUkl04aeme",
	"+R2XSkGe2tsY2QDjKUwYWQMopn/JqhaXTcz6Hqi4VsfVXaoRIJHlfzli7J0nXBPI7jUVRwmvN4Wk3qlD",
	"0FJVpWrmg+so4SVqm+bGh+jlNECZuz796VnlLoyFWDIxl0hCEUbBss1CJrYQO5lIJk6ysTnLUBkQGA+T",
	"zfNajUK+pJ3OzEOfsLvQSF6ZtxJVkiK87YoqScXPD7iH4cyvn7cYeQxv9oE+Hm4qBqxYiJE5m79EAeAp",
	"UKFk/KwQc6cgyvC6hqt/mZJhbr6/uC5HyRLH/Jqq4AA5zdHkC1YRQgVn07GFGEOsHNP4L3nWiBNxvdHx",
	"rjUKDLJeCxaY8AsJApfGzSWTP9ragVtvjroYitlvwSuzzlvOjF+RoluGP3wieAshrDPPdqF7S+72hHI/",
	"Hrwy+06vyZs04YSmtDmraQbzyfHb1F2nR9+dOzX+XfWeNX8C2fj3/I37BUexhUuX47GSGK3mnz4VVebV",
	"EozhWHGWY5fpW2HJk19xjhA9LGLvyxTK6pTPR++7DFpZLyv4P/bAyoIR+pB74LN0/fwb2botMgNKL+Ye",
	"1RL3XDSXnI9mawr1CIPNR5ZYNVzy6JYYLRECvsevwhRcYQQE49vyjvb6UM5Cb09bPwWdAG7Gk0oxNHz8",
	"qu6GBZXZeLKJZY15dQabn8x8c0WVh6+DggFXSrJIVht0y2q1h2YoLlV7LDQH8f4GabjQTOj3LfBAsCuu",
	"BeKVWMrsR97s5SelePwL6jSkkvQnR6oVQP0Ikr1qOSMXzf3kCiJw85rm8j3ltqQfnbhCJ6Sz39jCYwmv",
	"BEP6omWUKHJSnYHoAiBZa955h7aRF0EVfGs/jYESHG44kYUy+84sFC4QeFzuv5a58gNUf/LUuzZ1jiyS",
	"mAqUVTDLZm7unV5RekSRw6IdKliYkiUI03FNicGUL5Hp30eLLaZE1cS0brYZZcD/CuYZO64j5V7aXBUR",
	"BybvspZ2jverPs9Ty1m4SmFF+xD5DzAvPc7DlPHgoFxxWeng1eHgu15cvMaritk9SVRnPnghQlmN3cH3",
	"TcX2W7TZv6VTzpzop16wuuHlJnFZfGt9F9w6lm3mriKLOgQmVy7avorHex7Z+iPMSfGXf1RjuXZRDAsx",
	"TD/OdVd0qAWHKah3QQRHbS7acvNqVCTQ8a3N40DvWwAs0QopzyBQfuUnNueRX9El6/v/2ufYhXSJf5Uh",
	"t1g7XTRssCjmq74Mn4/oF0Y475urE9nKAHiH9yO+vaN39Cvh65J/sMSdH/+uvCn8rVlZMi+vOlEdH4WT",
	"ebAwdjl0x31EG6r/SGCsxmVVEvAvRhncRi5vO8vsfpovNSMdd2r+dWoiLf74UBTY+78JJaDnk0k0Kl/9",
	"EgS+LODhsc8K1T1FGD05FAUxlVaoLpoXv8BzapU1JfWyiKYDB94WuWTjS3U1fNDnBSuy+uWQlXdQkSW6",
	"M/kIZRhkJvvrWDU1edEavBIA8kamkI+BEGnehNQ+BDnJ7Rq7e86/kCRcdB/s8iuLIchqidNIu5+4kg6c",
	"0Pm5ORSt1hbQpS8vG9MSuog7BKk3BBFqqOeUa9ODE3mKJjL8G+agOnqyy/rkcLnoyy5Juznuvsvw53Qe",
	"fqbkvM9Jf4SVQhYGD4xXX7KRZ3sJZHz22WefzRw1xBzq0kQv05crVnHVb2UC0o6pd8Arw85hqPlX82sz",
	"U8lLszOnLt+YvZScmbs8rZ1zHnn/YMTKXwZWDV7AN+6muss/oTfpX8ipNUIhJcNIK4HwzrY/NkdRdHB3",
	"Iyc/7x+gY5jZO+499R78H0NZtIIykWMgjnCz7nO/VoGM6gDFINSqghFrkArgoMDVsa3BsoN++23kFaYj",
	"fK27mjR0qa3/WzHHCqCUOVpYUrTmKYOUmvISbpfnlWSXrl+iAI0rLO0Q3hhTNqTh8nRUaKo+Wz1UP6Xa",
	"agHddIStpuR7d/7E4pfNcHqS9Vd2N8S9P/fcyeZjsuxWZ6yVd9Vy2EXOP7UI0DryIZS9c9vxH2H/Kdv9",
	"0Y2/eKywooussvYSxltIR6i43gzxgs+t7O+8Lk2S3uCgQ143gzNdeExTsEaHU6y0qdpu8M4c6Tn5F0CJ",
	"/jR5qayfhA3JGOZaBi9tYTdtjlyAFsmezApihb5+flvcmi1HtIXjfpPzH9mqgyUlBEgoPc9v277fV0c5",
	"iirooFnmA6QRJbBBbh5FGZKioCfClmQFLeOtSCrxpSE5Ik4KK4o4+fHDkurdxe84bRopxJTr6P8xQuwd",
	"OsD/EEvI5xcmcyBIo2jfcSYQuydDa/ZA/4SLyJbHckuhOmneP8SyD7yjFt/tCabmMzvmk7NiLIh8n/tC",
	"XDCovfqhBkJuHswnZwcHhzIKdJwkY4RW/9j6KVX6x0eXDgA3CJn3Q6j7B5KOHiDIEMIoC4V0claQaorq",
	"3Ec98cBVfmDobnnKxX1oMSau9fNkXxvowsWYktOSeUOgKsW7Seg7JlzWYunJUz9i5uNbFAVOsZvppqX6",
	"gVqo7gbLW422mqilyf7oWdbYzzvK2GTqI7x0dQDhT0aqgZvvdEQbqJ5mB/Hjp8v1BAFlVu03spOP6+KD",
	"A4UwlVmba6ElRobEXLpMbUD+5lfatFncpy75T5HF56EEyCmMRiD0zASIq3aUEIileZeH2LafJETY7IAR",
	"83Ytzj3ZOEUB6TTivB8QkfW/kE7L/7AQ7hrIjo9d/k0fuWuX1/4zAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
