// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ConsentKind.
const (
	ConsentKindOverseasTransfer ConsentKind = "overseas_transfer"
	ConsentKindPrivacy          ConsentKind = "privacy"
	ConsentKindSensitiveData    ConsentKind = "sensitive_data"
	ConsentKindTerms            ConsentKind = "terms"
)

// Valid indicates whether the value is a known member of the ConsentKind enum.
func (e ConsentKind) Valid() bool {
	switch e {
	case ConsentKindOverseasTransfer:
		return true
	case ConsentKindPrivacy:
		return true
	case ConsentKindSensitiveData:
		return true
	case ConsentKindTerms:
		return true
	default:
		return false
	}
}

// Defines values for ConversationMode.
const (
	ConversationModeChat  ConversationMode = "chat"
	ConversationModeVoice ConversationMode = "voice"
)

// Valid indicates whether the value is a known member of the ConversationMode enum.
func (e ConversationMode) Valid() bool {
	switch e {
	case ConversationModeChat:
		return true
	case ConversationModeVoice:
		return true
	default:
		return false
	}
}

// Defines values for DiaryStatus.
const (
	DiaryStatusConfirmed DiaryStatus = "confirmed"
	DiaryStatusDraft     DiaryStatus = "draft"
)

// Valid indicates whether the value is a known member of the DiaryStatus enum.
func (e DiaryStatus) Valid() bool {
	switch e {
	case DiaryStatusConfirmed:
		return true
	case DiaryStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for PasswordReason.
const (
	PasswordReasonInvalidEncoding PasswordReason = "invalid_encoding"
	PasswordReasonMatchesEmail    PasswordReason = "matches_email"
	PasswordReasonTooCommon       PasswordReason = "too_common"
	PasswordReasonTooLong         PasswordReason = "too_long"
	PasswordReasonTooShort        PasswordReason = "too_short"
)

// Valid indicates whether the value is a known member of the PasswordReason enum.
func (e PasswordReason) Valid() bool {
	switch e {
	case PasswordReasonInvalidEncoding:
		return true
	case PasswordReasonMatchesEmail:
		return true
	case PasswordReasonTooCommon:
		return true
	case PasswordReasonTooLong:
		return true
	case PasswordReasonTooShort:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	ProblemCodeConsentRequired      ProblemCode = "consent_required"
	ProblemCodeCrossOriginRejected  ProblemCode = "cross_origin_rejected"
	ProblemCodeEmailTaken           ProblemCode = "email_taken"
	ProblemCodeForbidden            ProblemCode = "forbidden"
	ProblemCodeInternalError        ProblemCode = "internal_error"
	ProblemCodeInvalidCredentials   ProblemCode = "invalid_credentials"
	ProblemCodeMethodNotAllowed     ProblemCode = "method_not_allowed"
	ProblemCodeNotFound             ProblemCode = "not_found"
	ProblemCodePayloadTooLarge      ProblemCode = "payload_too_large"
	ProblemCodeRateLimited          ProblemCode = "rate_limited"
	ProblemCodeServiceUnavailable   ProblemCode = "service_unavailable"
	ProblemCodeUnauthenticated      ProblemCode = "unauthenticated"
	ProblemCodeUnsupportedMediaType ProblemCode = "unsupported_media_type"
	ProblemCodeValidationFailed     ProblemCode = "validation_failed"
	ProblemCodeWeakPassword         ProblemCode = "weak_password"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case ProblemCodeConsentRequired:
		return true
	case ProblemCodeCrossOriginRejected:
		return true
	case ProblemCodeEmailTaken:
		return true
	case ProblemCodeForbidden:
		return true
	case ProblemCodeInternalError:
		return true
	case ProblemCodeInvalidCredentials:
		return true
	case ProblemCodeMethodNotAllowed:
		return true
	case ProblemCodeNotFound:
		return true
	case ProblemCodePayloadTooLarge:
		return true
	case ProblemCodeRateLimited:
		return true
	case ProblemCodeServiceUnavailable:
		return true
	case ProblemCodeUnauthenticated:
		return true
	case ProblemCodeUnsupportedMediaType:
		return true
	case ProblemCodeValidationFailed:
		return true
	case ProblemCodeWeakPassword:
		return true
	default:
		return false
	}
}

// Defines values for ProblemField.
const (
	ProblemFieldDisplayName ProblemField = "display_name"
	ProblemFieldEmail       ProblemField = "email"
	ProblemFieldQ           ProblemField = "q"
	ProblemFieldText        ProblemField = "text"
	ProblemFieldTimezone    ProblemField = "timezone"
)

// Valid indicates whether the value is a known member of the ProblemField enum.
func (e ProblemField) Valid() bool {
	switch e {
	case ProblemFieldDisplayName:
		return true
	case ProblemFieldEmail:
		return true
	case ProblemFieldQ:
		return true
	case ProblemFieldText:
		return true
	case ProblemFieldTimezone:
		return true
	default:
		return false
	}
}

// Defines values for WsAITextType.
const (
	WsAITextTypeAiText WsAITextType = "ai_text"
)

// Valid indicates whether the value is a known member of the WsAITextType enum.
func (e WsAITextType) Valid() bool {
	switch e {
	case WsAITextTypeAiText:
		return true
	default:
		return false
	}
}

// Defines values for WsDiaryReadyType.
const (
	WsDiaryReadyTypeDiaryReady WsDiaryReadyType = "diary_ready"
)

// Valid indicates whether the value is a known member of the WsDiaryReadyType enum.
func (e WsDiaryReadyType) Valid() bool {
	switch e {
	case WsDiaryReadyTypeDiaryReady:
		return true
	default:
		return false
	}
}

// Defines values for WsEndType.
const (
	WsEndTypeEnd WsEndType = "end"
)

// Valid indicates whether the value is a known member of the WsEndType enum.
func (e WsEndType) Valid() bool {
	switch e {
	case WsEndTypeEnd:
		return true
	default:
		return false
	}
}

// Defines values for WsEndReason.
const (
	WsEndReasonIdle WsEndReason = "idle"
	WsEndReasonUser WsEndReason = "user"
)

// Valid indicates whether the value is a known member of the WsEndReason enum.
func (e WsEndReason) Valid() bool {
	switch e {
	case WsEndReasonIdle:
		return true
	case WsEndReasonUser:
		return true
	default:
		return false
	}
}

// Defines values for WsEndedType.
const (
	WsEndedTypeEnded WsEndedType = "ended"
)

// Valid indicates whether the value is a known member of the WsEndedType enum.
func (e WsEndedType) Valid() bool {
	switch e {
	case WsEndedTypeEnded:
		return true
	default:
		return false
	}
}

// Defines values for WsErrorType.
const (
	WsErrorTypeError WsErrorType = "error"
)

// Valid indicates whether the value is a known member of the WsErrorType enum.
func (e WsErrorType) Valid() bool {
	switch e {
	case WsErrorTypeError:
		return true
	default:
		return false
	}
}

// Defines values for WsErrorCode.
const (
	WsErrorCodeAlreadyStarted    WsErrorCode = "already_started"
	WsErrorCodeConversationEnded WsErrorCode = "conversation_ended"
	WsErrorCodeInternalError     WsErrorCode = "internal_error"
	WsErrorCodeInvalidMessage    WsErrorCode = "invalid_message"
	WsErrorCodeMessageTooLarge   WsErrorCode = "message_too_large"
	WsErrorCodeNotStarted        WsErrorCode = "not_started"
	WsErrorCodeRateLimited       WsErrorCode = "rate_limited"
	WsErrorCodeUnsupportedMode   WsErrorCode = "unsupported_mode"
)

// Valid indicates whether the value is a known member of the WsErrorCode enum.
func (e WsErrorCode) Valid() bool {
	switch e {
	case WsErrorCodeAlreadyStarted:
		return true
	case WsErrorCodeConversationEnded:
		return true
	case WsErrorCodeInternalError:
		return true
	case WsErrorCodeInvalidMessage:
		return true
	case WsErrorCodeMessageTooLarge:
		return true
	case WsErrorCodeNotStarted:
		return true
	case WsErrorCodeRateLimited:
		return true
	case WsErrorCodeUnsupportedMode:
		return true
	default:
		return false
	}
}

// Defines values for WsOrigin.
const (
	WsOriginFixed    WsOrigin = "fixed"
	WsOriginModel    WsOrigin = "model"
	WsOriginTemplate WsOrigin = "template"
	WsOriginUser     WsOrigin = "user"
)

// Valid indicates whether the value is a known member of the WsOrigin enum.
func (e WsOrigin) Valid() bool {
	switch e {
	case WsOriginFixed:
		return true
	case WsOriginModel:
		return true
	case WsOriginTemplate:
		return true
	case WsOriginUser:
		return true
	default:
		return false
	}
}

// Defines values for WsReadyType.
const (
	WsReadyTypeReady WsReadyType = "ready"
)

// Valid indicates whether the value is a known member of the WsReadyType enum.
func (e WsReadyType) Valid() bool {
	switch e {
	case WsReadyTypeReady:
		return true
	default:
		return false
	}
}

// Defines values for WsResourcesType.
const (
	WsResourcesTypeResources WsResourcesType = "resources"
)

// Valid indicates whether the value is a known member of the WsResourcesType enum.
func (e WsResourcesType) Valid() bool {
	switch e {
	case WsResourcesTypeResources:
		return true
	default:
		return false
	}
}

// Defines values for WsSpeaker.
const (
	WsSpeakerAi   WsSpeaker = "ai"
	WsSpeakerUser WsSpeaker = "user"
)

// Valid indicates whether the value is a known member of the WsSpeaker enum.
func (e WsSpeaker) Valid() bool {
	switch e {
	case WsSpeakerAi:
		return true
	case WsSpeakerUser:
		return true
	default:
		return false
	}
}

// Defines values for WsStartType.
const (
	WsStartTypeStart WsStartType = "start"
)

// Valid indicates whether the value is a known member of the WsStartType enum.
func (e WsStartType) Valid() bool {
	switch e {
	case WsStartTypeStart:
		return true
	default:
		return false
	}
}

// Defines values for WsThinkingType.
const (
	WsThinkingTypeThinking WsThinkingType = "thinking"
)

// Valid indicates whether the value is a known member of the WsThinkingType enum.
func (e WsThinkingType) Valid() bool {
	switch e {
	case WsThinkingTypeThinking:
		return true
	default:
		return false
	}
}

// Defines values for WsUserTextType.
const (
	WsUserTextTypeUserText WsUserTextType = "user_text"
)

// Valid indicates whether the value is a known member of the WsUserTextType enum.
func (e WsUserTextType) Valid() bool {
	switch e {
	case WsUserTextTypeUserText:
		return true
	default:
		return false
	}
}

// AuthRequirements defines model for AuthRequirements.
type AuthRequirements struct {
	// Consents 가입에 필요한 동의와 그 지금 판. 모두 필수다
	Consents []ConsentGrant `json:"consents"`

	// DisplayNameMaxLength 부를 이름의 최대 글자 수
	//
	// Example: 40
	DisplayNameMaxLength int                  `json:"display_name_max_length"`
	Password             PasswordRequirements `json:"password"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	User User `json:"user"`
}

// ConsentGrant defines model for ConsentGrant.
type ConsentGrant struct {
	// Kind 동의의 종류.
	// `terms` 이용약관, `privacy` 개인정보 처리방침, `sensitive_data` 마음에 관한 기록의 처리,
	// `overseas_transfer` 대화 내용이 외부 AI 서비스로 전송되어 해외에서 처리되는 것.
	Kind ConsentKind `json:"kind"`

	// Version 사용자가 보고 동의한 문서의 판
	//
	// Example: 2026-09-20
	Version string `json:"version"`
}

// ConsentKind 동의의 종류.
// `terms` 이용약관, `privacy` 개인정보 처리방침, `sensitive_data` 마음에 관한 기록의 처리,
// `overseas_transfer` 대화 내용이 외부 AI 서비스로 전송되어 해외에서 처리되는 것.
type ConsentKind string

// ConsentProblem `consent_required`일 때만 있다
type ConsentProblem struct {
	// Missing 필요한데 오지 않은 동의
	Missing []ConsentKind `json:"missing"`

	// Outdated 왔지만 지금 판이 아닌 동의. 가입 규칙을 다시 받아 새 문서를 보여줘야 한다
	Outdated []ConsentKind `json:"outdated"`
}

// ConversationMode 대화를 시작할 때의 기본 방식
type ConversationMode string

// Diary defines model for Diary.
type Diary struct {
	// ConfirmedAt 마지막으로 확인한 시각. 한 번도 확인하지 않았으면 null이다
	ConfirmedAt *Timestamp `json:"confirmed_at"`

	// Date 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	Date RecordDate `json:"date"`

	// Status `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
	Status DiaryStatus `json:"status"`

	// Text 상태가 `draft`면 초안, `confirmed`면 확인한 글이다.
	// 초안을 만들지 못한 날에는 빈 초안이 온다. 사용자가 직접 써서 확인하면 된다.
	Text string `json:"text"`

	// UpdatedAt UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
	//
	// Example: 2026-09-20T12:00:00.000Z
	UpdatedAt Timestamp `json:"updated_at"`
}

// DiaryList defines model for DiaryList.
type DiaryList struct {
	Items []DiarySummary `json:"items"`
}

// DiaryStatus `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
type DiaryStatus string

// DiarySummary defines model for DiarySummary.
type DiarySummary struct {
	// Date 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	Date RecordDate `json:"date"`

	// FirstLine 지금 화면에 보일 글의 첫 줄. 길면 잘라서 준다. 빈 초안이면 빈 문자열이다
	FirstLine string `json:"first_line"`

	// Snippet 검색어가 나온 자리의 앞뒤 글. 검색 결과에만 있다
	Snippet *string `json:"snippet,omitempty"`

	// Status `draft` 대화에서 만든 초안이고 사용자가 아직 확인하지 않았다. `confirmed` 사용자가 확인했다.
	Status DiaryStatus `json:"status"`
}

// DiaryUpdate defines model for DiaryUpdate.
type DiaryUpdate struct {
	// Text 일기 글 전체
	Text string `json:"text"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	Settings SettingsSummary `json:"settings"`
	User     User            `json:"user"`
}

// PasswordReason 비밀번호를 받지 않는 이유.
// `too_short` 너무 짧다, `too_long` 너무 길다, `too_common` 누구나 먼저 넣어 보는 흔한 비밀번호다,
// `matches_email` 이메일 주소나 그 앞부분과 같다, `invalid_encoding` 글자로 읽을 수 없는 바이트가 있다.
type PasswordReason string

// PasswordRequirements defines model for PasswordRequirements.
type PasswordRequirements struct {
	// MaxBytes 최대 길이. UTF-8 바이트로 센다(한글 한 글자는 3바이트)
	//
	// Example: 128
	MaxBytes int `json:"max_bytes"`

	// MinLength 최소 길이. 글자 수로 센다
	//
	// Example: 10
	MinLength int `json:"min_length"`
}

// Problem RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type Problem struct {
	// Code 오류의 종류. 값은 바뀌지 않는다. 화면은 이 값으로 안내 문구를 고른다
	Code ProblemCode `json:"code"`

	// Consents `consent_required`일 때만 있다
	Consents *ConsentProblem `json:"consents,omitempty"`

	// Fields 422 `validation_failed`일 때만 있다
	Fields *[]ProblemField `json:"fields,omitempty"`

	// Reasons `weak_password`일 때만 있다
	Reasons *[]PasswordReason `json:"reasons,omitempty"`

	// RequestID 이 요청의 ID. 응답의 `X-Request-Id` 헤더와 같다. 문의할 때 알려주면 서버 로그에서 찾을 수 있다
	RequestID string `json:"request_id"`

	// Status HTTP 상태 코드와 같은 값
	//
	// Example: 422
	Status int `json:"status"`

	// Title 개발자가 읽는 짧은 영어 문구. 사용자에게 보여주지 않는다
	//
	// Example: Password does not meet the policy
	Title string `json:"title"`

	// Type 오류 종류를 가리키는 URI 참조. `/problems/{code}` 꼴이다
	//
	// Example: /problems/weak_password
	Type string `json:"type"`
}

// ProblemCode 오류의 종류. 값은 바뀌지 않는다. 화면은 이 값으로 안내 문구를 고른다
type ProblemCode string

// ProblemField 받을 수 없는 값이 든 요청 필드의 이름. 쿼리 매개변수일 때는 그 이름이다
type ProblemField string

// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
//
// Example: 2026-09-20
type RecordDate = openapi_types.Date

// Resource defines model for Resource.
type Resource struct {
	// Description 언제, 어떤 도움을 받을 수 있는지에 대한 한두 문장
	//
	// Example: 24시간, 지금 바로 이야기를 들어줄 사람과 연결돼요.
	Description string `json:"description"`

	// ID 자원을 가리키는 고정된 이름. 화면이 아이콘을 고르거나 목록을 견줄 때 쓴다
	//
	// Example: suicide_prevention_109
	ID string `json:"id"`

	// Name Example: 자살예방상담전화
	Name string `json:"name"`

	// Phone 전화번호. 화면에 그대로 보여주고, 걸 때는 숫자만 남겨 `tel:`에 넣는다
	//
	// Example: 109
	Phone string `json:"phone"`
}

// ResourceList defines model for ResourceList.
type ResourceList struct {
	// Items 급한 곳이 앞에 온다
	Items []Resource `json:"items"`
}

// SettingsSummary defines model for SettingsSummary.
type SettingsSummary struct {
	// AnalysisEnabled 끄면 대화와 일기만 남기고 마음 신호를 뽑지 않는다
	AnalysisEnabled bool `json:"analysis_enabled"`

	// DefaultMode 대화를 시작할 때의 기본 방식
	DefaultMode     ConversationMode `json:"default_mode"`
	MemoryEnabled   bool             `json:"memory_enabled"`
	MoodPickEnabled bool             `json:"mood_pick_enabled"`
	ReminderEnabled bool             `json:"reminder_enabled"`

	// ReminderTime 알림 시각. 사용자 시간대의 벽시계 시각이고 `HH:MM` 꼴이다
	//
	// Example: 20:00
	ReminderTime string `json:"reminder_time"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	// Consents `GET /api/v1/auth/requirements`가 준 동의 목록 가운데 사용자가 동의한 것
	Consents []ConsentGrant `json:"consents"`

	// DisplayName 부를 이름. 비워 둘 수 있다. 앞뒤 공백을 떼고 40자까지 받는다
	DisplayName *string `json:"display_name,omitempty"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`

	// Timezone IANA 시간대 이름(예: `Asia/Seoul`). 브라우저의 `Intl.DateTimeFormat().resolvedOptions().timeZone` 값을 보낸다.
	// 하루의 경계와 알림 시각이 이 값으로 계산된다. 보내지 않으면 `Asia/Seoul`이다.
	Timezone *string `json:"timezone,omitempty"`
}

// Timestamp UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
//
// Example: 2026-09-20T12:00:00.000Z
type Timestamp = UTCTime

// User defines model for User.
type User struct {
	// CreatedAt UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
	//
	// Example: 2026-09-20T12:00:00.000Z
	CreatedAt Timestamp `json:"created_at"`

	// DisplayName 부를 이름. 정하지 않았으면 null이다
	DisplayName *string            `json:"display_name"`
	Email       string             `json:"email"`
	ID          openapi_types.UUID `json:"id"`

	// IsDemo 둘러보기용으로 만들어진 계정인지
	IsDemo bool `json:"is_demo"`

	// Timezone IANA 시간대 이름
	//
	// Example: Asia/Seoul
	Timezone string `json:"timezone"`
}

// WsAIText AI의 말 하나. 한 번에 통째로 온다
type WsAIText struct {
	// Origin `model`, `fixed`, `template` 가운데 하나다
	Origin WsOrigin     `json:"origin"`
	Seq    int          `json:"seq"`
	Text   string       `json:"text"`
	Type   WsAITextType `json:"type"`
}

// WsAITextType defines model for WsAIText.Type.
type WsAITextType string

// WsClientMessage 클라이언트가 대화 채널로 보내는 메시지. `type`으로 가린다
type WsClientMessage struct {
	union json.RawMessage
}

// WsDiaryReady 일기 초안이 준비됐다. `GET /api/v1/diaries/{date}`로 읽는다
type WsDiaryReady struct {
	// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	RecordDate RecordDate       `json:"record_date"`
	Type       WsDiaryReadyType `json:"type"`
}

// WsDiaryReadyType defines model for WsDiaryReady.Type.
type WsDiaryReadyType string

// WsEnd 끝내기 버튼을 눌렀다. 서버는 `ended`로 답한다
type WsEnd struct {
	Type WsEndType `json:"type"`
}

// WsEndType defines model for WsEnd.Type.
type WsEndType string

// WsEndReason `user` 끝내기 버튼을 눌렀다. `idle` 한동안 말이 없어 서버가 닫았다.
type WsEndReason string

// WsEnded 대화가 끝났다. 이 연결로는 더 보낼 수 없다. 다시 이야기하려면 새로 연결해 `start`를 보낸다
type WsEnded struct {
	// DiaryExpected 일기 초안을 만들고 있으면 참이다. 준비되면 `diary_ready`가 온다.
	// 거짓이면 초안은 만들어지지 않는다. 사용자가 한 말이 없었거나, 초안을 자동으로 만들지 않는 대화였다.
	DiaryExpected bool `json:"diary_expected"`

	// Reason `user` 끝내기 버튼을 눌렀다. `idle` 한동안 말이 없어 서버가 닫았다.
	Reason WsEndReason `json:"reason"`

	// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	RecordDate RecordDate  `json:"record_date"`
	Type       WsEndedType `json:"type"`
}

// WsEndedType defines model for WsEnded.Type.
type WsEndedType string

// WsError 요청을 처리하지 못했다. 사용자가 쓴 글은 담지 않는다
type WsError struct {
	// ClientMessageID 어느 글을 처리하다 난 오류인지. 글과 상관없는 오류에는 없다
	ClientMessageID *openapi_types.UUID `json:"client_message_id,omitempty"`

	// Code `invalid_message` JSON이 아니거나, 모르는 `type`이거나, 모양이 틀렸다.
	// `message_too_large` 메시지가 너무 크다.
	// `rate_limited` 너무 자주 보냈다. 잠시 뒤에 같은 `client_message_id`로 다시 보낸다.
	// `not_started` `start`보다 먼저 다른 메시지를 보냈다.
	// `already_started` `start`를 두 번 보냈다.
	// `unsupported_mode` 지금은 받지 않는 대화 방식이다.
	// `conversation_ended` 이미 끝난 대화다. 새로 연결해 `start`를 보낸다.
	// `internal_error` 서버 쪽 문제다. 글은 저장되지 않았을 수 있다. 같은 `client_message_id`로 다시 보내도 된다.
	Code WsErrorCode `json:"code"`
	Type WsErrorType `json:"type"`
}

// WsErrorType defines model for WsError.Type.
type WsErrorType string

// WsErrorCode `invalid_message` JSON이 아니거나, 모르는 `type`이거나, 모양이 틀렸다.
// `message_too_large` 메시지가 너무 크다.
// `rate_limited` 너무 자주 보냈다. 잠시 뒤에 같은 `client_message_id`로 다시 보낸다.
// `not_started` `start`보다 먼저 다른 메시지를 보냈다.
// `already_started` `start`를 두 번 보냈다.
// `unsupported_mode` 지금은 받지 않는 대화 방식이다.
// `conversation_ended` 이미 끝난 대화다. 새로 연결해 `start`를 보낸다.
// `internal_error` 서버 쪽 문제다. 글은 저장되지 않았을 수 있다. 같은 `client_message_id`로 다시 보내도 된다.
type WsErrorCode string

// WsOrigin 말을 만든 쪽. `user` 사용자, `model` 대화 AI, `fixed` 미리 써 둔 문구,
// `template` 사용자의 표현을 넣어 만든 고정 문형.
type WsOrigin string

// WsReady `start`의 답. 이 메시지를 받은 뒤에 글을 보낼 수 있다
type WsReady struct {
	ConversationID openapi_types.UUID `json:"conversation_id"`

	// RecordDate 기록 날짜. 달력 날짜가 아니라, 사용자의 시간대로 새벽 4시에 바뀌는 하루다.
	// 서버가 정해서 알려주는 값이다. 웹앱이 시각에서 직접 계산하지 않는다.
	//
	//
	// Example: 2026-09-20
	RecordDate RecordDate `json:"record_date"`

	// ResourcesPinned 이 대화에서 도움 자원을 화면에 고정해 두었는지. 참이면 곧이어 `resources`가 온다
	ResourcesPinned bool `json:"resources_pinned"`

	// Resumed 열려 있던 대화를 이어가는 것이면 참이다. 거짓이면 새 대화이고 곧이어 첫 안부가 `ai_text`로 온다
	Resumed bool        `json:"resumed"`
	Type    WsReadyType `json:"type"`

	// Utterances 이어가는 대화의 지난 발화. 순번대로다. 새 대화면 비어 있다
	Utterances []WsUtterance `json:"utterances"`
}

// WsReadyType defines model for WsReady.Type.
type WsReadyType string

// WsResources 화면에 고정해 둘 도움 자원. 받은 뒤로는 대화가 끝날 때까지 고정해 둔다
type WsResources struct {
	// Items 급한 곳이 앞에 온다
	Items []Resource      `json:"items"`
	Type  WsResourcesType `json:"type"`
}

// WsResourcesType defines model for WsResources.Type.
type WsResourcesType string

// WsServerMessage 서버가 대화 채널로 보내는 메시지. `type`으로 가린다
type WsServerMessage struct {
	union json.RawMessage
}

// WsSpeaker 누가 한 말인지
type WsSpeaker string

// WsStart 대화를 시작한다. 연결마다 한 번 보낸다. 열린 대화가 있으면 새로 만들지 않고 그 대화를 이어간다.
// 기록 날짜가 지나도록 열려 있던 대화는 서버가 먼저 끝내고 새 대화를 연다.
type WsStart struct {
	// Mode 대화 방식. 지금은 `chat`만 받는다. 다른 값에는 `error`(`unsupported_mode`)가 온다
	Mode ConversationMode `json:"mode"`
	Type WsStartType      `json:"type"`
}

// WsStartType defines model for WsStart.Type.
type WsStartType string

// WsThinking 글을 받아 저장했고 답을 준비하고 있다. 받았다는 확인이기도 하다.
// 이 메시지가 오지 않으면 같은 `client_message_id`로 다시 보낸다.
type WsThinking struct {
	// ClientMessageID 어느 글에 대한 것인지
	ClientMessageID openapi_types.UUID `json:"client_message_id"`

	// Seq 그 글에 붙은 순번
	Seq  int            `json:"seq"`
	Type WsThinkingType `json:"type"`
}

// WsThinkingType defines model for WsThinking.Type.
type WsThinkingType string

// WsUserText 사용자가 쓴 글 하나
type WsUserText struct {
	// ClientMessageID 클라이언트가 글마다 새로 만드는 식별자(`crypto.randomUUID()`).
	// `thinking`을 받지 못해 다시 보낼 때는 같은 값을 쓴다. 같은 값의 글은 한 번만 저장된다.
	ClientMessageID openapi_types.UUID `json:"client_message_id"`

	// Text 앞뒤 공백을 뗀 글. 공백만 있는 글은 보내지 않는다
	Text string         `json:"text"`
	Type WsUserTextType `json:"type"`
}

// WsUserTextType defines model for WsUserText.Type.
type WsUserTextType string

// WsUtterance 지난 발화 하나. 이어가는 대화의 `ready`에 담겨 온다
type WsUtterance struct {
	// ClientMessageID 사용자의 글이면 보낼 때 붙인 식별자다. 아직 답을 받지 못한 글과 견주는 데 쓴다. AI의 말이면 null이다
	ClientMessageID *openapi_types.UUID `json:"client_message_id"`

	// CreatedAt UTC 시각. 밀리초 세 자리까지 고정된 꼴이다
	//
	// Example: 2026-09-20T12:00:00.000Z
	CreatedAt Timestamp `json:"created_at"`

	// Origin 말을 만든 쪽. `user` 사용자, `model` 대화 AI, `fixed` 미리 써 둔 문구,
	// `template` 사용자의 표현을 넣어 만든 고정 문형.
	Origin WsOrigin `json:"origin"`

	// Seq 대화 안에서의 순번. 0부터 하나씩 는다. 화면은 이 순서대로 보여준다
	Seq int `json:"seq"`

	// Speaker 누가 한 말인지
	Speaker WsSpeaker `json:"speaker"`
	Text    string    `json:"text"`
}

// BadRequest RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type BadRequest = Problem

// CrossOriginRejected RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type CrossOriginRejected = Problem

// NotFound RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type NotFound = Problem

// RateLimited RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type RateLimited = Problem

// Unauthenticated RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type Unauthenticated = Problem

// Unprocessable RFC 9457의 오류 본문에 `code`와 `request_id`를 더한 것
type Unprocessable = Problem

// ListDiariesParams defines parameters for ListDiaries.
type ListDiariesParams struct {
	// Month 보고 싶은 달. `YYYY-MM` 꼴이다
	Month *string `form:"month,omitempty" json:"month,omitempty"`

	// Q 검색어
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// PutDiaryJSONRequestBody defines body for PutDiary for application/json ContentType.
type PutDiaryJSONRequestBody = DiaryUpdate

// AsWsStart returns the union data inside the WsClientMessage as a WsStart
func (t WsClientMessage) AsWsStart() (WsStart, error) {
	var body WsStart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsStart overwrites any union data inside the WsClientMessage as the provided WsStart
func (t *WsClientMessage) FromWsStart(v WsStart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"start"}`))
	t.union = b
	return err
}

// MergeWsStart performs a merge with any union data inside the WsClientMessage, using the provided WsStart
func (t *WsClientMessage) MergeWsStart(v WsStart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"start"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsUserText returns the union data inside the WsClientMessage as a WsUserText
func (t WsClientMessage) AsWsUserText() (WsUserText, error) {
	var body WsUserText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsUserText overwrites any union data inside the WsClientMessage as the provided WsUserText
func (t *WsClientMessage) FromWsUserText(v WsUserText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"user_text"}`))
	t.union = b
	return err
}

// MergeWsUserText performs a merge with any union data inside the WsClientMessage, using the provided WsUserText
func (t *WsClientMessage) MergeWsUserText(v WsUserText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"user_text"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsEnd returns the union data inside the WsClientMessage as a WsEnd
func (t WsClientMessage) AsWsEnd() (WsEnd, error) {
	var body WsEnd
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsEnd overwrites any union data inside the WsClientMessage as the provided WsEnd
func (t *WsClientMessage) FromWsEnd(v WsEnd) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"end"}`))
	t.union = b
	return err
}

// MergeWsEnd performs a merge with any union data inside the WsClientMessage, using the provided WsEnd
func (t *WsClientMessage) MergeWsEnd(v WsEnd) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"end"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WsClientMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t WsClientMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "end":
		return t.AsWsEnd()
	case "start":
		return t.AsWsStart()
	case "user_text":
		return t.AsWsUserText()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t WsClientMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WsClientMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsWsReady returns the union data inside the WsServerMessage as a WsReady
func (t WsServerMessage) AsWsReady() (WsReady, error) {
	var body WsReady
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsReady overwrites any union data inside the WsServerMessage as the provided WsReady
func (t *WsServerMessage) FromWsReady(v WsReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ready"}`))
	t.union = b
	return err
}

// MergeWsReady performs a merge with any union data inside the WsServerMessage, using the provided WsReady
func (t *WsServerMessage) MergeWsReady(v WsReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ready"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsThinking returns the union data inside the WsServerMessage as a WsThinking
func (t WsServerMessage) AsWsThinking() (WsThinking, error) {
	var body WsThinking
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsThinking overwrites any union data inside the WsServerMessage as the provided WsThinking
func (t *WsServerMessage) FromWsThinking(v WsThinking) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"thinking"}`))
	t.union = b
	return err
}

// MergeWsThinking performs a merge with any union data inside the WsServerMessage, using the provided WsThinking
func (t *WsServerMessage) MergeWsThinking(v WsThinking) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"thinking"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsAIText returns the union data inside the WsServerMessage as a WsAIText
func (t WsServerMessage) AsWsAIText() (WsAIText, error) {
	var body WsAIText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsAIText overwrites any union data inside the WsServerMessage as the provided WsAIText
func (t *WsServerMessage) FromWsAIText(v WsAIText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ai_text"}`))
	t.union = b
	return err
}

// MergeWsAIText performs a merge with any union data inside the WsServerMessage, using the provided WsAIText
func (t *WsServerMessage) MergeWsAIText(v WsAIText) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ai_text"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsResources returns the union data inside the WsServerMessage as a WsResources
func (t WsServerMessage) AsWsResources() (WsResources, error) {
	var body WsResources
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsResources overwrites any union data inside the WsServerMessage as the provided WsResources
func (t *WsServerMessage) FromWsResources(v WsResources) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"resources"}`))
	t.union = b
	return err
}

// MergeWsResources performs a merge with any union data inside the WsServerMessage, using the provided WsResources
func (t *WsServerMessage) MergeWsResources(v WsResources) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"resources"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsEnded returns the union data inside the WsServerMessage as a WsEnded
func (t WsServerMessage) AsWsEnded() (WsEnded, error) {
	var body WsEnded
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsEnded overwrites any union data inside the WsServerMessage as the provided WsEnded
func (t *WsServerMessage) FromWsEnded(v WsEnded) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ended"}`))
	t.union = b
	return err
}

// MergeWsEnded performs a merge with any union data inside the WsServerMessage, using the provided WsEnded
func (t *WsServerMessage) MergeWsEnded(v WsEnded) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"ended"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsDiaryReady returns the union data inside the WsServerMessage as a WsDiaryReady
func (t WsServerMessage) AsWsDiaryReady() (WsDiaryReady, error) {
	var body WsDiaryReady
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsDiaryReady overwrites any union data inside the WsServerMessage as the provided WsDiaryReady
func (t *WsServerMessage) FromWsDiaryReady(v WsDiaryReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"diary_ready"}`))
	t.union = b
	return err
}

// MergeWsDiaryReady performs a merge with any union data inside the WsServerMessage, using the provided WsDiaryReady
func (t *WsServerMessage) MergeWsDiaryReady(v WsDiaryReady) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"diary_ready"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWsError returns the union data inside the WsServerMessage as a WsError
func (t WsServerMessage) AsWsError() (WsError, error) {
	var body WsError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWsError overwrites any union data inside the WsServerMessage as the provided WsError
func (t *WsServerMessage) FromWsError(v WsError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"error"}`))
	t.union = b
	return err
}

// MergeWsError performs a merge with any union data inside the WsServerMessage, using the provided WsError
func (t *WsServerMessage) MergeWsError(v WsError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"error"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WsServerMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t WsServerMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ai_text":
		return t.AsWsAIText()
	case "diary_ready":
		return t.AsWsDiaryReady()
	case "ended":
		return t.AsWsEnded()
	case "error":
		return t.AsWsError()
	case "ready":
		return t.AsWsReady()
	case "resources":
		return t.AsWsResources()
	case "thinking":
		return t.AsWsThinking()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t WsServerMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WsServerMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 로그인
	// (POST /api/v1/auth/login)
	Login(ctx *echo.Context) error
	// Logout 로그아웃
	// (POST /api/v1/auth/logout)
	Logout(ctx *echo.Context) error
	// GetAuthRequirements 가입 화면이 알아야 하는 규칙
	// (GET /api/v1/auth/requirements)
	GetAuthRequirements(ctx *echo.Context) error
	// Signup 가입
	// (POST /api/v1/auth/signup)
	Signup(ctx *echo.Context) error
	// DeleteDay 하루를 지운다
	// (DELETE /api/v1/days/{date})
	DeleteDay(ctx *echo.Context, date RecordDate) error
	// ListDiaries 한 달의 일기 목록, 또는 검색
	// (GET /api/v1/diaries)
	ListDiaries(ctx *echo.Context, params ListDiariesParams) error
	// GetDiary 하루의 일기
	// (GET /api/v1/diaries/{date})
	GetDiary(ctx *echo.Context, date RecordDate) error
	// PutDiary 일기를 고치고 확인한다
	// (PUT /api/v1/diaries/{date})
	PutDiary(ctx *echo.Context, date RecordDate) error
	// GetMe 로그인한 사용자와 설정
	// (GET /api/v1/me)
	GetMe(ctx *echo.Context) error
	// ListResources 도움이 필요할 때 연락할 수 있는 곳
	// (GET /api/v1/resources)
	ListResources(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetAuthRequirements converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuthRequirements(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuthRequirements(ctx)
	return err
}

// Signup converts echo context to params.
func (w *ServerInterfaceWrapper) Signup(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Signup(ctx)
	return err
}

// DeleteDay converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDay(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "date" -------------
	var date RecordDate

	err = runtime.BindStyledParameterWithOptions("simple", "date", ctx.Param("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteDay(ctx, date)
	return err
}

// ListDiaries converts echo context to params.
func (w *ServerInterfaceWrapper) ListDiaries(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDiariesParams
	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "month", ctx.QueryParams(), &params.Month, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter month: %s", err))
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListDiaries(ctx, params)
	return err
}

// GetDiary converts echo context to params.
func (w *ServerInterfaceWrapper) GetDiary(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "date" -------------
	var date RecordDate

	err = runtime.BindStyledParameterWithOptions("simple", "date", ctx.Param("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDiary(ctx, date)
	return err
}

// PutDiary converts echo context to params.
func (w *ServerInterfaceWrapper) PutDiary(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "date" -------------
	var date RecordDate

	err = runtime.BindStyledParameterWithOptions("simple", "date", ctx.Param("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutDiary(ctx, date)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// ListResources converts echo context to params.
func (w *ServerInterfaceWrapper) ListResources(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListResources(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/v1/auth/requirements", wrapper.GetAuthRequirements, options.OperationMiddlewares["getAuthRequirements"]...)
	router.POST(options.BaseURL+"/api/v1/auth/signup", wrapper.Signup, options.OperationMiddlewares["signup"]...)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login, options.OperationMiddlewares["login"]...)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout, options.OperationMiddlewares["logout"]...)
	router.GET(options.BaseURL+"/api/v1/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)
	router.GET(options.BaseURL+"/api/v1/diaries", wrapper.ListDiaries, options.OperationMiddlewares["listDiaries"]...)
	router.GET(options.BaseURL+"/api/v1/diaries/:date", wrapper.GetDiary, options.OperationMiddlewares["getDiary"]...)
	router.PUT(options.BaseURL+"/api/v1/diaries/:date", wrapper.PutDiary, options.OperationMiddlewares["putDiary"]...)
	router.DELETE(options.BaseURL+"/api/v1/days/:date", wrapper.DeleteDay, options.OperationMiddlewares["deleteDay"]...)
	router.GET(options.BaseURL+"/api/v1/resources", wrapper.ListResources, options.OperationMiddlewares["listResources"]...)

}

type BadRequestApplicationProblemPlusJSONResponse Problem

type CrossOriginRejectedApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ProblemApplicationProblemPlusJSONResponse Problem

type RateLimitedResponseHeaders struct {
	RetryAfter int
}
type RateLimitedApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers RateLimitedResponseHeaders
}

type UnauthenticatedApplicationProblemPlusJSONResponse Problem

type UnprocessableApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    AuthResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse Problem

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response Login403ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	RateLimitedApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogindefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response LogindefaultApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type Logout403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response Logout403ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response LogoutdefaultApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthRequirementsRequestObject struct {
}

type GetAuthRequirementsResponseObject interface {
	VisitGetAuthRequirementsResponse(w http.ResponseWriter) error
}

type GetAuthRequirements200JSONResponse AuthRequirements

func (response GetAuthRequirements200JSONResponse) VisitGetAuthRequirementsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthRequirementsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAuthRequirementsdefaultApplicationProblemPlusJSONResponse) VisitGetAuthRequirementsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup201ResponseHeaders struct {
	SetCookie string
}

type Signup201JSONResponse struct {
	Body    AuthResponse
	Headers Signup201ResponseHeaders
}

func (response Signup201JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Signup400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response Signup400ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Signup403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response Signup403ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Signup409ApplicationProblemPlusJSONResponse Problem

func (response Signup409ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Signup422ApplicationProblemPlusJSONResponse Problem

func (response Signup422ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Signup429ApplicationProblemPlusJSONResponse struct {
	RateLimitedApplicationProblemPlusJSONResponse
}

func (response Signup429ApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type SignupdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SignupdefaultApplicationProblemPlusJSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDayRequestObject struct {
	Date RecordDate `json:"date"`
}

type DeleteDayResponseObject interface {
	VisitDeleteDayResponse(w http.ResponseWriter) error
}

type DeleteDay204Response struct {
}

func (response DeleteDay204Response) VisitDeleteDayResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDay400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response DeleteDay400ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDay401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response DeleteDay401ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDay403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response DeleteDay403ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDay404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteDay404ApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteDaydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteDaydefaultApplicationProblemPlusJSONResponse) VisitDeleteDayResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiariesRequestObject struct {
	Params ListDiariesParams
}

type ListDiariesResponseObject interface {
	VisitListDiariesResponse(w http.ResponseWriter) error
}

type ListDiaries200JSONResponse DiaryList

func (response ListDiaries200JSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiaries400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response ListDiaries400ApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiaries401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response ListDiaries401ApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiaries422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response ListDiaries422ApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListDiariesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListDiariesdefaultApplicationProblemPlusJSONResponse) VisitListDiariesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiaryRequestObject struct {
	Date RecordDate `json:"date"`
}

type GetDiaryResponseObject interface {
	VisitGetDiaryResponse(w http.ResponseWriter) error
}

type GetDiary200JSONResponse Diary

func (response GetDiary200JSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiary400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetDiary400ApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiary401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetDiary401ApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiary404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetDiary404ApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDiarydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetDiarydefaultApplicationProblemPlusJSONResponse) VisitGetDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiaryRequestObject struct {
	Date RecordDate `json:"date"`
	Body *PutDiaryJSONRequestBody
}

type PutDiaryResponseObject interface {
	VisitPutDiaryResponse(w http.ResponseWriter) error
}

type PutDiary200JSONResponse Diary

func (response PutDiary200JSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PutDiary400ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response PutDiary401ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary403ApplicationProblemPlusJSONResponse struct {
	CrossOriginRejectedApplicationProblemPlusJSONResponse
}

func (response PutDiary403ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response PutDiary404ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiary422ApplicationProblemPlusJSONResponse struct {
	UnprocessableApplicationProblemPlusJSONResponse
}

func (response PutDiary422ApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type PutDiarydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PutDiarydefaultApplicationProblemPlusJSONResponse) VisitPutDiaryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthenticatedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMedefaultApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListResourcesRequestObject struct {
}

type ListResourcesResponseObject interface {
	VisitListResourcesResponse(w http.ResponseWriter) error
}

type ListResources200JSONResponse ResourceList

func (response ListResources200JSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListResourcesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListResourcesdefaultApplicationProblemPlusJSONResponse) VisitListResourcesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login 로그인
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout 로그아웃
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetAuthRequirements 가입 화면이 알아야 하는 규칙
	// (GET /api/v1/auth/requirements)
	GetAuthRequirements(ctx context.Context, request GetAuthRequirementsRequestObject) (GetAuthRequirementsResponseObject, error)
	// Signup 가입
	// (POST /api/v1/auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)
	// DeleteDay 하루를 지운다
	// (DELETE /api/v1/days/{date})
	DeleteDay(ctx context.Context, request DeleteDayRequestObject) (DeleteDayResponseObject, error)
	// ListDiaries 한 달의 일기 목록, 또는 검색
	// (GET /api/v1/diaries)
	ListDiaries(ctx context.Context, request ListDiariesRequestObject) (ListDiariesResponseObject, error)
	// GetDiary 하루의 일기
	// (GET /api/v1/diaries/{date})
	GetDiary(ctx context.Context, request GetDiaryRequestObject) (GetDiaryResponseObject, error)
	// PutDiary 일기를 고치고 확인한다
	// (PUT /api/v1/diaries/{date})
	PutDiary(ctx context.Context, request PutDiaryRequestObject) (PutDiaryResponseObject, error)
	// GetMe 로그인한 사용자와 설정
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListResources 도움이 필요할 때 연락할 수 있는 곳
	// (GET /api/v1/resources)
	ListResources(ctx context.Context, request ListResourcesRequestObject) (ListResourcesResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAuthRequirements operation middleware
func (sh *strictHandler) GetAuthRequirements(ctx *echo.Context) error {
	var request GetAuthRequirementsRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthRequirements(ctx.Request().Context(), request.(GetAuthRequirementsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthRequirements")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAuthRequirementsResponseObject); ok {
		return validResponse.VisitGetAuthRequirementsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Signup operation middleware
func (sh *strictHandler) Signup(ctx *echo.Context) error {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx.Request().Context(), request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		return validResponse.VisitSignupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteDay operation middleware
func (sh *strictHandler) DeleteDay(ctx *echo.Context, date RecordDate) error {
	var request DeleteDayRequestObject

	request.Date = date

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDay(ctx.Request().Context(), request.(DeleteDayRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDay")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteDayResponseObject); ok {
		return validResponse.VisitDeleteDayResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListDiaries operation middleware
func (sh *strictHandler) ListDiaries(ctx *echo.Context, params ListDiariesParams) error {
	var request ListDiariesRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListDiaries(ctx.Request().Context(), request.(ListDiariesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDiaries")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListDiariesResponseObject); ok {
		return validResponse.VisitListDiariesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDiary operation middleware
func (sh *strictHandler) GetDiary(ctx *echo.Context, date RecordDate) error {
	var request GetDiaryRequestObject

	request.Date = date

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDiary(ctx.Request().Context(), request.(GetDiaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDiary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDiaryResponseObject); ok {
		return validResponse.VisitGetDiaryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PutDiary operation middleware
func (sh *strictHandler) PutDiary(ctx *echo.Context, date RecordDate) error {
	var request PutDiaryRequestObject

	request.Date = date

	var body PutDiaryJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PutDiary(ctx.Request().Context(), request.(PutDiaryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDiary")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PutDiaryResponseObject); ok {
		return validResponse.VisitPutDiaryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx *echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListResources operation middleware
func (sh *strictHandler) ListResources(ctx *echo.Context) error {
	var request ListResourcesRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListResources(ctx.Request().Context(), request.(ListResourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListResources")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListResourcesResponseObject); ok {
		return validResponse.VisitListResourcesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zH1tdxNHuuBfqaO5H+xZWcjGmR18z3zgkuSGnTDJ4eVkczHr7lgN1o3UUqQ2gzd4jzAdRoPEIgcLiyD5",
	"KovAhnhOFLsBsTEz/2U/qkr/YU899dLVrWpLJgm5HzKD7e6up5563t/qy9hiLpvP2ZbtFGNzX8aWLDNl",
	"FeCfpzKWWbBS56xiMZ2zT+Vyn6ct+vuUVVwspPNOOmfH5mLE7ZGvGoj8oz1Y6+DHB4hsl8g3Hq50Jowz",
	"5rWpk1esPySNyUQsHitYXyynC1YqNucUlq14rLi4ZGVN+klnJW/F5mJFp5C2r8RWV+Oxo6yaQMYHjpP/",
	"yM6s/DM6Z2atc2nH+sOH5rV/Rh+bztIfjhmk5fX323FEvvFI4wbZrBG3iW9vIOOctbhcsIx+t4TwnQ2E",
	"XzzAtzdwpZOYtwX0Bn2QrUdaDUTaLtnzECk38LOvSMtjDx9pd6vxWN4smFnL4Zg+ay3mCql3TUez036v",
	"i79tIbzWJtvNBDI+/fTTT6fOnJl6910D9Q88BkEsHkvTh/OmsxSLx2wzSxdM0Q8eBtg/FazLsbnYb475",
	"NHCM/bV4TIEJIC5YxXzOLloA8L+YqbPWF8tW0aE/LeZsx7Lhn2Y+n0kvmhT2Y/lC7rOMlf0v/16kG/ly",
	"zHU/Zm+xRUOH/s0G2fsbaXmI/kfR7/bIgxLC21tku4RI/TY7PDRhXDUz6RSAsXDZTGeslDEZW43HThVy",
	"xeJHhfSVtH3W+ndr0aFYeXsbwJUOftxD5EWT7AExDf53g7Q8sl0CAtz38FoPyV2ynSxSkBdyAPNCgQPN",
	"dvOnnPN+btl+q1vov+xxWiSbNUS6f6fcwWgUDmbzFgPbzjkLlylwDFTxxbcNafc+8Gyjgx83Egjv9/Bu",
	"j/7GWMylLAN/20T957v4hTuoNykbrcZjZ03H+jCdTb9t0nDLeNdDZKtGHh0gUmniu+7gfpkhs2A61kKG",
	"AWVMxuKqlD5rOYWVqZOXHaswLDxwpUMqTfG5eqPf6/ZfVSmz0COrdPATDxGvfKiQyKbtdHY5G5ubjgtJ",
	"lrYd64pVoPtYjccu2Oays2TZDkXOW8bat83+yx5p9Qb1BhcBpN7o/9DFaw0psz2Eb7Tw2i7D5XIQWkae",
	"F+x8IbdoFYvmZxnrrRJp92tKjiDIhSDD21WEuw9Jy6VaBliK8hh90ouUbglkXE5bmVTRAL687+HbNTSo",
	"u/hek7R6FDe44vV7oCwoGBw2CvrJZWfpLDv+rDAD8oVc3io4aSbuF6ng538Jw18iW1/RJQd1l3yzMag3",
	"Eb77gLQaVDBTFqTCrVdGg2otgfCzHbzOHi03uNpyrGxxFAJPsfX/tWDaDj0uToZmoWCu0J9T6WI+Y64s",
	"UL23kDWvLWQs+4qzpOGHFyUwUVoefuKCZHjexFXKDSWyVaPojsVj1jUzm6dkMJscpniquovFP+cKqZGn",
	"zp8LoJZpUsFqF/2PxX0kR+/nkoQn9xlVBBQcdnpMNw+f3HKRiYXDAL1QBFYOAgYv6tYLnAVlj1QqTbFr",
	"Zj5WVr5sZopWPATM52k7NeZR/5E+uhqPXbUKxTTjtZAtsLZLvnlKtmpcc/b325zwgAR3e8Rtgoat1tQj",
	"jc0kZ343lTwxNZOMxWNZ89qHnFKOz8SppBM/+rJOsUlV/MBefPgOwdQf+a5DlMiYhJLg//mKKqd523Cs",
	"QrZoUOqkW6u/7nulODLyhfRVc3HFQP0usHK7jvc9RPYa+Mku7j4lr3biyChadjHtpK9aCynTMQ2Et8uk",
	"VaV82fdKFCNCRTf4m/F528hR6C2zuOAUTLt42SoYCFdLgwcbCK8BCFShP+jhFyV08jSiJvMrl9zuUK1J",
	"reBb3+Jag9z30KDukQc9ZlULwGoNEFp7N5lxbNlUg1yMwRZjlDBgU7F4LAh5LB4bgkpBrjgMiVzFrgji",
	"1+DstCAOzSCtA4TrVSpdyVaZSZ8gfWbTxSL9/NDHpGzDd7rUmBCqhopsOMcjCjJB3WE5llt2UkKFhsj9",
	"wQbXDL48heOpu7hS5VAkEBPHqP+ySV49oAqEGwBUndRdRG6WOWtQKYj3PbK5SzoNUj9A3AD6OfYR4hSB",
	"VWV7EdxCDx602plcSuMJMdoE+V1pkq31Qb1NDxT0Z6+L96m595RUWgq5Xc2lF6kLtLhkOloyejdtFla0",
	"Cu9yupC1UgsmE3KZzEeXY3MXD8fK+XTWKjpmNh9bvTRkqWyX4QD/SpoHlIEGD+pgtoBx1u/eSCCQW3tl",
	"fNeVf1RsGvraUw/Zy5mMdPnoD8xgoTYb1YPcgxzXr4vHio7pLI88bsDSOfYoPW7rmqMh0Zs3BjebVBwb",
	"qYJ52TEovMQrk3o5Tu1tjlH4tb97qnmFE80eBrLdruJ7wGb42Y+AmLU22axRkYJflZF40EOksUPfRQF1",
	"QLZvkPY6Ind2qECSyKQL41pTOuxDxLCcB/LkZz7mSYeonfvcHK8cV/EgQQVW0vEC4PvDNPOug5Qp2XMs",
	"PmUHt5zNUiofxajsi5HwnJOkEpK07LS56uBaAA6w7R8UVc/BM6q7ZPuGjtLhPBV6Cb7HXwDPKKhaAAwV",
	"1dEMLzAyhN2jM9DldKHoLGTSti5IxUX1gw381KO6mErc1gGjeaqIv0Ok4yZQv9cDXtlq4NYB6NBOCbAQ",
	"oHUg31dMgG/VyKYf+hnaZNFO5/OWhkf7eyVy86/kvgdW01qDNHaoy4mf7AJA9S38dYeCl0DsSdTf6/b3",
	"DyjrqWpzeMGji5ERfKPgNZIiL+TFeR3BCI0QXq2Dfq9Lt84DfEHrcDqZTCaPZiDCOjrQP8xB9ElGz44A",
	"u5U10xmwVFTDdRRgQZclsKuZ2aNtigGgfFC3wTMaP6RoOU7avjKSRM7x5xSZ9dNcmLi/tA5W30kzizo3",
	"A79ycbeE98qDRg9spu5DP9QIlnqzDaZ7LrdQXMoVqBzkkZztbVzpxBH8KZOzr8i/UHaXf1nMZbM520C4",
	"7Paf7+K1BsI7B6RdQth9RG1rvO/RlQYt5lqr4FQ61IjPms7iklVcgKMB5wE/3aBShjw6ILeq9Ivghte3",
	"qPP7wu3vH6B+9wGDIG1DKGHBshdzqTSFkXnCYOK3XodCELi7QVre4HYPBPjWsAiWWKAygm+b/5PtE7hK",
	"gRfi1kEQtFJb60sPERn1lD9bcSyNkpJ+fo+0vAS6cP79qd/7+4Htuge40pkY1JtUCAjTZAtsjuPyyUnV",
	"mZye+b0uQJBN25EBCPK8SW5VJRx+3MEHIbCCJgIxZF7L1eIKBrTEHuUsnX3/FDox+85/9WOlIlS6WeOh",
	"UvKghIwCk1oL6ZQBzHAHiLK/d3PIlVrkFvwYYbFT9NHVeCDINIbvIYNqVFdYmZTm0GdnZpAmVqZzBMey",
	"pviS79PldO5bAYSIzkT6s2V+viCE5k8AICittCCIE9LpOE8mFxro9LsJRFrruPIc4uH/fYqrpKnTKQMN",
	"Njv4zgaE8EBUJBCLm3OXC5F6Fbc75BH4JNSd3HMRj8XyKED371J4jGE1BAH94Pz5jxFzJxB5vYHvNTkk",
	"1OHud78OxOhmZnQ86KSdjC6Z1m3iblOYoK3XIMS3t+l3SeMGyNvdXv/5ruJQkM1af68qnOVHB4FMUyC0",
	"JE4HpXJWEdk5B2Uty0HOkoXyuUwaoh1DOGC/GDoqxoQsNERZrd8t4Se7g7UOhfjC2dOIdHvk224CGSIm",
	"XTz2JWW61WBW0IfOfy5AjLGRdgz9q0CoYqABhwcI7hCRc0rr0LNdKjEwFuQuUcGMS9UAphPCjKZH1fLg",
	"SeZJk3oZr4mDA1ztt/HjHt+/CASEpYCieRYLVsqynbSZofsK5QfoTnUZOGqi5gqfpVMpi2o1me6iQthy",
	"lnKpBforM5PJ/RkeBnW34Jifw+N5cyWTM1MLoCTNwhULFi4u5/O5AvULs1YqbS5w1IfPKxzZoqegJIhg",
	"Z45VsM3MglUo5JgNVLiaXrQWlm3zqplmQQOtnlUl3LAxFJGUQODqgWSRKYcGD7InEPnHAX6yi/B2h3Lf",
	"fomUG0IA0i9Q24SH473gmQkLQY2GAyVmrf+Zsy3fuf5Cu5cjJNVxZRe3H/MfuXeKK2XcOogrgoDuqdLs",
	"d11cLQHh3SzjvddollQgF8qIFoy1egM/2uExDRCO8M12fVD3QDhK6anmdRKIPHxF6j+AmIaYkJClLJzR",
	"33fJWtd3lWWhQnR8+3KukDUdvxJAg6NibrmwqDHYA/gaYtz7PdJuxiHNdL+D8F2XPCxB3EahkK0yvr1B",
	"tkuAmyoEoQf1Jl6vMQ/2cRDsWYbauIhvUmyCEeqROnXNwN641yH3PdJx6aHgrSo1Zclmt7/XxXcPyDcb",
	"Cd0WtZpwq0Ye1iikAbna32+Tdh3XmpJ2hcyBQCuF5XUD3qISxuNpRvzsKUTWXdTf26XAgYK8NySAi8vp",
	"xXTKWsgXrKtUvOTshenkCR3IrHzjS+VdCvCaRxpl3H1Kbt7AFY+03cGDDd3b+aWcNhgBLzDXIaHEJPov",
	"e5yepYqDUpn+Dz3Bo6T8HTWEt6sIr+3093aQ4ViZOUg0YveRRhNq9xWONqVEoYoAORgy1WkTQa4jQmNh",
	"Xv8rWKn7++wctyBBCnHDce0uySZvHkILO7ZD0Ju2mVkpposLlk3Fs0783nAhBsTibA+oHgTO4OfS60IO",
	"DBI/iFTawmN9vR42WThwn+VyGcsEMzJlXTaXM85CdgyzfShQT10eK5srrKigD6+RzeVSC/n04ueHP1aw",
	"smk7ZRXGfIpqAw2x16v4yYEMrUsZ7gtwKs3x3mv6874r5C2LUxoffDB35kyUHTWTnEsmQYU7VMnG5mL/",
	"Y+JicvrSxeTUiUvXZy4mp45fmpy7mJx6h/3qn0ZywtCOw9sLnU98mFaGTkCHbi1Zpq/Yy/k3i0ZFVwUY",
	"//reeXTMzKePXZ0+Rs2pYwXFcYdqO9IRuTMuQCF39Y0HGbZAblcmdZmf+UYFA1nz2mn23vTvDi8fGFEz",
	"kED4lUseVhFebyjeTULGTvef4+4PoArvUzmKZpN0H6zmBncfSh5UwnC/T2qk+NsP9SmW1RAOTp/800mf",
	"dzguJkijPIeMk8W0eeyclVvOGJMJhHtV3Dog33RJG3jMOG07mQS1ws6ns9b7YJBMTCYKVjGXuWqlPoIV",
	"ihOTCbr4v+Vsy2AWkcvL4ZiJwywqyPTtvaaGEJV+Ko+LokDfLWDmEs/3sI95IsnAcmkq5Gohp4K2380e",
	"OSKqBDJ0DOdnjoaQfOH8KSmxMNglxCsj4vZ4iF5UbkkrJUpACQvw/PTMXJKKq0Qymfy3sD04xWVLcH/x",
	"2LWpK7kp/ssL509RgKFEiodhQzKgYB09ZXZEjgPD+Uip0MP4KcJAlKhZXk6ntHZkcSFlZXMaaNcb+D92",
	"8b7X73Wp2GLkxzOY9z2y7QIttuusDkurf4/IeYHz9ql4PJtrtFslthpXj1dHzJ8UT54+r82nnDwNkn27",
	"Bs7QWkOmt6FU7NZzss2CrsIMC1IV87XHT7x/wmt6NXl3g6rMjBFHxuX0NStF/+FY2XzGdEDSCJXDoOQl",
	"oEXri0Dho7YMTOSRIiM6wo010wuhXNDhkRa6unRtOSb0yD+VSVu2c8YqFs0rGtIZ3PCoKG555H6PB+15",
	"eQ/5wcVujdv8eA0yDPjpBnVkt0sJZNC1DCFHqSTqslNKpen3s2nbdHIFpmHyeV4xY9mp6ON5DwIjRccs",
	"ONEPnYM/s4QPQ1nko1QYAeGtStJZ+RMregc8rcZjOdsai3LYqqvxUc8pS456lO529RIcEeQpz1pmaiUy",
	"56gUM3RK+JWLazWWAleNqFTaLKSt4rEvqeReNXh+RloTQfYpQORj4ejJ7DDp0lVXFgoA/rjkqy6uJ9v3",
	"WD3coZZm2PNp4TUqXxHecwe3D8A8KFdxm6XJWYwF+jksO2WlAD248lzWNIUywKFdUsodb3eR+4lKHxqU",
	"lg00An4jncpYBkRH7j4g9TKVm7yYntwX8XVg38p3vEAikHbjiU76FW0kDEDUepQgDuDLokI6gdjKEFX5",
	"FppkoDGGyokDGfoDk4rXlosIDRWh7Q4kBG6WgUDhI4O6hwzgfIMXnTGrbuhYGLFZ1/KyLeNQdhFFQlBZ",
	"slXmRgHp9mQ0jXMT1P0YCikz/6PBA3T9H7pk+x6vrxAfL6n6uxQKRAfrUaha849rs8yiQnEFTmq93X0Q",
	"tAv8HDJ35xulcF1SwNsV5DVS8PipoZ9NCgBPHYH/AYDg+vHw6UZwEoSrh0+eJ61cXlzKrUH87EdeBxQq",
	"LbrnsRIbqHkPBz9C9iuo0IUs06H6tBmrpYcvKhDgSgfhtSYSSYweqM5+rwRRyZs3+l6JB8n5E6x8jXGP",
	"aotHGZzjpFA5ykQKdejkAJ/jnhwseMjB6JM4soaA49BA/+3cR3+StamSH/CzHfwYLA1uXrQ85U/k/jp9",
	"ZVAp4Tb3+QxxKDJJYvhGCsgsVk4xuLHLXwi0yaBgRw2VOzc5sWy1oSb26w7EP1la0RiiBK5FWP2s4otC",
	"axMINLqKEG370JohajdYn5eEVgi+m7xkwjAzIImGP0MfXK9RQzn4QiA5lEtZBo+Ts2zZwyF5wkthpVtr",
	"LCpRuwWmJcGZ+L7HZH+Tv8gwNI4Ap18NJpoMkQomz15DkL/NnG/OjKRdIluPcU115QI54sQRDsPDd91A",
	"Naeg+RA5QmgsREfDCTPlSGPxWOh0wrk5FoMbRuhw4k2vjD+S3k24RLgm1Vqb4jCBuP0gxVsccX9GHPPJ",
	"09KzQfj7Hn6yi8idHYTXN3hCNA59BcLhCSSzBuvNQcOFJXmtEVuZBRjo+4NGXWtpAAxQpHcNti0WiNhw",
	"hP3LiQocxcpzZngEWab7EOibMyoTwKoloi/jD5zMmN79GyvLAk8NFBfyadu2IsougrWxkC5DfhJKScYA",
	"6inH4fUa2eQZtIQwa556qL+/DR6dhwy5tGLQRJgPxeWsFrRND7c7gMc7DaTU18MK1PNjPRzCOvKNq6DV",
	"dLMsdsgi6D6QUONaL+MXILEN7gsbAd9fEw4J6bEoDyQeW3Ycq2Dai9qaL3UXAr4GFZwg7rrNwYONBCLl",
	"Jt4rsxSYEH4CFVBx68I+jlSn80nxgoBrZMpIKt8g0YbtJ3GGgS1ryE+vv0UCS4MlPfE1glSaUHhReAVB",
	"3wHqggIRSvYhrdX1a2TqdFQlkDKuhRSd3vukeM4qXLUKkcEYxYn75WIwItQUSZY8XBcPePaRTyvBizj3",
	"Ag5zPVidCzPhDzVXmZdw2MpiUf+IDnlUPBKPOUtp+3PARdTT58UTPz1wxGAcHQ1Slhz1KD+e0Q/6mx4r",
	"GmWlxnhOOe0xPgrnyINc5/KW+bm2/bzsBnxkHv8OWRNmOsJuYKG5I4aKhprEuFRnEY1t6KjnsWjFlkVU",
	"FT7pKlJNiSkwazjguYOWe9nT6EyXhxXUCiPWlFTCaw1816W/1ipeGDMipQT3JFjkaL+tqqXHUPYiLd9Q",
	"ETT30saLnA8n8y/pMcodioTidxiLS6Zj8G51ERzhrk+/+zV3eA3mGkwMuzCTitmiEc8sWjyuaM5GO6+S",
	"ATUKR1Yt1V3unwzul6GOovIcnBMIIg3qDR5mYnukzzfoTm9v8IYkavj0utC7JwJ0AXOWbbUTTEAe2fX8",
	"ieELvxALbDrOjSNtY54OGZ6uIb75ArbBDKlYfFTeJHTMUmaPHaYY2jMDUX/4Mmx/NDGiCyjxJNGbHIIm",
	"FdPvlbg0UuULmFak0sL7LtmqTRiLhZW8k0sUTDuVy164cPrdiUljEhpOONoMQcCiV9ILEI5fZymrp4Gs",
	"73mqvy2mUDA/XTSiblely+672SOpJaK/aqg8YrPEG83gV6IWHobJsNCdmrHXlU3MjG7JGqY2P7f0U8gt",
	"srdLNfx17YC+4yHzohFeisFC1cBfFa+/txOVKx1HBKheP2+4feopBMJYuOcTHi9pgRZNLglVGmuKOGd/",
	"b5eXsULdDqcqmfzlCwUy9WECGpm5f8MSAz+HPF7mOELOCWu9XmbeO3iQIOkSKIlflAauSB6TjadIX6tO",
	"yk2q2ANVltDhOVJYFn3LakQWkz8YnZgOUTfLMovvS3T5Dcsasj+0GgAQuLhcSDsr5yhYou/v0DFucn4P",
	"60qD4QWiKcVDpLLrz14TE+Z4igoKxksId7uDu7uIuB0osHAR3uiy4v/EvP3B+fMfn6Pu6nZVcbLYsxNs",
	"FNykPwuOfVS4ncbCwge5ojPFRsMpY+HEqLVFtiU5bM02rXRmge/XF4xmPv1Ha4WN/knbl3X1I2vQFKwU",
	"f9/rUnjOvnfuPDr58WlmcjzbgdDc3mvufhs8M2xAmH2rAa6yaMmbt3/zG0QV/JPWvK3OSPLbdUCvDY3u",
	"A4QzFLNf0pXEbD1DdCff7gxu7OInr0XnXKBREIqH1SowWAkyOELf1atUtLhB20bsv4QGt9qDG134JKt8",
	"p5bWo51QFo6rLj5LjUfWXpTwYw9/D4xmXLacxSVDHQ9x9wHZWsfbVdE5AnsE+Cod5mAL5AUntfE6/MYO",
	"38i8zbqTWJByo//3HhAQ/G3i44/OnY+jjy/Q/zl5/tQHcfTuex++d/69SaZpVaiplFQw5Y9+E6XlYTSy",
	"aR8hawJEkniT3Pf8cR6JeftII+dKyJhNHkf6kXMQiPihS2Ue96kor1E0VjqiU3XtQJ5eSSSKOUYFd2/u",
	"ivIutQuCMb1CrFx2sl5WVtlH3+cTZ2Rzgf+VcJKWN6jwyiuPcs+gUgIfT22ipUzFzfDZ5DTS9AQZIqj5",
	"Qw8/YQKJlWPddUV33LzN52BRxT2bPIGUbh/qIMHJ80YXuSGefRnaF3MrqM6udIAJ2A75SABSr/b320Ds",
	"6zI2q4Ag5lyw9gmJTmhqkAM62HQefKcbRwwedSIJDO4h7TLp7gDN8d5fqEwQMzjWa1QUkW+6rDeN0TST",
	"2zzNfZcBTe2Gp3iv7s8G5J4Rl2QsuBUkDAGIbH6GXboI335CXmzIX5REh/O+K74BFRTuhDE7cwIFZ+bh",
	"f9Qkonh/tHTcELnZohLiqSAyUCxyi2JqWXCbFJ67goCZUw8NQDVVAkPid94W3Xz8zZL4ohE1Ws6YEB25",
	"kyLg7lsUfHQhS8WBWxrZAAeOQtrJWAaTPeM1P4bHdRzaAZnQbI+Lk4DpKqt6aw2GN52BD4i7Llo/ryO6",
	"U3Qd4eaP6Pq8fX1qakr+R5+bTSbRdV2HL7qOxp8V6iemWe9aXMiJwU1KDHHerI2IV+7vH8RR/9UO2XYh",
	"yz2JOBzTFA6d7KCQKEwPQl0RPxAdkzlvMbaPPHvNvHM4Ia2ACywcHmlIUXbUwYj8e8fp9/Tyn371yPNL",
	"1c/KfskAgKDx75f5dKtBva32F3Ks+R+apR/yZ4tS9HJBD/JEKSoYa1BpAuG1HWEhfNuiIl1+7ya1SXFj",
	"Hfje8+vJBCjvUFCGez0pTBAcAYAAL8H8/NMNaoHdUz91gn5K1RmcbBT10AzSkXx3GlA71E8KKObTTr1g",
	"pYR48R1GOrqm0+DbATEF4smv7vC/NzMTyYtvMOTyCOMsA+sHG+3pNkLcxkejUdkUkgQJ8LmLOZuvCbM9",
	"WNWdbqWh+XLo+tAMTHj7VZt8WxWcNzy8rSznHUHTgLpfMSNQv18gmmDJy3UUPUY2gQxlVKxs8ae2o1fG",
	"29XBjQM5FLYrl3mHidhwncd1baWHeAVIUtNyDO/J8LGopGoHqgqDxTmh+bViEaZdoVVi3hYNIFKtXjh/",
	"SnRyRfVCKM1doGqPHz9+Iq5tuuDJzElpxqpxfWrKHPR7XapYlBYVLmRK6vp8xUbwA2A+g2jihTLq36iw",
	"iGhMVppihLE4fo9yTdb47L1G0/wvQLR+HqLt0jWVzYgRbVxDlekaQMMivKxAriiv6O5nYc++Wc8zo4D/",
	"WyOV5rzNnWNugFDn/ZS5uGRNncrZTiGXmUN2bqro5MScd+nMK2/w2ZrqhhnHdaFqt15lslD1ENU0Lpr4",
	"xPrsXG7xc8uZnLd9PFIfPtBPjuRzwgeFdlslgaK6+H8uHrs6fUwtDfAblRSzhnodedNZAuHBju+GIlip",
	"S0hRurlLSZVV0rAZnjfYUHwFBD9jwTrzWGEeGJ0i6pTgUScWm1znB6JrNpAhF26vG6GWBSOuJrw0Twdy",
	"6oZA/hT67W9ZcOO3v50DFCvjQYaDRUMuN0sFCldmyMUWwQlSeSTJDUUYVCJDyL5IUd7YFU6iNEDBsQzb",
	"aPFDjCnBA5se2RRJyBGOOavhk8CuNxBEWpru0EgfPv8JHAIhA1najmpkBRvM0+0MqjswpZJvsTE8mEVY",
	"Cm4gMiTm3WldBiS/57HM626oNU/tfciyQe3yBJAffJFzJNlnKWVIAqbEMfjqDoXpdg8NNlzcLpMtV0Rr",
	"N2tgwqN+t0X2PL8BKFR6ERrB0pXRONVlYMOxHoZ3ScFhLimFRQImIKBHfmOXqw+lCORVGd91uUzGd11l",
	"2BbCriA5mVYdrpKNh8yCyUC9O+Co8t1gq8GPkMKmyGlJyrjyHfwfTDPohqyz6WQy+b9mTpw4AUhYb5JO",
	"Cc6SSvmmeLB1QN9UMuYywNlTRkRQNy7JS7AeH4gkAqURYzaZnDaUsJmI5jQk80gqCifiAzla3PxR3ABC",
	"vzljBEJDcGPJwypp96DVQSRkyopd4n9E0m8LyqRYkblshLjv8agQQPuqiit/EwERivIyD03qhCX/yNZf",
	"wnFO/xoDdmwsCHFAaYmK+R7IS74In4MtvxVwq3H36eD+Y3QdUfo+xK0OQYf+362vhbl3XVQC09cjKy0i",
	"KymiKybQGCvL3B3YkboE7RgfsZjXeGhHDvsOf4e+Hv7kdZGe8xEiq1iFXSBSafGgbRTXJfxwi6mRQIJw",
	"DCBkEpg6WW9SyzDOIqJmE133E3vjYUiUp1LPaJwqw3G+ykvXryNN79I476t9QOBlH9KDNxY80iEa0aTC",
	"/JZBq8YzV1SWtP8iuHM6Iavt4Xi0BfdqoxvbQaDRDeRSqHz1CJW42lQ0qBpYK+HXnTIfVSVW4SZDrK9D",
	"BS3Awt8MF6myeuVxS5oT8/ZMQpC3IgRk6WQYN5z26+BFKkwihCRoBtKqiuD6k12Ws+JJx0DbmERTqPMB",
	"IcSDnYf0NScQ+bZLfRq+8FoDl9sRcU+KLaWmw1OrhaSdecSCIYSf/QVgE2XzTDuNqvI4nlDsAeVIJA48",
	"Kcvl6KNDqoH1rM8dMGUoERBd2aWGlZ/AYEmX/l7Vz2jNJtBx/MIl33fUxrvmQTC3GSBwWe+3+yObbfSy",
	"h7ca0EES/gIXMBM8FjSHoDdzMnz+7yQ0KqTE1Es002q6UxP8t4lgg1yIRQ7vfRyycpggGKf/kR0jC7aM",
	"bDj2OxpF6zEXOb4VJqoWb/f3DihY4aV5P9ywjSNGTbXEsC/Ses2zirBL/4i1ASIFoN8lVIAoJDtw0tIp",
	"9/tslTJMtaM1su3JU5gwsvJTzHyTtUwum5P2I1BxtYYrO1QjQPrS/3LEsENPOKSQ020o7jFeawhJvV2D",
	"ULWqStV8F9dRIjagbZUcnZiRMyBlxcLJj08rN6DMxZKJmUQSSm/ylm3m07G52PFEMnGcDUtagnqQwFCg",
	"TI5X6ORzRe1Mbh7wht2FBjHLbKWojRVJDVfUxirRnUBQIJzv97NVQ4/hjR7Qx4MNxYAVCzEyZ1O3KAA8",
	"8S2UjJ8LZE40xJbAI5iQyQ2+v7guM83KBfjlZMGxgZqjyeWtAgSITqdiczGGWDmc819yrP0q4lKro11m",
	"FRhfvhosK+LXUASuCpxJJn+2tQN3HR12HRiz34IXpZ2znCm/Dkm3DH/4WPDuSVhnlu1C95bc7THlVkR4",
	"ZfqtXo44bpoRTWgzlZMM5uOjt6m7RJG+O3Ni9Lvq7Xr+3LnR7/kb98vMYnMXL8VjRTFQzz99KqrMK0UY",
	"vrLsLMUu0bfCkie37BwieliexpcplNUpnw/fchq0sl6U8X/sgpUFFydAxolPUPazrmTzlsgHKR24uzx6",
	"MJOcjWZrCvUQg81GFtbVXfLwphgoEgK+yy9AFVxhBATjm/KO9tJYzkJvTlu/BJ0AbkaTSiE0cv6K7l4N",
	"ldl4ipHVCvCaHDY1m/nmiioPXwIGY82UFKGsMemU1BofzShkqvZYQBayPHVSd6GFVIm9sfC/Ky6D4vV3",
	"ysRP3uLnpyJ51BOqc6SS9OeFqnVfvQiSvWI5Q9cL/uIKInDfnubKReWOrJ+duEInpLPf2MIjCa8Ioxmj",
	"ZZSIX6rOQHTZl+wwaL9F28iLoAq+tV/GQAmOtBzLQpl+axYKFwg8Lvefy1z5Cao/eeJtmzqHlsZMBIpp",
	"mGUzM/NWL6Y9pLRl3g6VqUzIwpPJuKawZMKXyPTvwyU2E6JWZlI30Y4y4H8G84wd16FyL2WuiIgDk3cZ",
	"Szu9/WWPVyfICchKOU3rAPkPMC89zsOU8eB4ZHFFbf/lQf+Hbly8xmvJ2e1YVGfefy5CWfWd/o8Nxfab",
	"t9m/pVPOnOgnXrCm5cUGcVl8a20H3DpWYyAyQxB1CMwrnbd9FY93PbL5F5iO4y//sMoqLEQJNMQw/TjX",
	"HdGXGByhod4AEhywOm/LzatRkUCfvzaPAx2PAbBEA6w8g0DRnZ/OnkV+HZ/s6vi+x7EL6RL/AktusbY7",
	"aFBnUcyXPRk+H9IvjHDeNVfGspUB8DbvQn1zR+/wV8KXZP9kiTs7+l15P/wbs7JkXl5rpDo+CifzYGHs",
	"EgwgLphZywEtFtF87D8SGKZySZUE/ItRBreRzdnOEruV6AvNIM/tqn+JniiGeHQg2ir834TKDmaTSTQs",
	"X/3CE74s4OGRzwqVXUUYPT4QZVDlZqganpc8wXNqbT0l9ZKIpgMH3hLJeuMLdTW83+NlSrLm6YAV9VCR",
	"JXpy+eBsGF8nuypZDT153uy/FADy9rWQj4EQadyAgg4IcpJbVXbjoH8NTbjVItjbWRKjr9XCtqEmT3ER",
	"ITihszMzKFqtzaGLX1wyJiV0ETdHUm8IItRQxSvXpgcn8hQNZPj3CkJhwXhXNMqRgtFXnJJWY9Qtp+HP",
	"6Tz8dNF5l5P+ECuFLAweGK+8YDUIuwlkfPrpp59OHTa6HqoRRQfbF8tWYcVvYAPSjqk3/ysj7mGU/Zez",
	"q1MTyYvTUycuXZ++mJyauTSpnW4feetkxMpfBFYNXrs46n7CS7+gN+lfw6o1QiElw0grgfD2lj8sSVF0",
	"cGMnJz/vV9AxzOwd9V6+kFu0ikXow/05lEUzKBM5BuIIN2o+92sVyLAOUAxCrSoYsgapAA4KXB3bGiw7",
	"6DddR15cO8TXugtpQ1cZ+78V08sASpmjhSVFQ6YyPqshr153eV5J9mb7JQrQrsTSDuGNMWVD6i5PR4Xu",
	"UmCrh6rmVFstoJsOsdWUfO/2X1n8shFOT7Ku2s66uO3prjveVFSW3WqPtPKuWA67vvuXFgFaRz6Esrdu",
	"O/4a9p+y3Z/d+IvH8su6yCprKmK8hXSEimuNEC/43Mr+zuvSJOn199vkVSM4yYfHNAVrtDnFSpuq5QZv",
	"SpKek3/tl+hKlFcJ+0nYkIxhrmXwqh52v+rQtXeR7MmsIFbe7ee3xV3pcjBfOO43Pv+RzRpYUkKAhNLz",
	"/I51pZSToUNIttDHGEAaUQIb5OZRlCEpCnoibElW0DLaiqQSXxqSQ+Ikv6yIk58/LKneWP2W06aRQszX",
	"Ur+SEHuLDvCvYgn5/MJkDgRpFO07ygRit6NozR6opXYR2fRYbilUHc+7xlj2gfdR4ztdwdR8UstscloM",
	"g5Hvc19IVhT7ExpCbaPcPJhNTvf3D2QU6ChJxgitfsb6JVX6mcNLB4AbhMz7KdT9E0lHDxBkCGGAiUI6",
	"WStINQV12qeeeOACRzB0Nz21Fn8+Ji5z9GQ3I+jC+ZiS05J5Q6AqxbtJ6PtkXNZY68lTP2TS5xsUBU6w",
	"+wgnpfqBWqjOOstbDTcYqaXJ/sBhv3BfziM/xEtXx07+YqQauO9QR7SB6ml2ED9/ulxPEFBm1Xot+ze5",
	"Lt7fVwhTmbC6GlpiaDTQxUvUBuRvfqlNm8V96pL/FFl8HkqAnMJwBELPTIC4SlsJgViad3mIbetxQoTN",
	"9hkxb1Xj3JONUxSQdj3Ou0ARWfsbaTf9DwvhroHs6Njl3/SRu3pp9f8HAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
