apiVersion: apps/v1
kind: Deployment
metadata:
  name: naeil-web
spec:
  template:
    spec:
      containers:
        - name: web
          volumeMounts:
            - name: local-proxy
              mountPath: /etc/caddy/conf.d
              readOnly: true
      volumes:
        - name: local-proxy
          configMap:
            name: naeil-web-local
